### ISSUE TITLE
How to show fragment from MaterialSectionListener

### ISSUE THREAD

**Issue by pawelantczak** [neokree/MaterialNavigationDrawer#100]
Hello.
Is there a possibility to show fragment from listener?
I want to do something like this:
```java
        sectionMonitored = this.newSection("Section", new MaterialSectionListener() {
            @Override
            public void onClick(MaterialSection materialSection) {
                Bundle agruments = new Bundle();
                agruments.putBoolean("key", true);
                DetailsFragment detailsFragment = new DetailsFragment();
                // how to show detailsFragment?
            }
        });
```
Generally speaking, sometimes we have to perform some action and decide what to show.

**Comment by pawelantczak** [comment]
You could unprivate method ```setFragment``` on ```MaterialNavigationDrawer```. It will give us more flexibility.

**Comment by neokree** [comment]
Yes, It will be public from the next release

**Comment by neokree** [comment]
now the <code>setFragment</code> is public
