### ISSUE TITLE
Account photo is not displayed with custom drawable

### ISSUE THREAD

**Issue by vedhavyas** [neokree/MaterialNavigationDrawer#101]
I have a custom drawable which is extended from drawable.

The drawable is displayed in image view but when i pass it to the setPhoto(), the drawable is not being displayed.

**Comment by neokree** [comment]
maybe you miss to call <code>notifyDataAccountChanged()</code> ?

**Comment by Swisyn** [comment]
It gives error; 

 java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.Bitmap it.neokree.materialnavigationdrawer.MaterialAccount.getCircularPhoto()' on a null object reference
            at it.neokree.materialnavigationdrawer.MaterialNavigationDrawer.notifyAccountDataChanged(MaterialNavigationDrawer.java:1005)
            at cuneytayyildiz.com.tubilgisistemi.Activities.MainActivity$getUserProfileImage$1.run(MainActivity.java:105)


its in thread;

   private class getUserProfileImage extends AsyncTask<Void, Void, Void> {

        @Override
        protected Void doInBackground(Void... params) {
            Bitmap profileImage = new RequestHelper(MainActivity.this).getUserProfileImage("1131602623", "17528461138");

            if (profileImage != null) {
                account.setPhoto(profileImage);
                runOnUiThread(new Runnable() {
                    @Override
                    public void run() {
                        notifyAccountDataChanged();
                    }
                });
            }

            return null;
        }
    }

**Comment by h0aX14** [comment]
Replace

    Bitmap profileImage = new RequestHelper(MainActivity.this).getUserProfileImage("1131602623", "17528461138");


With

      MaterialAccount account;
      .....
     account.setPhoto(getResources().getDrawable(R.drawable.user_photo));

**Comment by Swisyn** [comment]
What i want is get user's image from web and show it as bitmap. I have already know to what you said. 
new RequestHelper(MainActivity.this).getUserProfileImage("1131602623", "17528461138"); gets image as bitmap

**Comment by vedhavyas** [comment]
i did call notifydataaccountchanged..
my custom drawable extends shapesrwable ..

**Comment by neokree** [comment]
@vedhavyas try to get the bitmap of that drawable and load the bitmap instead the drawable.
