### ISSUE TITLE
toolbar only on activity

### ISSUE THREAD

**Issue by flatlining** [neokree/MaterialNavigationDrawer#103]
it would be nice if it was possible to create an activity using the toolbar but not a drawer, so if my main  activity call a secondary, that don't have a drawer, i can still use the same toolbar...

**Comment by h0aX14** [comment]
One way to do this to other activity is to make subclass of ActionBarActivity.
Create a layout

    <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="com.example.timepass.sampleapp.SubActivity"
    android:fitsSystemWindows="true">

    <android.support.v7.widget.Toolbar
        android:id="@+id/toolbar"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:background="?attr/colorPrimary"
        app:navigationContentDescription="@string/abc_action_bar_up_description"
        app:navigationIcon="?attr/homeAsUpIndicator"
        app:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar"
        app:popupTheme="@style/ThemeOverlay.AppCompat.Light"
        app:title="@string/action_settings"
        android:fitsSystemWindows="true" />

     </RelativeLayout>

And then create a subclass of ActionBarActivity
and in onCreate(...) method

    android.support.v7.widget.Toolbar toolbar = (android.support.v7.widget.Toolbar)   findViewById(R.id.toolbar);
            setSupportActionBar(toolbar);

**Comment by flatlining** [comment]
thanks! (i'm still a learning this still).
By doing this, main main activity, with the drawer, have the toolbar in primary color and the statusbar is translucent, but the other activity, without the drawer and using your tip, have both the toolbar and statusbar in primary color.
have been looking for the answer with no sucess.
