### ISSUE TITLE
Expandable section

### ISSUE THREAD

**Issue by imanolmi** [neokree/MaterialNavigationDrawer#104]
I would like to be able to add expandable/collapsible sections, as in http://developer.android.com/design/patterns/navigation-drawer.html#Content . 

Is that currently possible?

Best regards

**Comment by neokree** [comment]
Actually no, But I will work to add this feature in future. 
Sincerily, not now. Because first I have to remove all bugs. 
If you want to help, you could implement it forking this project and creating by your own and then do a pull request
Thank you

**Comment by javmarina** [comment]
http://www.google.com/design/spec/components/list-controls.html
Types of list controls > Expand/collapse

**Comment by mkosik** [comment]
@imanolmi, @javmarina I don't think expandable/collapsible sections are ment to be in material design navigation drawer (side nav):
http://www.google.com/design/spec/layout/structure.html#structure-side-nav
http://www.google.com/design/spec/patterns/navigation-drawer.html

If you have e.g. many labels in GMAIL (I have 20+) they are all in drawer list, however the recent ones are brought to the top (you can provide better UX like so). Or there are other means of additional / secondary navigation. You can use a spinner in a toolbar, tabs, etc...

But if you really need expandable/collapsible sections, go ahead and try to implement it according to guidelines posted here & do a pull request as @neokree mentioned.
