### ISSUE TITLE
Photo and Background of profile as url (String)

### ISSUE THREAD

**Issue by N1cE174** [neokree/MaterialNavigationDrawer#105]
Can you add this function in your lib?
I want to use 
```
account.setPhoto(bitmap)
account.setBackground(bitmap2)
```

 like this (url, url2 - String)
```
account.setPhoto(url)
account.setBackground(url2)
```
 and in library downloading image from internet and paste as photo and background.

Now I'm using AsyncTask:
```
	private class Ava_Bg_load extends AsyncTask<String, Void, Void> {
		Bitmap avatar, bg;
		String g_avatar, g_bg;

		@Override
		protected Void doInBackground(String... urls) {
			g_avatar = urls[0];
			g_bg = urls[1];
			try {
				InputStream u_avatar = new java.net.URL(g_avatar).openStream();
				avatar = BitmapFactory.decodeStream(u_avatar);
				if(!g_bg.equalsIgnoreCase("")) {
					InputStream u_bg = new java.net.URL(g_bg).openStream();
					bg = BitmapFactory.decodeStream(u_bg);
				}
			} catch (IOException e) {
				e.printStackTrace();
			}
			return null;
		}
		@Override
		protected void onPostExecute(Void result) {
			account.setPhoto(avatar);
			if(!g_bg.equalsIgnoreCase("")) {	
					account.setBackground(bg);
				} else {
					account.setBackground(getResources().getDrawable(R.drawable.temp_img));
				}
			notifyAccountDataChanged();
		}
	}
But it's very inconvenient
```

I hope you make it.

**Comment by mkosik** [comment]
I think @neokree's answer will be unfortunatelly no for a simple reason - lib complexity.

There are so many popular  file / image downloading & caching libs out there with full blown, networking, async operations, stack, backward compatibility, memory usage & other optimizations & features.

Use whichever lib you prefer for your whole project or write your own module, but creating this from scratch / including some external lib just for this case inside this lib makes no sense - creates unnecessary / unwanted complexity, possible lib versions conflics, etc.
