### ISSUE TITLE
setNotifications not working

### ISSUE THREAD

**Issue by vedhavyas** [neokree/MaterialNavigationDrawer#106]
notifications number is not display with setNotifications() on a section

**Comment by neokree** [comment]
could you post some of your code? Because In the example app it works

**Comment by vedhavyas** [comment]
sure

public void init(Bundle bundle) {
        account = new MaterialAccount("", "", new ColorDrawable(Color.parseColor(TRANSPARENT_COLOR)), getResources().getDrawable(R.drawable.ic_nav_background));
        this.addAccount(account);
        panicSection = this.newSection(PANIC, this.getResources().getDrawable(R.drawable.panic_btn_small), new Panic())
                .setSectionColor(this.getResources().getColor(R.color.teal_500), this.getResources().getColor(R.color.teal_700));
        MaterialSection circleSection = this.newSection(CIRCLES, this.getResources().getDrawable(R.drawable.ic_circles), new Circles())
                .setSectionColor(this.getResources().getColor(R.color.teal_500), this.getResources().getColor(R.color.teal_700))
                .setNotifications(basicController.getEntryCount(Database.CIRCLES_TABLE));

        MaterialSection settingsSection = this.newSection(SETTINGS, this.getResources().getDrawable(R.drawable.ic_settings), new Settings())
                .setSectionColor(this.getResources().getColor(R.color.teal_500), this.getResources().getColor(R.color.teal_700));


        this.addSection(panicSection);
        this.addSection(circleSection); /// for this section the notifications are seen
        this.addBottomSection(settingsSection);
        allowArrowAnimation();
        addMultiPaneSupport();
    }

**Comment by vedhavyas** [comment]
any update on this ?

Thanks

**Comment by neokree** [comment]
I tried your code but I cannot reproduce the bug, notifications is shown as 99+ on my device.

**Comment by vedhavyas** [comment]
damn :(

**Comment by neokree** [comment]
maybe you should try to debug your app using the dev version of this library, so you can see the library code and find the problem

**Comment by vedhavyas** [comment]
yes will definitely try

**Comment by vedhavyas** [comment]
I can see them, but notification text color is white.
how to change it ?

**Comment by vedhavyas** [comment]
From the layout i see that u have not mentioned text color in particular, maybe that is y the text color is white.

**Comment by neokree** [comment]
are you using the MaterialNavigationTheme.Light?

**Comment by vedhavyas** [comment]
im using MaterialNavigationDrawerTheme.TranslucentKitKatStatusBar

**Comment by neokree** [comment]
Well, in the old version there isn't a real dark theme. 
with the 1.3 alpha avariable on github I have created a dark theme and the notifications color should be ok.

**Comment by vedhavyas** [comment]
its working
