### ISSUE TITLE
Caligraphy NoSuchMethodError

### ISSUE THREAD

**Issue by mseroczynski** [neokree/MaterialNavigationDrawer#107]
Hey there,

I'm getting error as below. I am also using Caligraphy-2.0.0-SNAPSHOT version (which is configured correctly). Could you please tell me how to make MaterialNavigationDrawer use other (older) version of Caligraphy?

java.lang.NoSuchMethodError: uk.co.chrisjenx.calligraphy.CalligraphyConfig.initDefault
            at it.neokree.materialnavigationdrawer.MaterialNavigationDrawer.onCreate(MaterialNavigationDrawer.java:187)

**Comment by neokree** [comment]
please refer to the main issue #93
