### ISSUE TITLE
Actionbar not allowed/viewable in an activity section?

### ISSUE THREAD

**Issue by emcenrue** [neokree/MaterialNavigationDrawer#108]
I'm wondering if there is a way to get/show the actionbar of an activity section. I have a fragment that shows media, which works perfectly with the design of this lib. However, I also have an activity with tabs, each of which has unique "add new item" actionbar items/buttons. By using this library, the actionbar is removed from the activity section tabs. If somehow I could show that actionbar, this library would be perfect. 

PS I can't chop up the activity, because the tabs are an important part of the UI.

Thank you for these libraries! They look beautiful!

**Comment by neokree** [comment]
You have added the custom Theme for this library to all your activity, check your Manifest file and move the <code>android:theme="MyCustomTheme"</code> to the <code>activity</code> tag.

**Comment by neokree** [comment]
@emcenrue have you solved your problem?
