### ISSUE TITLE
Can't swipe to open drawer if fragment below is clickable or scrollable

### ISSUE THREAD

**Issue by guilhermearaujo** [neokree/MaterialNavigationDrawer#109]
This bug I am able to reproduce using the sample app, using the "Example with custom drawer Header" and selecting "Last Section" (because it will show a big button).

After a few opens & closes of the drawer, the swipe gesture seems to stop working, and if I open the drawer (using the burger button) and click outside the drawer (in an attempt to close it), the drawer will not be closed, and the button behind it will be clicked. Swiping to open doesn't work either.

Update: I just noticed something even worse: if the fragment has a horizontal scroll view, as soon as you scroll it for the first time, you won't be able to swipe to open the drawer.

**Comment by guilhermearaujo** [comment]
Looks like something described on issue #85.

**Comment by neokree** [comment]
please refer to the main issue instead open new issue, thank you
