### ISSUE TITLE
How to change toolbar icon (hamburger) color?

### ISSUE THREAD

**Issue by pawelantczak** [neokree/MaterialNavigationDrawer#110]
Hello.
Is it possible to change hamburger icon color?
Thanks.

**Comment by javmarina** [comment]
Why would you want to do that? It doesn't follow Material Design guidelines

**Comment by Hondrus** [comment]
2javmarina. However, Youtube app has a black hamburger.

**Comment by pawelantczak** [comment]
I want to have it white. This is the recommended color, right?

**Comment by javmarina** [comment]
Sorry guys, I thought you wanted to change the icon itself, the "shape". I think its not customizable with last AppCompat version (which this library uses) but we might be able to change the color.

**Comment by neokree** [comment]
check this [link](http://stackoverflow.com/questions/27861102/actionbardrawertoggle-v7-arrow-color)
That should work

**Comment by pawelantczak** [comment]
Thanks a lot!

**Comment by HanderWei** [comment]
@pawelantczak Did you fixed it?
