### ISSUE TITLE
Can't add pre-rendered icons

### ISSUE THREAD

**Issue by guilhermearaujo** [neokree/MaterialNavigationDrawer#111]
When we add an icon to a section, the image will be converted to a gray surface.
I wish I could add regular colored images as icon too (not as default, but as an additional option), just like the YouTube app's Subscription section.

**Comment by angelmartz** [comment]
Waiting too thankyou

**Comment by angelmartz** [comment]
I found this method but didnt work .useRealColor()

**Comment by neokree** [comment]
<code>useRealColor</code> works, but only if you set it before set the icon, because in the <code>setIcon</code> method I render the color over the icon.

**Comment by neokree** [comment]
1.3.1 released, I have created the <code>newSectionWithRealColor</code> methods for create this type of sections.
