### ISSUE TITLE
How to edit/remove sections after init()?

### ISSUE THREAD

**Issue by guilhermearaujo** [neokree/MaterialNavigationDrawer#112]
I'd like to add a Login section to my drawer, and remove it once the user has logged in.
I couldn't find any method like `removeSection()` to do that.

Another option would be to clean the whole thing and re-add all the sections again (without the Login this time). Is it possible to do as of 1.2.9?

**Comment by neokree** [comment]
no, with 1.2.9 is not possible change programmatically the section list. 
This feature will be avariable soon, but for now is not possible.

**Comment by y2kshane** [comment]
+1

**Comment by pepibumur** [comment]
It would be great to have it @neokree . Can I help you with it?

**Comment by Nivl** [comment]
+1

**Comment by neokree** [comment]
In the dev project on github is avariable. 
For documentation please wait until the next release. 
in short you can use the `removeSection` method for removing the section that you want.
