### ISSUE TITLE
Visual issue

### ISSUE THREAD

**Issue by grojasv** [neokree/MaterialNavigationDrawer#113]
Greetings,

I've got an iusse running the example app, username account overlaps photo account. Device used and screenshot attached.

Device: GT-I8190
Android version: 4.1.2

![screenshot_2015-01-15-11-46-03](https://cloud.githubusercontent.com/assets/4202945/5756238/8677e6ae-9cad-11e4-9cfa-a0e052152211.png)

**Comment by neokree** [comment]
how many inches has your device?

**Comment by neokree** [comment]
however this is a problem with the 1.2.9 version of this library. 
Into the dev project it is fixed.

**Comment by grojasv** [comment]
Thanks.
