### ISSUE TITLE
How to let other Activitys obtain the styles like MaterialNavigationDrawer

### ISSUE THREAD

**Issue by w821881341** [neokree/MaterialNavigationDrawer#114]
In my Apps,I have used this project to make MainActivity to have the MaterialNavigationDrawer,but other Activitys that don't need NavigationDrawer can't extends this,So How I get the styles in them?

**Comment by neokree** [comment]
Well,first you should read [this](http://developer.android.com/guide/topics/ui/themes.html).
you can have multiple custom theme in your styles.xml, so you could simple use another theme for all your others activities. I suggest you to use a <code>Theme.Appcompat</code> theme and set 
```xml
colorPrimary
colorPrimaryDark
colorAccent
```
to the same value, but then you should use your customizations.

**Comment by w821881341** [comment]
thanks
