### ISSUE TITLE
Change color of the notification number

### ISSUE THREAD

**Issue by treylon** [neokree/MaterialNavigationDrawer#115]
Hey,

I was wondering if there is a way to change the color of the notification number. In my app the notification number is almost unreadable due to its color, as you can see on the attached image. 

![drawer-notificaitons](https://cloud.githubusercontent.com/assets/10380579/5774629/2adee586-9d70-11e4-995e-c82097e46b27.png)

**Comment by neokree** [comment]
Well, actually I'm working to add the Dark Theme to the Drawer, because If you see your drawer use the Light theme, but you are using MaterialNavigationDrawer theme, that should be dark. 
See the main issue #76

**Comment by treylon** [comment]
Ohhh I see, thank you very much!

**Comment by ArsalBhutta** [comment]
How do you manage to draw lines on top and bottom of "konversation" ?
