### ISSUE TITLE
How to set the width of NavigationDrawer?

### ISSUE THREAD

**Issue by w821881341** [neokree/MaterialNavigationDrawer#116]
I can't find the place to set the width of NavigationDrawer.
In addition, How to  customize the layout of section?

**Comment by javmarina** [comment]
I think it's not necessary. It would not follow material design and maybe difficult to implement. The developer will focus on more important features and bug fixes, I think

**Comment by neokree** [comment]
I followed the material design guidelines for the drawer width, if you think it is not true, please tell me what problem there is. But I agree with the @javmarina post.

**Comment by w821881341** [comment]
I also agree with that there are more important features need to be better.  from a technical standpoint ，Changing the width of drawer is not important，but But from the point of view of design and framework ，design should be    multiple ，not all following the material design book , Framework needs to always have flexible features to adapt to the changing of apps。
 After all，one million apps based on the material design have one million kinds of material design
This is just personal opinion ，I just want to find the way to change width of drawer to meet the demand of my project～thanks

**Comment by neokree** [comment]
Well sure, there are millions of apps that use a navigation drawer and they not follows the material design guidelines, but this library is born for create easily a navigation drawer that follows these guidelines. 
However, if you want to use this library and not follow the material design guidelines, simply download the dev project, go to the <code>Utils.class</code> and change the <code>getDrawerWidth()</code> method.
