### ISSUE TITLE
Saving fragment view state

### ISSUE THREAD

**Issue by imanolmi** [neokree/MaterialNavigationDrawer#118]
I have a MaterialNavigationDrawer that switches between several fragments. 
When I navigate into a different fragment and come back to the first one, it loads again from the beginning, instead of showing the last view state. 
I would normally save its state using a variable in the calling activity with the following solution, but how can I do it with MaterialNavigationDrawer?

 MyFragment fragment;
    if (savedInstanceState != null) {
        fragment = (MyFragment) getFragmentManager().findFragmentByTag("my_fragment_tag");
    } else {
        fragment = new MyFragment();
        fragment.setArguments(getIntent().getExtras());
        getFragmentManager().beginTransaction().add(android.R.id.content, fragment, "my_fragment_tag").commit(); 
    }

Cheers!

**Comment by SwiTool** [comment]
Same question, but I simply need the id of the fragment container they are adding on the fly in the code...
