### ISSUE TITLE
Sections are not clickable if drawer is not closed properly

### ISSUE THREAD

**Issue by egor-n** [neokree/MaterialNavigationDrawer#120]
See [video](https://www.youtube.com/watch?v=4P7kwwIdr8Q).

It seems that sections get disabled when you click one, and don't get enabled if I manage to "catch" the drawer and not close it.

Is it related to #59 in some way?

**Comment by neokree** [comment]
Yes, it is related to 59 issue because it should be an implementation for fixing that problem. 
Essentially, When a section is clicked, all sections and all header listener is locked to prevent multiple clicks.

**Comment by Mrjerruss** [comment]
How fix it?

**Comment by neokree** [comment]
There are no fix for now. 
Actually I have used a boolean value to block all clicks, but I think there is an event life problem and this bug persists. 
I will test and try to find a solution

**Comment by neokree** [comment]
Well the main problem with this bug is this: there is not a drawer close cancel event to use. So I need to implements it on my own. 
I cannot remove the click lock for the drawer because I use it for preventing multiple clicks on drawer closing.

**Comment by neokree** [comment]
Check the new dev project. I have changed the ripple library and this one works much better than the old.
