### ISSUE TITLE
Prevent drawer overlaying Toolbar

### ISSUE THREAD

**Issue by logineimer** [neokree/MaterialNavigationDrawer#122]
Hello!

Is it possible to prevent the drawer from overlaying my ActionBar/Toolbar?

Thanks!

**Comment by neokree** [comment]
Well, no. Actionbar is created from the library and you should use the library toolbar. 
you can get it with <code>getToolbar();</code>

**Comment by logineimer** [comment]
Yeah, i know...but is there an option to place the drawer below the toolbar like the one in the screenshot?

![drawer](https://cloud.githubusercontent.com/assets/3143217/5792489/5c74daf0-9f1a-11e4-9d73-da8ae4ff3562.png)

**Comment by neokree** [comment]
That not follow the material design guidelines and that is not used there. 
You should see my other library: [GoogleNavigationDrawer](https://github.com/neokree/GoogleNavigationDrawer)

**Comment by logineimer** [comment]
Ok. I'll try! Thanks. Is the GoogleNavigationDrawer library up-to-date or abandoned?

**Comment by neokree** [comment]
Is not abandoned, but it is based on an old version of this library. I'm concentrating on this library first because all google apps are changing to this type of layout, so that layout seems to be deprecated.

**Comment by logineimer** [comment]
OK. It's a pity that the new lib doesn't support an alternative layout. Maybe you could implement in a future release. Thanks for your support, sir.

**Comment by yoavst** [comment]
@logineimer see my suggestion on #144. You can change the layout file to support it. Though you will probably have to fix all 5.0 code.

**Comment by logineimer** [comment]
Thank you very much. I will try!
