### ISSUE TITLE
Section labels get wrapped on galaxy note 4

### ISSUE THREAD

**Issue by Swisyn** [neokree/MaterialNavigationDrawer#123]
I got a weird feedback from one of my users that says on drawer section labels textview wrapping words.

Normally drawers' like; https://lh5.ggpht.com/WzhVtRiQ-3Eb0ynkkn5pObMxX9Q3ECdPaFIkVL5E7riWBBru0KX1pWFj4dg3ZtEUzQ=h900-rw

on galaxy note 4;  http://oi58.tinypic.com/2vluzvs.jpg

Is there a solution to fix that issue?

**Comment by neokree** [comment]
related to #90
