### ISSUE TITLE
Navigation Drawer with Google maps fragment

### ISSUE THREAD

**Issue by HTAD** [neokree/MaterialNavigationDrawer#124]
Hello,

I have an app in non-material navigation drawer. This is an Maps type app. Now I want to integrate it with MaterialNavigationDrawer. 

The main activity (activity_map.xml) 
```java
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
          xmlns:ads="http://schemas.android.com/apk/res-auto"
          android:id="@+id/main_layout"
          android:orientation="vertical" 
          android:layout_width="match_parent"
          android:layout_height="match_parent">
          
    <fragment 
             android:name="com.google.android.gms.maps.MapFragment"
             android:id="@+id/map"
             android:layout_width="fill_parent"
             android:layout_height="0dp"
             android:layout_weight="1.0"
          />

</LinearLayout>
```
In MND wiki, there is a note that say the first section have to Fragment type. I don't know how to configure the activity_map above as a fragment for first section in MND ? Please give me some instructions.

Thanks !

**Comment by javmarina** [comment]
Activity_map (your main activity)  contains some fragments, which are represented as sections (or items) in the navigation drawer. It means your default section (the section that is selected when the app starts) must be a fragment. In your case, create a MapFrament with layout:

<fragment 
         android:name="com.google.android.gms.maps.MapFragment"
         android:id="@+id/map"
         android:layout_width="fill_parent"
         android:layout_height="0dp"
         android:layout_weight="1.0"
      />

**Comment by HTAD** [comment]
The code is encoded, please capture screen or copy it to pastebin. Thanks !

The ss below is the fragment_map.xml I am using in project

![screen shot 2015-01-18 at 20 40 57](https://cloud.githubusercontent.com/assets/4926488/5792587/5e24ac12-9f52-11e4-980a-f7048746d220.png)

**Comment by neokree** [comment]
I have modified the first comment for showing all code.

**Comment by javmarina** [comment]
Your map fragment's layout must be what you have inside the fragment tag

**Comment by HTAD** [comment]
There is a lot of functions (loadMap, loadMaker, InfoWindowClick,...) in the MapActivity.java. I don't know where to put these functions in the new file (MapFragment.java)

**Comment by javmarina** [comment]
You have one activity (MainActivity) which extends from MaterialNavigationDrawer. There you add your drawer sections.
Your main fragment (inside the activity) is MapFragment, where you add all that methods.
However, if you're going to use just one section (one fragment) you should not use this library at all.

**Comment by HTAD** [comment]
Are there any Navigation Drawers that are support activity instead of the fragment ?

**Comment by javmarina** [comment]
I don't know what you mean.
Please read the library documentation and Android Developers resources, specially regarding fragments and navigation drawers.

**Comment by HTAD** [comment]
May I contact you via email to ask for help? I will send you a project with activity that need to transfer all codes to a fragment however I don't know how to do that.

Sorry for the inconvenience.

**Comment by javmarina** [comment]
I dont think I can help you. I don't have enough time and I'm not an expert at all...

**Comment by neokree** [comment]
@HTAD I think that you should move your <code>fragment</code> xml inside another fragment, because in this library you cannot set the xml code for fragments. 
So create a Fragment, inflate your map layout in there and then use the fragment instead the activity.
