### ISSUE TITLE
Show back button instead of drawer

### ISSUE THREAD

**Issue by treylon** [neokree/MaterialNavigationDrawer#125]
Hey guys,

I was wondering if there is way to show a custom icon instead of the drawer icon and bind a custom event to it? 
I am using a ViewPager in one of the fragments and i would like to show a back button on pages >0 to allow he user to easily navigate back inside the viewpager.
My current approach was to set the drawer icon using getToolbar() and then add a custom onclick event, but I did not find a proper way to get the drawer behaviour back after that.
Any suggestions?

**Comment by neokree** [comment]
Actually is not avariable any type of method for this implementation. 
But I think it's easy to resolve, so I will create it for 1.3 official release.
Stay tuned to the alpha ;)

**Comment by drinfernoo** [comment]
Access to the DrawerLayout would be sufficient, since we could then pass in any DrawerListener, including those from other libraries like android-ui or the like.

**Comment by neokree** [comment]
@drinfernoo Yes, but the library use an internal drawer listener. If you set another listener, library listener will be overrided. 
However, you can set the drawer listener to the library using this method:
```java
public void setDrawerListener(DrawerLayout.DrawerListener listener)
```

**Comment by wrik** [comment]
awesome library @neokree! @treylon did you manage to implement this function in your project?

I have an issue whereby if the user enters a nested fragment and then uses the navigation drawer to change sections followed by pressing the hardware back button the user gets a fragment pile-up.

This could easily be resolved if I changed the nav drawer button to a back button when entering a nested fragment. I have tried to figure out how to do this myself but have had no luck.

Image of pile-up: http://s24.postimg.org/rawq10x77/pileup.jpg

**Comment by treylon** [comment]
Not really @wrik. Sorry.

**Comment by wrik** [comment]
Hey @treylon, I managed to get this working.. Not sure if this is the correct implementation, but it works none the less :+1: 

Parent
Instead of using Fragment Transaction use setFragmentChild..
```java
Fragment childFragment = new MyChildFragment();
                childFragment.setArguments(bundle);
((MainActivity)mContext).setFragmentChild(childFragment, "My Child Fragment");
```

Child
```java
 actionBar = ((ActionBarActivity) getActivity()).getSupportActionBar();
actionBar.setDisplayHomeAsUpEnabled(true);
actionBar.setHomeAsUpIndicator(((MainActivity)mActivity).getV7DrawerToggleDelegate().getThemeUpIndicator());
```
