### ISSUE TITLE
MaterialAccount Constructor & sample 

### ISSUE THREAD

**Issue by bsElyes** [neokree/MaterialNavigationDrawer#126]
```java
   // add first account
        account = new MaterialAccount("NeoKree","neokree@gmail.com",getResources().getDrawable(R.drawable.photo),this.getResources().getDrawable(R.drawable.bamboo));
        this.addAccount(account);

        MaterialAccount account2 = new MaterialAccount("Hatsune Miky","hatsune.miku@example.com",getResources().getDrawable(R.drawable.photo2),this.getResources().getDrawable(R.drawable.mat2));
        this.addAccount(account2);

        MaterialAccount account3 = new MaterialAccount("Example","example@example.com",getResources().getDrawable(R.drawable.photo),this.getResources().getDrawable(R.drawable.mat3));
        this.addAccount(account3);
```

that was the sample but i got error

Error:(25, 19) error: no suitable constructor found for MaterialAccount(String,String,Drawable,Drawable)
constructor MaterialAccount.MaterialAccount(Resources,String,String,Bitmap,Bitmap) is not applicable
(actual and formal argument lists differ in length)
constructor MaterialAccount.MaterialAccount(Resources,String,String,Bitmap,int) is not applicable
(actual and formal argument lists differ in length)
constructor MaterialAccount.MaterialAccount(Resources,String,String,int,int) is not applicable
(actual and formal argument lists differ in length)
constructor MaterialAccount.MaterialAccount(Resources,String,String,int,Bitmap) is not applicable
(actual and formal argument lists differ in length)

**Comment by treylon** [comment]
Since the last release you have to pass your resources as the first parameter when creating a user. It should look something like this: 

<p>
<pre>
<code>
account = new MaterialAccount(<b>getResources()</b>, "NeoKree","neokree@gmail.com",getResources().getDrawable(R.drawable.photo),this.getResources().getDrawable(R.drawable.bamboo));
</code>
</pre>
</p>

**Comment by philbring** [comment]
You need something of

MaterialAccount account2 = new MaterialAccount(getResources(), "Hatsune Miky","hatsune.miku@example.com",R.drawable.photo2,R.drawable.mat2);
    this.addAccount(account2);

Api changed in library

**Comment by neokree** [comment]
@treylon is right. 
If you use the module downloaded by github you are using the 1.3 alpha version. That have multiple bug fix and changes from the 1.2.9 version, but it is still in testing.

**Comment by Mrjerruss** [comment]
When will the correction issue #85? I do not hurry, just wondering.

**Comment by neokree** [comment]
Actually I haven't tested if the fix works

**Comment by neokree** [comment]
@Mrjerruss the fix works!

**Comment by Ne1c** [comment]
Very lags closing drawer if my fragment had many data. How I can run closing drawer, after load data of my fragment?

**Comment by neokree** [comment]
@Ne1c please open a new issue for this problem
