### ISSUE TITLE
Clicking behavior in NavigationDrawer

### ISSUE THREAD

**Issue by sdeff** [neokree/MaterialNavigationDrawer#129]
If I compare it to e.g. the Google Mail app I see 2 differences:

1. Click sound after selecting an item.
2. Ripple effect starts as soon as you begin to touch an item (even if you don't lift your finger).

I think this should be the best practice since all Google apps are doing it this way?

**Comment by neokree** [comment]
check the newest version, problems should be resolved with the new ripple library.

**Comment by sdeff** [comment]
Thanks for letting me know!

The ripple effect is there but I think the background color of the menu item should get darker as soon as you touch it. (You can see the difference if you touch and hold down on a menu item in the Google Mail app compared to the example app).

Also I noticed that the drawer does not close instantly after you selected an item instead it seems that it waits until the "ripple effect" is done?!

**Comment by neokree** [comment]
Yes, is default in Lollipop, and it is the default there. 
I created an example that do the call to the onclick when you tap on the button. 
[sample](https://raw.github.com/neokree/MaterialNavigationDrawer/blob/master/test-click-before.apk)
