### ISSUE TITLE
Conflict with SlidingTabLayout and ViewPager

### ISSUE THREAD

**Issue by Hondrus** [neokree/MaterialNavigationDrawer#130]
Hey!
Sorry for my bad english! Sorry, if this question does not refer to this library.
I added a ViewPager with Tabs like in this tutorial http://habrahabr.ru/post/236567/ (tabs create begins after "Внедрение вкладок")
It use SlidingTabLayout, SlidingTabStrip and ViewPager.
I have conflict after adding ViewPager - Navigation Drawer doesn't open with swipe after I swipe tabs! However, it works if I don't touch viewpager area.
So, guys, how I can resolve this problem?
![screenshot_2015-01-25-00-20-20](https://cloud.githubusercontent.com/assets/3332036/5888440/08ecd09a-a429-11e4-85df-cd08747a3b1f.png)

**Comment by Hondrus** [comment]
If somebody known other ways to add tabs into app, please, send here or to my e-mail: hondrus@gmail.com

**Comment by SwiTool** [comment]
I've got the same issue.

**Comment by neokree** [comment]
what library version are you using? this is a bug with the 1.2.9 version.
I have fixed with the 1.3, you can check it in the changelog

**Comment by SwiTool** [comment]
Yes, fixed.
Great :)
thanks
