### ISSUE TITLE
Initial section coloring not working

### ISSUE THREAD

**Issue by drinfernoo** [neokree/MaterialNavigationDrawer#131]
I'm not really sure how to replicate it, but sometimes the toolbar color doesn't get set correctly on the first section that gets opened. For example, my first section should be red, but it's blue until I actually leave and return to it.

**Comment by neokree** [comment]
for "return" you mean clicking into the first section or click the back button and using the BACK_TO_FIRST pattern?

**Comment by drinfernoo** [comment]
Clicking back into the first section. Either just clicking it again, or leaving the section and coming back to it. It alsonworks with BACK_TO_FIRST.

**Comment by neokree** [comment]
@drinfernoo Check with the last dev version on github if this problem is resolved. I have done a patch
