### ISSUE TITLE
is drawer open/closed

### ISSUE THREAD

**Issue by pawelantczak** [neokree/MaterialNavigationDrawer#134]
Hello.
It can be useful to know if drawer is currently open or closed.
You could expose such methods or whole drawer.
Thanks.

**Comment by javmarina** [comment]
There are methods available. See https://developer.android.com/reference/android/view/MotionEvent.html

**Comment by javmarina** [comment]
Sorry, I made a mistake. The correct link is https://developer.android.com/reference/android/support/v4/widget/DrawerLayout.html

**Comment by pawelantczak** [comment]
Yes, they are. 
My point was, that since ```MaterialNavigationDrawer``` class already have drawer in hand, it can give us access to its methods.

**Comment by neokree** [comment]
Well, I can create a method like "isDrawerOpen" into the activity class for getting work.

**Comment by neokree** [comment]
I have released the 1.3.2 version
