### ISSUE TITLE
How to transfer data between two sections?

### ISSUE THREAD

**Issue by David996** [neokree/MaterialNavigationDrawer#135]
how can i get some section? 
i'd like to click this fragment ,and  then go to another section with some data.

Thanks!

**Comment by h0aX14** [comment]
Hello, 

By using Bundle  http://developer.android.com/reference/android/os/Bundle.html

**Comment by David996** [comment]
I mean, how to jump from one section to another section . For example, one section is to show all the fruit, and another section shows all the categories, click on a category will jump to the previous section which display the Fruits belonging to this category

**Comment by h0aX14** [comment]
getActivity().getSupportFragmentManager().beginTransaction().replace(R.id.frame_container, fragmentName, "tag").commit();

**Comment by neokree** [comment]
Having a section, you can set a bundle with your datas so:
```java
Fragment fragment = new MyCustomFragment();
Bundle data = new Bundle();

// adding data to the bundle
data.putString("Test","Banana");

fragment.setArguments(data);
((MaterialNavigationDrawer)this.getActivity()).setFragmentChild(fragment,"Test page 2");
// ((MaterialNavigationDrawer)this.getActivity()).setFragment(fragment,"Test page 2");
```
Now you have to retrive your data in the child fragment
```java
public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
    Bundle data = this.getArguments();
}
```

I'm creating the page documentation right now
