### ISSUE TITLE
Overlap Botton Section

### ISSUE THREAD

**Issue by angelmartz** [neokree/MaterialNavigationDrawer#137]
Hello, nice great library

Just one bug, when expand/collapse User Profile arrow on Drawer, Botton Section with last section get overlap

**Comment by neokree** [comment]
Sorry but I don't get the bug, what do you mean for botom section with last section get overlap?

**Comment by angelmartz** [comment]
![screenshot_2015-02-04-21-38-44](https://cloud.githubusercontent.com/assets/2517199/6054784/bdb7b044-acb7-11e4-997f-bc46f33410c5.png)

**Comment by neokree** [comment]
Which version are you using? 1.3 dev or 1.3 official?

**Comment by angelmartz** [comment]
compile 'it.neokree:MaterialNavigationDrawer:1.3'

**Comment by neokree** [comment]
With version 1.3 there is a bug, in my layout I removed a view, but I forgot to link the main section list to the start of bottom list. This probably cause this issue. Please check if with the dev version this problem persists

**Comment by neokree** [comment]
With the new version the bug persists?

**Comment by angelmartz** [comment]
Thank you; I will try

**Comment by angelmartz** [comment]
Fixed!!! thank you
