### ISSUE TITLE
How to hide Section (Fragment) if there is only one item?

### ISSUE THREAD

**Issue by anticafe** [neokree/MaterialNavigationDrawer#142]
Sometimes my app have only 1 Section with Target is Fragment, and the rest have Target is Intent. For example:
>Drawer Header
Section
Setting
About app
Share this app

Therefore, I don't think this Section should be visible. Is there any way to hide it?

**Comment by neokree** [comment]
Actually no. I'm working for adding section customizations like adding/removing section, but for now section list is static.
