### ISSUE TITLE
AsyncTasks in MaterialAccount should not be instanciated at class initialization

### ISSUE THREAD

**Issue by mlumeau** [neokree/MaterialNavigationDrawer#143]
When manipulating a MaterialAccount, it can happen that setPhoto() is called twice in a short timespan. In that case, an IllegalStateException is thrown, because you cannot execute the same instance of an AsyncTask while it is already executing.

A workaround would be to define AsyncTask inner classes of MaterialAccount (ResizePhotoBitmapAsyncTask, ResizeBackgroundBitmapAsyncTask...) and define setPhotoBitmap, setBackgroundBitmap, etc... as the following: 
```java
public void setPhoto(Bitmap photo) {
    new ResizePhotoBitmapAsyncTask().execute(photo);
} `

**Comment by neokree** [comment]
I followed your suggestion and committed now a little fix, please check if now the problem is resolved.

**Comment by mlumeau** [comment]
That did it. Everything runs perfectly with your fix.
Thanks.
