### ISSUE TITLE
Access Activity Layout

### ISSUE THREAD

**Issue by RubyDerBoss** [neokree/MaterialNavigationDrawer#144]
Hi, awesome Library.
I want to display Ads in my App, but i want to declare the view in the Activity layout so i don't have to do that for each fragment i have. Is there a way to do that?

**Comment by neokree** [comment]
Sure, but you need to add this library as a module and modify the main layout manually.

**Comment by RubyDerBoss** [comment]
Yes, but than i have to manually import the library every time an update is pushed? Could there propably an more easy way in a future release? Than i would wait for it.

**Comment by yoavst** [comment]
you can override the resource...

**Comment by RubyDerBoss** [comment]
Hi, thank you for the hint. Could you give me some example how to do that?

**Comment by yoavst** [comment]
Here is a general guide how to override any layout file for any library
1. Check for layout name. In this library you can find it [here](https://github.com/neokree/MaterialNavigationDrawer/tree/master/MaterialNavigationDrawerModule/src/main/res/layout)
2. In your resources, create a layout file with the same name as the selected file (you would probably want overriding `activity_material_navigation_drawer.xml` or `activity_material_navigation_drawer_customheader.xml`
3. Copy the content of the original layout file to your layout file
4. Modify it. 

**Note 1:** if you change Id or view type it could break the library (just adding adview somewhere shouldn't break it

**Note 2:** If the layout exists in default configurations (not in this case), you better override them too.

**Comment by RubyDerBoss** [comment]
Okay great, thank you! Your help is very appreciated!
