### ISSUE TITLE
Bug - Section Not Highlighted

### ISSUE THREAD

**Issue by TurKurT656** [neokree/MaterialNavigationDrawer#147]
in the sample app:
for example:
1- select Light - Accounts
2- open navigation drawer
3- select section 3
4- open navigation drawer (you can see that section 3 is highlighted with a purple color)
5- now select bottom Section
6- touch on back button
7- open navigation drawer

now you can see that section three is selected but not highlighted with purple color

**Comment by javmarina** [comment]
Its working as expected

**Comment by javmarina** [comment]
Sorry I didn't understand well, it's a bug

**Comment by gvsharma** [comment]
Let me check it.....I have implemented this in one of my application..

**Comment by neokree** [comment]
Well, no the section three is not selected because you have opened a section with intent as target.

**Comment by javmarina** [comment]
Yes, but when you close the second activity you return to section three, so it should be highlighted

**Comment by neokree** [comment]
Now the section is Highlighted when you return back from an activity
