### ISSUE TITLE
FragmentList shows a spinner instead of a list

### ISSUE THREAD

**Issue by mrcasals** [neokree/MaterialNavigationDrawer#148]
Hi! 

Android noob here. I've downloaded the project and tested the example app, but when I try to use the `FragmentList` fragment in one of the sections it shows a spinner and no list. What should I do to see the list?

**Comment by egor-n** [comment]
Not related to the library. To show the list you have yo use `setAdapter` inside your `ListFragment`.

**Comment by mrcasals** [comment]
Not related to the library, but related to the example bundled with the repo (which are not working as expected)

**Comment by mrcasals** [comment]
Anyway, thanks for the reply, I'll check if I can make it work.
