### ISSUE TITLE
How to set section title color??? No api for this

### ISSUE THREAD

**Issue by niketkadde** [neokree/MaterialNavigationDrawer#150]
If I want to change color of text of the section in drawer list, how to do that, I do not see any api for that.
It will be great if you provide apis like getView() getTitleTextView, getNotificationTextView() or simple setTitleTextColor() etc etc.

**Comment by neokree** [comment]
If you want to set all sections colors you can customize your drawer, check the [Theming page](https://github.com/neokree/MaterialNavigationDrawer/wiki/Theming#advanced-theming)
You can also add a section color, that allows you to set the color of the section when it is selected.

**Comment by niketkadde** [comment]
Hey thank you for the quick reply,

Yes I know that, what if I want same section color  but different section title color. For doing this I did 
View view = materialSectionActions.getView();
        TextView textView = (TextView) view.findViewById(R.id.section_text);
        if (textView != null) {
            textView.setTextColor(getResources().getColor(R.color.font_gray_dark));
        }

something like this... now if you check above code, I needed to mention "R.id.section_text" which is there in your library.

One more thing, when I click on empty space in drawer below the top sections, the view behind it (views inside fragment) gets clicked. So how to handle this?

**Comment by neokree** [comment]
@niketkadde for programmatical methods please wait for the next release. 
The other bug you have found there is an opened issue -> #146

**Comment by niketkadde** [comment]
Okay thanks for that. :+1:

**Comment by neokree** [comment]
1.3.1 released
you can use this method: <code>setUsernameTextColor</code> for the username (first line)
and <code>setUserEmailTextColor</code> for the second line
