### ISSUE TITLE
Sections not clicable

### ISSUE THREAD

**Issue by pawelantczak** [neokree/MaterialNavigationDrawer#151]
Hello.
From time to time, when I open drawer, I can't click any section. Touch is not working.
I have to close drawer and reopen, after that, touch is working correctly.
When I will figure out in what circumstances it's happening, I will give more info.

**Comment by tankilo** [comment]
I also met this problem,If you click the item and perform next click very fast before the drawer automatically close.Then the click doesn't work anymore except you close and reopen the drawer.

**Comment by tankilo** [comment]
I also met this problem,If you click the item and touch the drawer very fast to prevent it from automatically closing.Then the click doesn't work anymore except you close and reopen the drawer.

**Comment by tankilo** [comment]
The problem has been talked about in Issue #120.It's a bug.

**Comment by pawelantczak** [comment]
#120
