### ISSUE TITLE
Laggy drawer close animation

### ISSUE THREAD

**Issue by pawelantczak** [neokree/MaterialNavigationDrawer#152]
Hello.
When I'm opening more complex fragments, drawer close animation is a bit laggy.
It's not fluent, it is animating for a while, then stop and disappears.

**Comment by neokree** [comment]
Well, this is not a library bug, The drawer should be laggy at any case, try using the navigation drawer sample instead of this library.

**Comment by yoavst** [comment]
[Here](http://stackoverflow.com/questions/17491557/drawerlayouts-item-click-when-is-the-right-time-to-replace-fragment) you can find a solution. I'm using this in my app and it looks a lot better.

**Comment by neokree** [comment]
@yoavst Thank you, I'm working to add this into the library

**Comment by neokree** [comment]
Try to use the 1.3.1 version, I moved the setFragment call after the close of the drawer.

**Comment by pawelantczak** [comment]
Yes. It way better now. Thanks.
