### ISSUE TITLE
Request - 1.3 Final Version

### ISSUE THREAD

**Issue by TurKurT656** [neokree/MaterialNavigationDrawer#153]
hi,
when version 1.3 (final) will be release?
i saw that you fixed a lot of bugs but not yet implemented in the final version.
so im very happy and i want to use new version of this lib in my new app.
can u say that when we can use 1.3final version? 
thnx a loooooooooooooot Bro :+1:

**Comment by neokree** [comment]
The 1.3 is online. 
The 1.3.1 will be avariable soon, I'm working about fixing all problems and adding some customizable methods.

**Comment by TurKurT656** [comment]
thnx bro, u r awesome
just there is no guide for the new version.
can u add a guide?

**Comment by neokree** [comment]
Yes, I'm working for the complete guide.

**Comment by neokree** [comment]
Released the 1.3.1 with all fix
