### ISSUE TITLE
Statusbar color too dark

### ISSUE THREAD

**Issue by alexfacciorusso** [neokree/MaterialNavigationDrawer#154]
Hi!
Referencing to Material Design guidelines, I think the status bar color in Lollipop devices (so with transparency) is too dark. Can you confirm?

![comparison](https://cloud.githubusercontent.com/assets/4479527/6021708/083e65b4-abb8-11e4-94b0-f77d45d646be.jpg)

**Comment by PaoloRotolo** [comment]
I can confirm it too.

**Comment by PaoloRotolo** [comment]
Also, is there a way to remove automatic color for colorPrimaryDark and use the one in styles?

**Comment by neokree** [comment]
Well, I have used the primaryColorDark for the status bar imageView that is under the status bar. 
(this library uses the android:windowTranslucentStatus true for getting the drawer under the status bar).
Try to set the same color for colorPrimaryDark and colorPrimary (the lighter). Lollipop adds his dark opacity to the status bar color when the windowTraslucentStatus is setted to true.

**Comment by PaoloRotolo** [comment]
Thanks, colorPrimaryDark si now used if android:windowTranslucentStatus=false.

**Comment by PaoloRotolo** [comment]
UPDATE: nope... Even if android:windowTranslucentStatus=false, the app uses the primaryColor for the status bar, not the dark one.

**Comment by neokree** [comment]
Yes I know. You should modify the <code>changeToolbarColor(MaterialSection section)</code> method.
Actually it uses the primaryColor for Lollipop.
