### ISSUE TITLE
NavDrawer is below the status bar

### ISSUE THREAD

**Issue by PaoloRotolo** [neokree/MaterialNavigationDrawer#155]
I tried your example .apk, and this is what I have (I also tried MaterialNavigationDrawer on a my project):

![screenshot_2015-02-03-18-35-29](https://cloud.githubusercontent.com/assets/5623301/6025569/c64dd286-abd3-11e4-9d3d-3005d8262784.png)

As you can see, the status bar opacity is over the NavigationDrawer. I also saw a screenshot on your README without the bug:

![screenshot](https://camo.githubusercontent.com/12308f7914b9286b9b084f84e201636ca2537aa9/68747470733a2f2f7261772e6769746875622e636f6d2f6e656f6b7265652f4d6174657269616c4e617669676174696f6e4472617765722f6d61737465722f6172742f73637265656e312e6a7067)

Is there a way to disable opacity for the status bar (and maybe use colorPrimaryDark)?

P.S. Thanks for your work, MaterialNavigationDrawer is awesome!

**Comment by alexfacciorusso** [comment]
Paolo, this is not a bug: the screenshot has a bug ;)
Respecting the Material Design guidelines, the drawer must be **below** the darkening layer :)
http://www.google.com/design/spec/patterns/navigation-drawer.html

**Comment by PaoloRotolo** [comment]
@alexfacciorusso oh, thanks. Now I just need your opacity bug fixed :)

 I'm going to close the issue.
