### ISSUE TITLE
Any way to hide the expand/collapse option in the header?

### ISSUE THREAD

**Issue by CoericK** [neokree/MaterialNavigationDrawer#158]
Hello, as the tittle says there is any ways to hide that button (Arrow) that aallows show/hide  the options of the menu? Because the even the bottom section is hidden when i press it.

**Comment by pawelantczak** [comment]
Try this: https://github.com/neokree/MaterialNavigationDrawer/blob/master/MaterialNavigationDrawer/app/src/main/res/values/styles.xml#L51

**Comment by mrcasals** [comment]
Or this: https://github.com/neokree/MaterialNavigationDrawer/blob/master/MaterialNavigationDrawer/app/src/main/res/values/styles.xml#L66

**Comment by CoericK** [comment]
Thank you @pawelantczak that worked. Thank you @mrcasals for your answer, that will be usefull if i try to update the icon later on.
