### ISSUE TITLE
NullPointerException in onCreate

### ISSUE THREAD

**Issue by SqualalaTeam** [neokree/MaterialNavigationDrawer#160]
Hello, I got a NullPointerException after I return in activiity that extends MaterialNavigationDrawer

Caused by: java.lang.NullPointerException
            at it.neokree.materialnavigationdrawer.MaterialNavigationDrawer.onCreate(MaterialNavigationDrawer.java:678)
            at android.app.Activity.performCreate(Activity.java:5372)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2257)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2349)
            at android.app.ActivityThread.access$700(ActivityThread.java:159)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:176)
            at android.app.ActivityThread.main(ActivityThread.java:5419)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by angelmartz** [comment]
Hello

You dont should override OnCreate Method , use init() instead

https://github.com/neokree/MaterialNavigationDrawer/wiki/Set-Up-a-Navigation-Drawer-Activity

**Comment by SqualalaTeam** [comment]
Hi

I don't override onCreate, I use init, and I have this bug.

**Comment by SqualalaTeam** [comment]
Here is the problem

  // init account views
            if(accountManager.size() > 0) {
                currentAccount = accountManager.get(0);
                notifyAccountDataChanged();
            }

**Comment by angelmartz** [comment]
can you paste your Activity?

**Comment by SqualalaTeam** [comment]
I get this code in MaterialNavigationDrawer and not in my activity

**Comment by angelmartz** [comment]
I know but I think that you didnt initializate anything account

**Comment by SqualalaTeam** [comment]
My activity look like this example :

https://github.com/neokree/MaterialNavigationDrawer/blob/master/MaterialNavigationDrawer/app/src/main/java/it/neokree/example/light/CustomDrawerHeader.java

**Comment by neokree** [comment]
@SqualalaTeam could you share your theme?

**Comment by SqualalaTeam** [comment]
Here is my theme : 

 <style name="CustomHeaderLight" parent="MaterialNavigationDrawerTheme.Light.DarkActionBar">
        <item name="colorPrimary">#8bc34a</item>
        <item name="colorPrimaryDark">#558b2f</item>
        <item name="colorAccent">#FFFFFF</item>
        <item name="drawerType">@integer/DRAWERTYPE_CUSTOM</item>
        <item name="rippleBackport">true</item>
    </style>

But now I know exactly how to reproduce this bug, I open the activity that extends MaterialNavigationDrawer and I leave the activity for example to open others applications, and after a little moment when I return to my activity, I get the exception.

**Comment by neokree** [comment]
mmm... your theme config seems to be ok
It should be impossible have a nullpointer exception in line 678. 
<code>accountManager</code> is initialized in line 437, so it is not null. 
However, if you come back from another activity the <code>savedInstanceState</code> should not be null as it is.

**Comment by SqualalaTeam** [comment]
Yes, you have done accountManger is not the problem.

I use the library with Dagger like this :

public abstract class BaseActivity extends MaterialNavigationDrawer {

    private ObjectGraph activityGraph;

    @Override
    public void init(Bundle bundle) {

        if (getModules() != null) {
            activityGraph = ((MyApp) getApplication()).createScopedGraph(getModules().toArray());
            activityGraph.inject(this);
        }

    }

    /** Inject the supplied {@code object} using the activity-specific graph. */
    public void inject(Object object) {
        activityGraph.inject(object);
    }

    @Override
    protected void onDestroy() {
        activityGraph = null;
        super.onDestroy();
    }

    public void addModules(List<Object> list) {
        activityGraph = ((DjihtiApp) getApplication()).createScopedGraph(list.toArray());
    }


    protected abstract List<Object> getModules();

}


public class MyActivity extends BaseActivity {
	

	@Override
    public void init(Bundle savedInstanceState) {
    	super.init(savedInstanceState);


    	// create and set the header
        View view = LayoutInflater.from(this).inflate(R.layout.custom_drawer,null);
        setDrawerHeaderCustom(view);

        // create sections
        this.addSection(newSection("Section 1", new FragmentIndex()));
        this.addSection(newSection("Section 2",new FragmentIndex()));
        this.addSection(newSection("Section 3", R.drawable.ic_mic_white_24dp,new FragmentButton()).setSectionColor(Color.parseColor("#9c27b0")));
        this.addSection(newSection("Section",R.drawable.ic_hotel_grey600_24dp,new FragmentButton()).setSectionColor(Color.parseColor("#03a9f4")));

        // create bottom section
        this.addBottomSection(newSection("Bottom Section",R.drawable.ic_settings_black_24dp,new Intent(this,Settings.class)));

    }


	@Override
	protected List<Object> getModules() {
		return Arrays.<Object>asList(new MyModule(this));
	}





}

**Comment by SqualalaTeam** [comment]
After an investigation, it's my fault because I had override onSaveInstanceState method and didn't call  
"super.onSaveInstanceState(outState);"
I apologize for making you waste your time, and thank you sincerely for your help!
