### ISSUE TITLE
ResizePhotoBitmap and ResizeBackgroundBitmap break the specified bitmap

### ISSUE THREAD

**Issue by k-kagurazaka** [neokree/MaterialNavigationDrawer#163]
Hi.

In the MaterialAccount.java, ResizePhotoBitmap and ResizeBackgroundBitmap call params[0].recycle() for releasing a pre-resized bitmap.
I think it is not good because it causes a problem when the user uses the bitmap for several purposes like:

```java
mBitmap = BitmapFactory.decodeResource(res, resId, options);
account.setPhoto(mBitmap); // Change the photo of MaterialAccount

// After finishing ResizePhotoBitmap, mBitmap is recycled!!
```

**Comment by neokree** [comment]
So you suggest to create another bitmap equal than the first before starting the resize process?
Because the main problem is this: I used the same bitmap assuming that is only used for setting the user image photo. If it will cloned, this potentially cause a memory exception on low devices.

**Comment by k-kagurazaka** [comment]
I know that the solution by cloning the bitmap potentially causes the memory leak (OOM).
Even so, I think the library method should not affect arguments destructively.

There are three solutions for this problem:

1) Document that users must not share the bitmap for setPhoto and setBackground.

```java
// should copy if you want to use the shared bitmap
account.setPhoto(mBmp.copy(mBmp.getConfig(), true));
```

2) Simply delete the following line.

```java
params[0].recycle();
```

3) Clone the bitmap before resizing.

```java
Bitmap src = params[0].copy(params[0].getConfig(), true);
Bitmap photo = Utils.resizeBitmap(src,photoSize.x,photoSize.y);
src.recycle();
```

I recommend the No. 2 solution because I think the user (not library) resources should be managed in the user-side.

**Comment by k-kagurazaka** [comment]
Oops, the second solution has problem that the bitmap is recycled before resizing.
For safe, recycle() should be called in a listener of OnAccountDataLoaded.
