### ISSUE TITLE
Scroll on drawer scroll fragment list

### ISSUE THREAD

**Issue by mrcasals** [neokree/MaterialNavigationDrawer#166]
Hi!

When the drawer has few sections (not enough to be scrollable), and I try to scroll on it, it scrolls the background layout. Is this a bug, or is there a section to disable this behavior?

**Comment by neokree** [comment]
if you are using the 1.3 version, it is a bug that I have fixed in the dev version of this library avariable on github.

**Comment by mrcasals** [comment]
Nice, thanks!
