### ISSUE TITLE
Custom Header change height

### ISSUE THREAD

**Issue by pimato** [neokree/MaterialNavigationDrawer#167]
Hey, 

I already look into the wiki but I can't find the possibility to change my own customheader height.
Is there a way ?

thanks for the reply and taking time ! 

cheers pimato

**Comment by neokree** [comment]
There is not a way because the material guidelines tells that the header of the layout must be a 16:9 size. The library always calculate the correct height.

**Comment by pimato** [comment]
thank you for the answer and the nice library :)
