### ISSUE TITLE
setTarget(Fragment) results in no action when section is clicked

### ISSUE THREAD

**Issue by sciencepro** [neokree/MaterialNavigationDrawer#170]
I'm constructing a section as follows

````
MaterialSection newSection = new MaterialSection(this, MaterialSection.ICON_24DP, true, MaterialSection.TARGET_FRAGMENT);
newSection.setTitle("Title");
TestFragment testFragment = new TestFragment();
fragmentList.add(testFragment);
newSection.setTarget(testFragment);
newSection.setIcon(getResources().getDrawable(R.drawable.icon));
addSection(newSection);
````
When I click on it, nothing occurs. 

However, the first item in the list has a Fragment as a target, and it does get loaded correctly when the activity starts.

My other sections that use a MaterialSectionListener are triggered just fine.

What might be wrong?

**Comment by pawelantczak** [comment]
Code sample is small, but I can see something. 
```newSection.setTarget(testFragment);``` replace with ```newSection.setTarget(fragmentList);```

**Comment by sciencepro** [comment]
Why do you suggest that?  fragmentList is a List<Fragment> that I use for other purposes.  My understanding is that setTarget() should accept a Fragment.

**Comment by pawelantczak** [comment]
Your understanding is right. I guess I should go to sleep.

**Comment by sciencepro** [comment]
@neokree, can you take a look at this?  Wondering what I'm doing wrong.  If documentation needs to be updated, I'd be glad to help.

**Comment by neokree** [comment]
@sciencepro check the <code>newSection</code> method with the your, You haven't added the listener to the section. Try to use add this method:
```java
        section.setOnClickListener(this);
```
It should work

**Comment by sciencepro** [comment]
Thanks!
