### ISSUE TITLE
Support for Font awesome icons instead of drawable

### ISSUE THREAD

**Issue by macpraveen** [neokree/MaterialNavigationDrawer#171]
Material section currently takes drawable or bitmap as icon parameter.

It will be great if material section takes a font awesome or icomoon or any font glyphs string as icon parameter.

**Comment by yoavst** [comment]
you can use [iconify](https://github.com/JoanZapata/android-iconify#get-started-2) for that
though I suggest using [material-icons](https://github.com/Malinskiy/android-material-icons) instead.

**Comment by sohayb** [comment]
:+1:  for material-icons
