### ISSUE TITLE
Right way to create actionbar menu for target fragments

### ISSUE THREAD

**Issue by mifa** [neokree/MaterialNavigationDrawer#174]
Now i need call onCreateOptionsMenu() from MaterialNavigationDrawer activity:

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        ((Fragment)getCurrentSection().getTargetFragment()).onCreateOptionsMenu(menu, getMenuInflater());
        return super.onCreateOptionsMenu(menu);
    }

and getActivity().invalidateOptionsMenu() in target fragment.

**Comment by yoavst** [comment]
On fragment:
```
@Override
public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setHasOptionsMenu(true);
}

@Override
public void onCreateOptionsMenu(Menu menu, MenuInflater inflater) {
    // TODO Add your menu entries here
    super.onCreateOptionsMenu(menu, inflater);
}
```

taken from [here](http://stackoverflow.com/questions/8308695/android-options-menu-in-fragment)

**Comment by mifa** [comment]
@yoavst Thank you, bro

**Comment by sohayb** [comment]
@mifa can you close the issue please
