### ISSUE TITLE
Non-Material Design App Bar?

### ISSUE THREAD

**Issue by daenth** [neokree/MaterialNavigationDrawer#176]
How would one go about changing the size and padding of the app bar to better reflect Material Design standards? It seems like no matter how many times I change the toolbar's layout_height, it never probably adjusts to the default toolbar's configuration.

**Comment by neokree** [comment]
I don't get your first question. What you mean about: changing the size and padding of the appbar to better reflect material design standards? 
This library reflect the material design standards.

**Comment by pawelantczak** [comment]
I think what @daenth means, is that [fixed statusBar height](https://github.com/neokree/MaterialNavigationDrawer/blob/master/MaterialNavigationDrawerModule/src/main/res/values-v21/dimens.xml#L4) is not suitable for all devices. For example on S4 it should be more than 21dp. I'm getting it programatically:
```java        
int resourceId = resources.getIdentifier("status_bar_height", "dimen", "android");
if (resourceId > 0) {
  Utils.setStatusbasrHeight(resources.getDimensionPixelSize(resourceId));
} 
```
![status](http://i.imgur.com/I658Sgb.png)
