### ISSUE TITLE
BACKPATTERN_BACK_TO_FIRST disables touch events in drawer

### ISSUE THREAD

**Issue by sciencepro** [neokree/MaterialNavigationDrawer#177]
Steps to reproduce:

Call  `setBackPattern(BACKPATTERN_BACK_TO_FIRST);` in `init`

Open drawer, click on a Fragment target.
Press the back button.
Open drawer again, click on a target - no touch response.

**Comment by mrcasals** [comment]
Yes, check #120 :) discussion is over there

**Comment by sciencepro** [comment]
No longer occurs in 1.3.1
