### ISSUE TITLE
Not compatible with MaterialDesignLibrary

### ISSUE THREAD

**Issue by Trojaner25** [neokree/MaterialNavigationDrawer#179]
Since this commit: https://github.com/neokree/MaterialNavigationDrawer/commit/b2415b80b40d9cab747251aaa02b873b68620b47 this is not compatible to MaterialDesignLibrary, because the "material-ripple" library used by this and the "MaterialDesignLibrary" both define the attribute "rippleColor"

**Comment by mrcasals** [comment]
I think this issue should be moved to either MaterialDesignLibrary or MaterialRipple repos, not here

**Comment by neokree** [comment]
I'm writing a mail to the material-ripple library developer, but yes, the issue should be moved to the other library.

**Comment by M3talen** [comment]
i recommend to use the build [2e5bb42](https://github.com/neokree/MaterialNavigationDrawer/commit/969500b5a7d22520b5b96f9fd5af071d42329e2a) whilte there will be a fix, you can just download it and import the library. I got my project up and running with this.

**Comment by Trojaner25** [comment]
Moved the issue to material-ripple.
