### ISSUE TITLE
Update material-ripple

### ISSUE THREAD

**Issue by Trojaner25** [neokree/MaterialNavigationDrawer#183]
The material-ripple library got updated, so its not conflicting with MaterialDesignLibrary anymore. As I can't  build my local fork for some reason (gradle can't find javaHome etc...), I can't make a pull-request instead. Please update the lib to version 1.0.1, thanks

**Comment by neokree** [comment]
thank you for the news, I will update the library soon

**Comment by neokree** [comment]
I have released now the new version
