### ISSUE TITLE
Navigation Drawer is open by default.

### ISSUE THREAD

**Issue by willowcheng** [neokree/MaterialNavigationDrawer#184]
Followed by example [MockedAccount](https://github.com/neokree/MaterialNavigationDrawer/blob/master/MaterialNavigationDrawer/app/src/main/java/it/neokree/example/light/MockedAccount.java). My navigation drawer is open by default, is there any way to change it while example will not display navigation drawer at first?

By the way, will it be any documentation for further information of use? I really appreciate this repo and it's very easy to use.

**Comment by egor-n** [comment]
Navigation drawer is opened the first time you enter an app if learning pattern is enabled. To disable it call `#disableLearningPattern` method inside your activity.
