### ISSUE TITLE
when you click twice in the same section, the fragment dissapear

### ISSUE THREAD

**Issue by Atriz-Developer** [neokree/MaterialNavigationDrawer#185]
First of all, It's awesome and easy with this navigation drawer. Thanks!

By the way, I've implemented some fragments acording to each section for my app, but, when the user click twice in the same section, the fragment dissapear! the layout got a white background, I assume it's something about the fragment replacement method. When the user click in another section the layout inflate all views inside the associated fragment. everythings is right! Yei!!! and If you click again in the section with the fragment that had disappear... it appear again!!!!! yep, all these things happen time and time again.  

I've done all the wiki says, jejeje,
I've done wrong implementation? 
it's there other way to do this method?

**Comment by Brblol** [comment]
I have this problem as well.

I a fragment with a view pager inside it. the first time I open this fragment everything is fine but if I navigate to somewhere else and come back to this fragment, there is only a white screen.

after debuging a bit I saw that the getview for the pager adapter is not called the second time, so the fragments in my pager are not created again.

can someone please shed some light

**Comment by Brblol** [comment]
I have found a solution to my problem

padding getChildFragmentManager() instead of getFragmentManager() to my fragment adapter fixed the problem

**Comment by neokree** [comment]
In test version when user clicks on the same section that is actually opened I simply close the drawer.

**Comment by swolford** [comment]
I have the same problem as @GEDIT-Developer.

Clicking on the currently selected section in the navigation drawer makes it disappear. I don't have any fancy layouts, only LinearLayout with TextView and EditText. Switching to another section in the drawer and returning brings it back but disappears again when selecting the same section!

The problem doesn't happen on my HTC One M7 running Lollipop, but it does on my LG Optimus Showtime running Ice Cream Sandwich 4.0.4. This might be an issue with appcompat.

My setup:

Android Studio version 0.9.9
Appcompat: appcompat-v7:21.0.3

compileSdkVersion 21
buildToolsVersion "21.1.2"

minSdkVersion 14
targetSdkVersion 21

I'll do some more in-depth testing and poking around in the next few days.

**Comment by gvsharma** [comment]
I have faced this problem and the simple solution is change
getFragmentManager() to getChildFragmentManager()...

Cheers..all the best.

G VenkateshwaraSharma
Software Developer

**Comment by swolford** [comment]
I've found the solution. In your fragment, change

    import android.support.app.Fragment;

to

    import android.support.v4.app.Fragment;

After changing the type of fragment to the one in the support library, the issue goes away.

**Comment by nguyentando** [comment]
Could anyone tell me more details about the solution that is changing from getFragmentManager() to getChildFragmentManager(). 
Where is the code "getFragmentManager()".
