### ISSUE TITLE
Toolbar color changes before content

### ISSUE THREAD

**Issue by mrcasals** [neokree/MaterialNavigationDrawer#186]
On 1.3.2, when changing sections, toolbar color changes on click, but section content and toolbar title change when the drawer is totally closed. This results in a weird state where you have the toolbar with a color, but the contents of the previous section. See these screenshots:

1. First screenshot is the first section
1. Second screenshot is the second section
1. Third screenshot is the state after clicking the section in the drawer, but the content has not been totally replaced.

I don't have this issue in 1.3.0.

![screenshot_2015-02-18-15-38-56](https://cloud.githubusercontent.com/assets/491891/6249055/eb691280-b784-11e4-92ef-5addb016f777.png)

![screenshot_2015-02-18-15-39-05](https://cloud.githubusercontent.com/assets/491891/6249058/efc90498-b784-11e4-91ad-e1aacc035405.png)

![screenshot_2015-02-18-15-40-43](https://cloud.githubusercontent.com/assets/491891/6249059/f371c8a0-b784-11e4-89bb-ab1df5dbfd26.png)

**Comment by neokree** [comment]
This problem will be fixed with the next version, It was the first fix I did after the 1.3.2 release

**Comment by neokree** [comment]
If you use the test version the bugfix is already avariable

**Comment by ChristopheVersieux** [comment]
Is it possible to use the test version with build.gradle or do we have to clone the project and import manually inside AS?

**Comment by neokree** [comment]
actually you should import the library manually.
