### ISSUE TITLE
smallestScreenWidthDp still used directly.

### ISSUE THREAD

**Issue by pawelantczak** [neokree/MaterialNavigationDrawer#187]
Hello.
You are trying to access smallestScreenWidthDp [here](https://github.com/neokree/MaterialNavigationDrawer/blob/b4cac600919934eb3d1ded06e13548d70dfe99d5/MaterialNavigationDrawerModule/src/main/java/it/neokree/materialnavigationdrawer/MaterialNavigationDrawer.java#L1208). On api < 13 it is causing npe.

**Comment by neokree** [comment]
Thanks @pawelantczak, I will fix it
