### ISSUE TITLE
Cover and Profile photo not showing

### ISSUE THREAD

**Issue by l-petrov** [neokree/MaterialNavigationDrawer#188]
I am using this code to get a bitmap of the photo from url but when I create a new account the photos are not displayed. they do appear when I rotate the screen and then it works properly...

This is how i get the Photo:

public class GetProfileImg extends AsyncTask<String, Void, Bitmap> {

        ImageView bitMapView;

        public GetProfileImg(ImageView bitMapView) {
            this.bitMapView = bitMapView;
        }
        public Bitmap bitmapIcon = null;
        protected Bitmap doInBackground(String... urls){
            String url = urls[0];

            try {
                InputStream inputStream = new URL(url).openStream();
                bitmapIcon = BitmapFactory.decodeStream(inputStream);
            } catch (Exception e) {
                e.printStackTrace();
            }
            return bitmapIcon;
        }
        protected void onPostExecute(Bitmap res) {profile = res;}
    }

and them Im doing this:

MaterialAccount account = new MaterialAccount(this.getResources(),name,"",profile,cover);
        addAccount(account);

The cover and the profile picture do not appear until I rotate the screen...
How can i fix this?

**Comment by neokree** [comment]
read on the [wiki](https://github.com/neokree/MaterialNavigationDrawer/wiki/Accounts#update-the-account-information-asyncronously)

You should call <code>notifyAccountDataChanged</code> method if you want to change account information at runtime.

**Comment by l-petrov** [comment]
The wiki also say that if you use it like this:

MaterialAccount account = new MaterialAccount(this.getResources(),name,"",profile,cover);

You dont need to call notifyAccountDataChanged method

**Comment by l-petrov** [comment]
Ok. I tried to do this: 
`   account = new MaterialAccount(this.getResources(),name,"",profile,cover); 
            notifyAccountDataChanged(); `
         `   addAccount(account); `
It did not help. The Pictuers stil apper only after i rotate my device.

And this code crashed: 
`   account = new MaterialAccount(this.getResources(),name,"",profile,cover); `
         `   addAccount(account); `
`notifyAccountDataChanged();`

**Comment by neokree** [comment]
The correct way to add an account Asyncronusly is: 
```java
account = new MaterialAccount(this.getResources(),name,"",profile,cover);
addAccount(account);
notifyAccountDataChanged();
```
Now if a crash appened, please share the api used, the device specs and the logcat error.
