### ISSUE TITLE
Changing section from inside another section

### ISSUE THREAD

**Issue by mrcasals** [neokree/MaterialNavigationDrawer#189]
I'm in section 1, I want to change to section 2 when clicking a button inside section 1 (not changing with the drawer), how can I do this?

Thank you!

**Comment by neokree** [comment]
If your Fragment is used only as a target section, you can use this code:
<code>((MaterialNavigationDrawer)this.getActivity())</code>
With this you have a pointer to your drawer and you can use all drawer methods, like <code>setFragment</code>, <code>setSection</code> and <code>setFragmentChild</code>

You can find an example [there](https://github.com/neokree/MaterialNavigationDrawer/tree/master/MaterialNavigationDrawer/app/src/main/java/it/neokree/example/functionalities/master_child)

**Comment by mrcasals** [comment]
Yeah, `setSection` seems to be the one I need, thank you! I'll try it next Monday :)

**Comment by TheAnimatrix** [comment]
How do you declare a MaterialSection inside a fragment ?

**Comment by mrcasals** [comment]
I created sections in a public `ArrayList`, then iterated on this list to add them to the drawer. This way I can find the sections from other places.

**Comment by neokree** [comment]
@TheAnimatrix You can use the materialnavigationdrawer methods for:<br>
getting all sections: <code>getSectionList</code><br>
get the section at position: <code>getSectionAtCurrentPosition</code><br>
get the current section: <code>getCurrentSection</code>

From the next release, a new method is called for get the section knowing his title. For now, you can get all section list and check what section is your target.
