### ISSUE TITLE
Accounts Problem

### ISSUE THREAD

**Issue by l-petrov** [neokree/MaterialNavigationDrawer#190]
So this is the problem: I have the Navigation Drawer Activity and in the `init` method I use this code(as shown in the wiki) to add an account: 
    `account = new MaterialAccount(getResources(), name, email, profilePhoto, background);
            addAccount(account);`

but when the activity is lanuched the header of the Drawer is White and you can beraly see the title and sub title on a completely white background. The photo and the background appear only when i turn my device to landscape, after that it works fine in landscape and protrait. What could be the problem and how I can make the photo and background appear when the activity starts?

**Comment by mithrann** [comment]
I am having the same issues, But its happening occasionally. So i could't find anything in the log. So i had to close the app and reopen it when every time this while space  comes.

**Comment by l-petrov** [comment]
It happen every time for me... I think that maybe it because I load my photos from a URL...

**Comment by neokree** [comment]
If you want to use a photo from URL make sure you load a bitmap and use a bitmap as a parameter. 
All Account resources before used are resized to the correct width and height for the device, then It will be used. Now this process can be a little longer on low devices, so a white header is showed. If you wait some time (not turning the device to landscape) the images will be loaded asynchronously.

**Comment by mithrann** [comment]
First i am creating an account using

// here both account image and bg are loaded from drawable
Agentaccount = new MaterialAccount(this.getResources(), name, Email, R.drawable.agent_img, R.drawable.acc_bg);
this.addAccount(Agentaccount);

// here i am downloading the image from url and loading that bitmap to account
// Somewhere here the header background goes white(That should't be happening right?)
ImageLoader.getInstance().loadImage(image_url, targetSize, new SimpleImageLoadingListener() {
                    @Override
                    public void onLoadingComplete(String imageUri, View view, Bitmap loadedImage) {
                        // Do whatever you want with Bitmap
                        Agentaccount.setPhoto(loadedImage);
                        SyncAgentAccount();
                    }
                });

  private void SyncAgentAccount() {
        runOnUiThread(new Runnable() {
            @Override
            public void run() {
                notifyAccountDataChanged();
            }
        });
    }
