### ISSUE TITLE
A slight delay in displaying sections

### ISSUE THREAD

**Issue by mithrann** [neokree/MaterialNavigationDrawer#191]
I was using version 1.3 and it was fine. now i tried the 1.3.1. But here when i click the section in navigation drawer- it takes couple of seconds to load the respected the section.(only in this new version i am experiencing this problem). Thanks.

**Comment by neokree** [comment]
Yes, Now from 1.3.1 the fragment is loaded after the drawer is closed, like described [here](http://stackoverflow.com/questions/17491557/drawerlayouts-item-click-when-is-the-right-time-to-replace-fragment) to prevent laggy close.
