### ISSUE TITLE
Confict with other repositories

### ISSUE THREAD

**Issue by willowcheng** [neokree/MaterialNavigationDrawer#192]
Hi,

I meet the problem for attributes definition conflict (such as `rippleColor`) with [material-ripple](https://github.com/balysv/material-ripple) library and [MaterialDesignLibrary](https://github.com/navasmdc/MaterialDesignLibrary) library.

Is there any way to solve it?

**Comment by neokree** [comment]
1.3.2 version resolve this bug.
