### ISSUE TITLE
change Toolbar Color doesn't work as expected

### ISSUE THREAD

**Issue by ternes3** [neokree/MaterialNavigationDrawer#194]
```java
((MaterialNavigationDrawer)this.getActivity()).changeToolbarColor("#f44336", "#e53935");
```
result:
![toolbar](https://cloud.githubusercontent.com/assets/1932977/6319467/6ecc217c-babd-11e4-9842-2b60b53c6d58.png)
i guess the black/grey line is a result of issue #193

**Comment by AGr7K** [comment]
yoy forget "Color.parseColor("Color code")"
((MaterialNavigationDrawer)this.getActivity()).changeToolbarColor(Color.parseColor("#f44336"), Color.parseColor("#e53935"));
