### ISSUE TITLE
How to add a search Icon to actionbar?

### ISSUE THREAD

**Issue by mohfaz** [neokree/MaterialNavigationDrawer#198]
I wonder to know how to add a search icon with onclicklistener to the action bar.
I have another question. I used getWindow().getDecorView().setLayoutDirection(View.LAYOUT_DIRECTION_RTL); in init() method
to make navigation drawer RTL. But the code doesn't work on android 4.1.2. .
/*
MaterialNavigationDrawer verison: 1.2.9
android:minSdkVersion="11"
android:targetSdkVersion="21" 
*/

**Comment by neokree** [comment]
This library create a navigation drawer, but remember you still coding on android. You can add menu like all another activity. [Menu](http://developer.android.com/guide/topics/ui/menus.html)
Android support natively RTL only from 4.2 version. [described here](http://android-developers.blogspot.it/2013/03/native-rtl-support-in-android-42.html)

**Comment by mdenhartog** [comment]
Simple example:

Add for example menu_application.xml to you application 
<?xml version="1.0" encoding="utf-8"?>
<menu xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    
    <item
        android:id="@+id/action_settings"
        android:orderInCategory="200"
        android:title="@string/action_settings"
        app:showAsAction="never" />

    
    <item
        android:id="@+id/action_search"
        android:orderInCategory="100"
        android:title="@string/action_search"
        android:icon="@drawable/ic_search_white_24dp"
        app:showAsAction="always"/>
</menu>

and in the MaterialNavigationDrawer activity add 
@Override
    public boolean onCreateOptionsMenu(Menu menu) {
        getMenuInflater().inflate(R.menu.menu_application, menu);
        return true;
    }
