### ISSUE TITLE
How do I remove the account switcher

### ISSUE THREAD

**Issue by wesjon** [neokree/MaterialNavigationDrawer#199]
Hi there and thanks for this awesome library,

It doesn't make much sense to have multiple accounts in my app. Is it possible to enable a **single account mode** or remove the **account switcher**? 

I'm using the version *1.3.2* and I couldn't find a way to do that.

**Comment by pawelantczak** [comment]
Check this [line](https://github.com/neokree/MaterialNavigationDrawer/blob/master/MaterialNavigationDrawer/app/src/main/res/values/styles.xml#L10) in sample app.

**Comment by wesjon** [comment]
Thank you, @pawelantczak  It worked like a charm.
