### ISSUE TITLE
Icon "back" appears in the Section

### ISSUE THREAD

**Issue by fortuna58rus** [neokree/MaterialNavigationDrawer#200]
I opened the app and there I choose a object that invokes the setFragmentChild. Then I open the navigation drawer, and select any Section with targetFragment. In ActionBar an arrow appears.

MaterialNavigationDrawer verison: 1.3.2
android:minSdkVersion="10"
android:targetSdkVersion="21"

**Comment by neokree** [comment]
Thank you for the segnalation, I will check and fix it

**Comment by fortuna58rus** [comment]
Fixed a bug, thank you for the excellent library
