### ISSUE TITLE
How to hide android soft keyboard

### ISSUE THREAD

**Issue by mithrann** [neokree/MaterialNavigationDrawer#202]
if there is edit text in the section fragment, on click of that, the keyboard appears which is fine. But i need to hide that whenever the action toggle is pressed from navigation drawer or swipe left to right.

Thanks

**Comment by neokree** [comment]
you can attach a listener to the navigation drawer, using <code>setDrawerListener</code> method.

**Comment by mithrann** [comment]
Thanks:). Working
