### ISSUE TITLE
Two Things

### ISSUE THREAD

**Issue by RubyDerBoss** [neokree/MaterialNavigationDrawer#204]
Hi, I have a question: What is the difference between
```java
addMultiPaneSupport();
``` 
and 
```xml
<item name="multipaneSupport">true</item>
```
or is it the same?

I also have a request: I have a Drawer with many sections, which have a Fragment as a Target. But two of those open a dialog instead and when the user clicks on one the dialog section is selected, but the section with the fragment in which the user is is not highlighted anymore, which is ugly in my opinion.
So i thought of something like a OnSectionChangedListener so i can keep track of the currently selected Section and unselect a Dialog section when a User clicks it and select the current Fragment section the user is in.
I hope you understand what I mean, because english is not my mother language.

**Comment by FWest98** [comment]
First:
They are the same.

Second:
You can always manually set a section to be selected. Create some sort of listener in your dialogfragment (and implement it) or create a static void in your activity and run it when the dialog is shown. Then in the function called you can set the correct section to be selected.

**Comment by RubyDerBoss** [comment]
Second:
I think that is not the problem I have. I make an example: I have a Section with a fragment as its target, which shows some statistics. I have also a section which shows a login dialog, but if that is closed the user remains in the statistics section. The problem is that the statistics section is not selected anymore, but the login section which shows the dialog. That is wrong and I want to set the statistics section as selected again, but I found no way to do that.
