### ISSUE TITLE
Custom typeface for section

### ISSUE THREAD

**Issue by savekirk** [neokree/MaterialNavigationDrawer#205]
Is it possible to use a custom typeface for the sections apart from the default fonts used?.
Currently, adding a typeface for the sections is overridden by the default typefaces. 

Thanks.

**Comment by FWest98** [comment]
You can use the public function setTypeface and it will set that typeface.
Basically:
````
for(MaterialSection section : getSectionList()) {
    section.setTypeface(/*some*/);
}
````
