### ISSUE TITLE
Disabling/Enabling drawer sections

### ISSUE THREAD

**Issue by mlumeau** [neokree/MaterialNavigationDrawer#207]
Hi,
I thought it would be great if we could enable and disable sections at our convenience, like buttons. 

Something like `mySection.setEnabled(false);`

For instance, in my case I have some sections in my drawer that should be clickable only if the device is connected to the Internet.

Thanks.

**Comment by FWest98** [comment]
I think setTouchable(boolean) is what you're looking for. If I look at the code, it won't run the listeners and callbacks when that's false. It doesn't change the UI, so you can't tell if a section is touchable or not (only by clicking it, touchable items will have ripple or different background).

**Comment by mlumeau** [comment]
Well then it's not what I'm looking for. I need the section to be greyed
out.

**Comment by FWest98** [comment]
You can hack around that:
````
View sectionView = section.getView();
TextView sectionTitleView = (TextView) sectionView.findViewById(R.id.section_text); // not sure if you can access that, it's in the R of the library
sectionTitleView.setTextColor(/* your color here */);
````
