### ISSUE TITLE
Advanced theming not working

### ISSUE THREAD

**Issue by fncapps** [neokree/MaterialNavigationDrawer#209]
I've tried to follow [Advanced Theming](https://github.com/neokree/MaterialNavigationDrawer/wiki/Theming#advanced-theming) but I'm having some trouble with ``subheaderTitleColor`` and ``colorPrimaryDark`` which aren't working correctly. subheaderTitleColor keeps the same color whatever color I choose in the theme. Also, the toolbar is being shown black all the time as well.

**Comment by neokree** [comment]
version used? api tested? 
However theming is working, because if it not in the example app could not working with light and dark theme.

**Comment by fncapps** [comment]
I'm using ``compile 'it.neokree:MaterialNavigationDrawer:1.3.2'`` and I don't know what do you mean with API tested... I can tell you however, I'm using compileSdkVersion 21, buildTools 21.1.1 and targetSdk 21 as well. minSdk is set to 14

**Comment by neokree** [comment]
the device that run your project, what api it have?

**Comment by fncapps** [comment]
I've test my app on Lollipop(API 21) and KitKat (API 19); both not working correctly

**Comment by fncapps** [comment]
I've updated to buildTools 21.1.2 and still not working... any thought about what can be happening?

**Comment by fncapps** [comment]
I've made a simple app with the issues I have: 
1) Status bar not working with ´´colorPrimaryDark´´
2) Subheader colors not working

I have shared it on [GitHub](https://github.com/fncapps/materialDrawer), please could you take a look at the project and tell me if there is something wrong with it?

**Comment by merijnbrs** [comment]
Why is this issue still not fixed? i struggle with exactly the same thing!

**Comment by fncapps** [comment]
What about ``colorPrimaryDark`` issue?

**Comment by neokree** [comment]
It is resolved with the 1.3.3
However, check if it is working. In my sample app and your sample project it is

**Comment by fncapps** [comment]
Sorry for the delay in my answer. I checked the new update 1.3.3. ``colorPrimaryDark`` is now working  great. However, I am not able to use subheader theming yet, but I consider this a minor bug. So, you could probably close the issue.

Thanks
