### ISSUE TITLE
Starting Activity with Intent

### ISSUE THREAD

**Issue by hoshomoh** [neokree/MaterialNavigationDrawer#211]
Please how do i pass data along to intent when starting an activity?

**Comment by sohayb** [comment]
You put your parameters in a bundle or directly to the intent (intent.put...). your arguments should be primitive types, or a parcelable object.
This has nothing to do with the library but hope this helps :)

**Comment by tejaslodaya** [comment]
Im unabe to open another activity, via the startActivity() function. I made the ImageNavigationDrawer as my LAUNCHER activity.. And made section1 call another activity.. But not working.. Keeps   crashing.

**Comment by mrcasals** [comment]
The first section must be a fragment, as stated in the wiki.  

--  
Marc Riera Casals

**Comment by sohayb** [comment]
:+1:

**Comment by tejaslodaya** [comment]
Still not working bro.Let me show you the code..
ImageDrawerHeader:

public class ImageDrawerHeader extends MaterialNavigationDrawer {
    @Override
    public void init(Bundle savedInstanceState) {

        // set the header image
this.setDrawerHeaderImage(R.drawable.mat2);

        // create sections
        this.addSection(newSection("Section 1", new FragmentIndex()));
        this.addSection(newSection("Section 2",new Intent(this,MainActivity.class)));
        this.addSection(newSection("Section 3", R.drawable.ic_mic_white_24dp,new FragmentButton()).setSectionColor(Color.parseColor("#9c27b0")));
        this.addSection(newSection("Section",R.drawable.ic_hotel_grey600_24dp,new FragmentButton()).setSectionColor(Color.parseColor("#03a9f4")));

        // create bottom section
        this.addBottomSection(newSection("Bottom Section",R.drawable.ic_settings_black_24dp,new Intent(this,Settings.class)));
    }
}

As you told, I made the first one as fragment..

MainACtivity:


public class MainActivity extends ActionBarActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
    }


    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.menu_main, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Handle action bar item clicks here. The action bar will
        // automatically handle clicks on the Home/Up button, so long
        // as you specify a parent activity in AndroidManifest.xml.
        int id = item.getItemId();

        //noinspection SimplifiableIfStatement
        if (id == R.id.action_settings) {
            return true;
        }

        return super.onOptionsItemSelected(item);
    }
}

**Comment by tejaslodaya** [comment]
Any help is appreciated.. I am working on this since two days, no sign of success

**Comment by tejaslodaya** [comment]
Manifest file:

        <activity
            android:name=".MainActivity"
            android:label="@string/app_name" >
            <intent-filter>
                <action android:name="android.intent.action.MAINACTIVITY" />

                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </activity>

        <activity
            android:name=".ImageDrawerHeader"
            android:label="@string/app_name" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

I have shown only two activities

**Comment by tejaslodaya** [comment]
I'm getting this warning(Not an error):

ImageDrawerHeader.java uses unchecked or unsafe operations.

**Comment by mrcasals** [comment]
The `FragmentIndex` exists in your codebase, right? Without the backtrace it's quite difficult to debug...

Anyway, I guess that what you want is the `MainActivity` to have the navigation drawer, right? Move the content of `MainActivity` into a Fragment (let's say you call it `MainFragment`) and then in your `ImageDrawerHeader` activity set this code:

```java
public class ImageDrawerHeader extends MaterialNavigationDrawer {
@Override
public void init(Bundle savedInstanceState) {

    // set the header image
this.setDrawerHeaderImage(R.drawable.mat2);

    // create sections
    this.addSection(newSection("Section 1", new MainFragment()));
    this.addSection(newSection("Section 2",new Intent(this,MainActivity.class)));
    this.addSection(newSection("Section 3", R.drawable.ic_mic_white_24dp,new FragmentButton()).setSectionColor(Color.parseColor("#9c27b0")));
    this.addSection(newSection("Section",R.drawable.ic_hotel_grey600_24dp,new FragmentButton()).setSectionColor(Color.parseColor("#03a9f4")));

    // create bottom section
    this.addBottomSection(newSection("Bottom Section",R.drawable.ic_settings_black_24dp,new Intent(this,Settings.class)));
}
}
```

**Comment by mrcasals** [comment]
The wiki says:

> **NOTE** that the first section you added is opened when the activity starts, so it must have a Fragment as target.

Source: https://github.com/neokree/MaterialNavigationDrawer/wiki/Sections

**Comment by tejaslodaya** [comment]
So, if I put a blank fragment as my first section, like:

  this.addSection(newSection("Section 1", new FragmentIndex()));
        this.addSection(newSection("Section 2",new Intent(this,MainActivity.class)));
        this.addSection(newSection("Section 3", R.drawable.ic_mic_white_24dp,new FragmentButton()).setSectionColor(Color.parseColor("#9c27b0")));
        this.addSection(newSection("Section",R.drawable.ic_hotel_grey600_24dp,new FragmentButton()).setSectionColor(Color.parseColor("#03a9f4")));

As you said, the first should be a fragment.. I have put a new(blank) fragment,..Still the app is crashing

**Comment by mrcasals** [comment]
The first section is what will be renderer behind the navigation drawer. Can you paste the backtrace please?

**Comment by tejaslodaya** [comment]
By backtrace, you mean the FragmentIndex() right?

**Comment by tejaslodaya** [comment]
package it.neokree.example.tcf.mockedFragments;

import android.os.Bundle;
import android.support.annotation.Nullable;

import android.support.v4.app.Fragment;
import android.view.Gravity;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;


/**
 * Created by neokree on 24/11/14.
 */
public class FragmentIndex extends Fragment {

    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        TextView text = new TextView(this.getActivity());
        text.setText("Section");
        text.setGravity(Gravity.CENTER);
        return text;
    }

}

**Comment by tejaslodaya** [comment]
Should the fragment class be v4 or the normal library?

**Comment by mrcasals** [comment]
No sorry, the stacktrace of the error.

--  
Marc Riera Casals

**Comment by tejaslodaya** [comment]
I dont use the emulator.. I run the app on my phone.

**Comment by tejaslodaya** [comment]
Any other way u can find the fault?

**Comment by neokree** [comment]
@tejaslodaya you can stacktracing the fault using android studio, open the logcat error and keep connected the cable to your phone when the app run.
