### ISSUE TITLE
I would like to have a Section with my own View.OnClickListener

### ISSUE THREAD

**Issue by anticafe** [neokree/MaterialNavigationDrawer#213]
With my own onClickListener, I can open a dialog, show a Toast, or start new Activity...

Is it possible?

Edit: I see there is such a method:
`public MaterialSection newSection(String title, int icon,MaterialSectionListener target)`

However if I use `MaterialSectionListener`, after clicking on it, this section will be in selected state while I only need to keep selection on main Fragment.

**Comment by neokree** [comment]
You can use the <code>MaterialSectionListener</code> and call the <code>section.unSelect();</code>
inside of it.

**Comment by anticafe** [comment]
It works. Thank you.
