### ISSUE TITLE
how can I close navigation drawer when start?

### ISSUE THREAD

**Issue by yoshimaa** [neokree/MaterialNavigationDrawer#215]
thanks neokree!!

always Navigation drawer is open when I start application.

how can I close navigation drawer when start?

please help me.

**Comment by RubyDerBoss** [comment]
Just call
'''java
this.disableLearningPattern();
'''
in your init() Method.
More about that in the wiki: https://github.com/neokree/MaterialNavigationDrawer/wiki/Functionalities

**Comment by tejaslodaya** [comment]
How can i make this activity as a launcher activity?/
It doesnt have a onCreate() method.. And when i make this a launher activity in the manifest. the app doesnt have a open button.. Anyways, my question is how to make this a launcher activity,.. Or how to integrate this inside my MainActivity(Which has a onCreate() method in it?

**Comment by tejaslodaya** [comment]
Help is deeply appreciated

**Comment by yoshimaa** [comment]
thanks RubyDerBoss!!
i should have seen read seriously.
thanks a lot.

**Comment by RubyDerBoss** [comment]
The init method acts like the onCreate metod. Just move all your code from your onCreate into the init() method. To declare your activity as launcher just add this to your manifest: 
```xml
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>

                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
```

**Comment by tejaslodaya** [comment]
For example:

MainActivity extends ActionBarActivity(){

onCreate(){
setContentView();
...
...
...}

somemoremethods(){

...
...
}
}
And should I copy paste the code into this class?:
i.e From onCreate of MainActivity into init() of ImageDrawerHeader class?

class ImageDrawerHeader extends MaterialNavigationDrawer{

init(){

..FragmentIndex()
...
..
}
}

**Comment by RubyDerBoss** [comment]
Your activity must extend MaterialNavigationDrawer. Then you have to override the init() method. More on this: https://github.com/neokree/MaterialNavigationDrawer/wiki/Set-Up-a-Navigation-Drawer-Activity

**Comment by tejaslodaya** [comment]
Can you show me how the code looks like? Just put some dummy data inside.. Like i did.. Help is appreciated..You may think of me as a n00b

**Comment by tejaslodaya** [comment]
And it says i cannot override the setContentView inside the init method? Should i?

**Comment by RubyDerBoss** [comment]
```java
public class MainActivity extends MaterialNavigationDrawer {

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.menu_main, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Handle action bar item clicks here. The action bar will
        // automatically handle clicks on the Home/Up button, so long
        // as you specify a parent activity in AndroidManifest.xml.
        int id = item.getItemId();

        //noinspection SimplifiableIfStatement
        if (id == R.id.action_settings) {
            return true;
        }

        return super.onOptionsItemSelected(item);
    }

    @Override
    public void init(Bundle bundle) {
        MaterialSection section = this.newSection("First Section", R.drawable.someIcon, SomeFragment.newInstance(parameter));
        //Create more sections

        this.addSection(section);
        //add more sections
        //Do some theming or other MaterialNavigationDrawer related things

        someMethod();
        //More methods
    }

    private void someMethod(){
        doSomething();
    }
}
```java

**Comment by RubyDerBoss** [comment]
This is how you do it. It is a freshly generated project, see the comments and the code. 
And No you don't override setContentView, because the MaterialNavigationDrawer has its own layout. Your fragments should have layouts and code which do what you want.
