### ISSUE TITLE
Show a specific Section in Activity init() method instead of the first Section.

### ISSUE THREAD

**Issue by AlexNsbmr** [neokree/MaterialNavigationDrawer#216]
How to show a specific Section instead of the default first Section at the Activity launch?
I Tried to use setSection() after addSection() but it gives me a null pointer exception in the init() method.

**Comment by neokree** [comment]
At this time there is no way to show specific section instead of the default section. 
I suppose that you want to start another section from the main section list, (so not from the bottom section list or the accountsectionlist), I am right?

**Comment by AlexNsbmr** [comment]
Yes it's exactly what I want to achieve with the main section list. 
I need to do this: When the app is not running, I would like to open a specific Fragment when the user clicks on a notification.

**Comment by willowcheng** [comment]
@neokree 
I meet the same problem as @AlexNsbmr that I want to start third section from a notification. Expect to see solution for that.

**Comment by gitton** [comment]
@neokree  awesome library
I was also looking for the same case

**Comment by lucamenor** [comment]
For to do that, I change the section (setSection) in onPostCreate method.

**Comment by AlexNsbmr** [comment]
It's working like a charm! Thanks a lot for adding this feature and keep the good work!

**Comment by willowcheng** [comment]
@lucamenor 
It works, thanks a lot!
