### ISSUE TITLE
Problem with elevation

### ISSUE THREAD

**Issue by RubyDerBoss** [neokree/MaterialNavigationDrawer#217]
With elevation added to the Toolbar it looks not normal:
![example](https://cloud.githubusercontent.com/assets/8021265/6510128/4f39d9a8-c364-11e4-847a-4ceaf349174c.png)
This also happens if I call setChildFragment(). Moreover there is no Back Icon.

**Comment by neokree** [comment]
What version are you using?

**Comment by RubyDerBoss** [comment]
I'm using 1.3.2 but with these layouts:
activity_material_navigation_drawer.xml	testing outofmemory
activity_material_navigation_drawer_customheader
from Version 1.3.3

**Comment by RubyDerBoss** [comment]
The theme there has a elevation of 4dp and this effect appears. I have noted that it looks just normal without eleveation.

**Comment by neokree** [comment]
check the dimens.xml for version 21

**Comment by RubyDerBoss** [comment]
Yes, okay I missed that.
