### ISSUE TITLE
Master/Child example returns init() when back to background

### ISSUE THREAD

**Issue by jmvines** [neokree/MaterialNavigationDrawer#218]
Hi @neokree,

First of all, congrats for your library, it is very useful.

I have a problem in my app and this also appears in your Master/Child example, the steps are,

1- Select Section 1 or Section 2
2- Click Button Open Child
3- Go to Background (change another app)
4- Back from background and the app restart the fragment's title to "Section 1" but the content remains second fragment.

Any idea?

**Comment by jmvines** [comment]
Any idea @neokree?

**Comment by neokree** [comment]
Sorry, I have some trouble with my computer and in this week I didn't have the time to do this. 
It will be fixed

**Comment by jmvines** [comment]
Thaks for your answer @neokree  , this bug is fixed in 1.3.3 release?

Thanks for your effort.

**Comment by neokree** [comment]
no, I'm working on it

**Comment by jmvines** [comment]
Hi @neokree, any advance?
Thanks.
