### ISSUE TITLE
Section previously selected remains highlighted even selecting another programatically

### ISSUE THREAD

**Issue by filipebezerra** [neokree/MaterialNavigationDrawer#220]
When I select another section programatically using the method select(), the previous selected section remains highlighted.

The piece of code that can simulate this:

    getSectionByTitle(getString(R.string.my_section_title)).select();

And here my screenshots that prove this issue:

The initial state:
![initial_state](https://cloud.githubusercontent.com/assets/1006095/6541573/df22b6d4-c4b8-11e4-8637-018ecfa1a779.png)

Then, after programatically selecting another section:

![then_after_selecting_another_section](https://cloud.githubusercontent.com/assets/1006095/6541574/f7655878-c4b8-11e4-8aa7-296a6478ce93.png)

**Obs.: After the dual section selection occurs, touching another section fix this wrong state.**

**Comment by filipebezerra** [comment]
I figure out that I have to call unSelect(), but this sounds weird, and unnatural, don't you think?

**Comment by neokree** [comment]
Yes, it is unnatural that you want to select some section programmatically instead of using default methods for changing sections, like `setSection`, `setFragment` or `setFragmentChild`.

**Comment by filipebezerra** [comment]
Can you reference `setFragment` or `setFragmentChild` methods in the documentation please?

**Comment by filipebezerra** [comment]
Please help me with the correct use of the library and `setFragment()` method.

I have this `init()` method:

    @Override
    public void init(final Bundle savedInstanceState) {
        setUpHeader();
        addPrimarySections();
        addDivisor();
        addSecondarySections();
        addBottomSections();
        setBackPattern(MaterialNavigationDrawer.BACKPATTERN_BACK_TO_FIRST);
        handleSearchQuery(getIntent());
    }

In the `addPrimarySections()` method I do following: 

    private void addPrimarySections() {
        addSection(newSection(getString(R.string.navdrawer_menu_item_favorite_bus_stops),
                R.drawable.ic_drawer_pontos_favoritos, new FavoritesListFragment())
                .setNotifications(getFavoriteCount())
                .setSectionColor(
                        getColor(R.color.navdrawer_favorites_section_color),
                        getColor(R.color.navdrawer_favorites_section_dark_color)));
    }

And in the `addSecondarySections()` method  I do:

    private void addSecondarySections() {
        ...
        addSection(newSection(getString(R.string.navdrawer_menu_item_rmtc_horarios_viagem),
                R.drawable.ic_drawer_horario_viagem,
                WebViewFragmentFactory.newHorarioViagemPageFragment(BaseActivity.this))
                .setSectionColor(
                        getColor(R.color.navdrawer_horario_viagem_section_color),
                        getColor(R.color.navdrawer_horario_viagem_section_dark_color)));
        ...
    }

In method `newHorarioViagemPageFragment()` I instantiate this fragment passing a static argument. So when user searches using SearchView widget, it triggers an event that I instantiate this same fragment but now passing arguments dinamically.

Then I do that:

    public void search(final String stopCode) {
        MaterialSection horarioViagemSection = getSectionByTitle(getString(
                R.string.navdrawer_menu_item_rmtc_horarios_viagem));
        getCurrentSection().unSelect();
        setFragment(WebViewFragmentFactory.newHorarioViagemPageFragment(BaseActivity.this, stopCode),
                horarioViagemSection.getTitle());

        horarioViagemSection.select();
        changeToolbarColor(horarioViagemSection);
    }

Is this correct? Because when I call the `search()` method above and then I try select another section by touching in it, the previous and the touched section remains highlighted. But seems not to trigger `onClick()` method because the fragment target of the touched section isn't instantiated.

**Comment by filipebezerra** [comment]
The problem only occurs when I call `search()` method and after that I try to select the first section.

**Comment by neokree** [comment]
you should change your `search` method: 
```java
public void search(final String stopCode) {
    MaterialSection horarioViagemSection = getSectionByTitle(getString(
            R.string.navdrawer_menu_item_rmtc_horarios_viagem));
   setSection(horarioViagemSection);
}
```

**Comment by filipebezerra** [comment]
But in `search` method I have to pass argument to fragment.

**Comment by filipebezerra** [comment]
What about to call method `syncSectionsState` when I set different target for this section?

**Comment by filipebezerra** [comment]
I found I way to fix this.
