### ISSUE TITLE
use finish(); in section and change transition of fragment to right to left

### ISSUE THREAD

**Issue by Sorush-moradisani** [neokree/MaterialNavigationDrawer#221]
I want to set exit button on fragment but I dont know how to use finish(); in sections!
also is there any way i can change transition of fragment to right to left???

**Comment by neokree** [comment]
It doesn't exists a `finish()` in sections, but you can call the activity `finish` using: `getActivity().finish();`
for the second request please see this: #201

**Comment by Sorush-moradisani** [comment]
Tnx. first problem solved :+1: good luck for second one!
