### ISSUE TITLE
How can I start an Activity with setting the second fragment as the default section

### ISSUE THREAD

**Issue by bullest** [neokree/MaterialNavigationDrawer#223]
```java
public void init(Bundle bundle) {
        this.addSection(newSection("First", new FirstFragment()));
        this.addSection(newSection("Second", new SecondFragment()))
 }
```

I init my drawer with two section. When I start the activity, FirstFragment is attached. 
Can I set the SecondFragment as the default fragment when start this activity?

**Comment by RubyDerBoss** [comment]
See https://github.com/neokree/MaterialNavigationDrawer/issues/216#issuecomment-77693315
