### ISSUE TITLE
How to set button to behave same as HomeUpIndicator in child fragment

### ISSUE THREAD

**Issue by willowcheng** [neokree/MaterialNavigationDrawer#224]
I use the master/child fragment, and want to use button in child fragment layout to go back to master fragment, which is the same as back icon in action bar (**HomeUpIndicator**).

Is there any way to do that?

**Comment by neokree** [comment]
mmm the first thing I call into my mind is this: do a call to the onBackPressed() from the main activity.
```java
getActivity().onBackPressed();
```
