### ISSUE TITLE
Bottom sections are not pinned in KitKat

### ISSUE THREAD

**Issue by filipebezerra** [neokree/MaterialNavigationDrawer#225]
According to [Material design guidelines](http://www.google.com/design/spec/patterns/navigation-drawer.html) > Settings and support, bottom sections are not pinned at bottom.

You can see above, screenshots from Moto X genymotion emulators.

![bottom_sections_not_pinned_kitkat_moto_x_portrait](https://cloud.githubusercontent.com/assets/1006095/6546745/7a497554-c59e-11e4-8530-fdb64f5590b5.png)

![bottom_sections_not_pinned_kitkat_moto_x_landscape](https://cloud.githubusercontent.com/assets/1006095/6546741/3a1cc1b6-c59e-11e4-94b9-3cd3fe92faa1.png)

Thanks for your work, an awesome Android library.

**Comment by neokree** [comment]
Ehm, I see that sections are not pinned to the bottom, what is the problem?

**Comment by filipebezerra** [comment]
I think the problem is that I have 2 bottom sections, and the list of content in the navigation drawer is very long, I can scroll down, so these 2 bottom sections must be pinned to the bottom of the navigation drawer.

This same layout in Lollipop or old versions like 4.2 stay pinned at bottom. Why? This is not a problem?

**Comment by neokree** [comment]
Material guidelines tells that bottom sections should be pinned to the bottom ONLY IF there is enough space. If not, the section are not pinned to the bottom but it is inserted as normal section at the end of the list.

**Comment by filipebezerra** [comment]
Look this carefully:

> If the list of content in the navigation drawer is very long, the two options can be pinned to the bottom of the navigation drawer on a surface with a higher elevation. This surface is present only while at the top of the list; any other scroll position will immediately result in dismissing the surface and placing the options at the end of the list, in-line with the rest of the list content. The navigation drawer retains its scroll position when closed and reopened.

In my example, the Drawer is in the top of the list, so the settings sections must be pinned. Believe me is a bug.
