### ISSUE TITLE
SoftInputMode="adjustResize" doesn't work with MyNavigationDrawerTheme

### ISSUE THREAD

**Issue by PaoloRotolo** [neokree/MaterialNavigationDrawer#226]
Hi!
I noticed that Android can't resize the activity when SoftKeyboard is opened if I'm using your DrawerTheme. All works fine with Lollipop's default theme (applied in styles.xml).

Activity with default theme:
![screenshot_2015-03-08-20-25-37](https://cloud.githubusercontent.com/assets/5623301/6547200/9ecc8df2-c5d1-11e4-8416-561a2e74a357.png)

Activity with MyNavigationDrawerTheme:
![screenshot_2015-03-08-20-24-52](https://cloud.githubusercontent.com/assets/5623301/6547201/9ecd282a-c5d1-11e4-871a-8a4f3e88a4fb.png)
EditText is **below** the Soft Keyboard, so the activity wasn't resized.

Best regards,
Paolo

**Comment by neokree** [comment]
could you share your drawer layout please?

**Comment by PaoloRotolo** [comment]
Sure, I uploaded the sources on GitHub: https://github.com/numixproject/org.numixproject.hermes

I'm having this issue with basically all activities especially with ConversationActivity and AddServerActivity.

Thanks again!

**Comment by neokree** [comment]
Well, I didn't understood very well the problem... 
When the keybard appears in landscape mode, the layout can't be resized so the edit text required remains under the keyboard?

**Comment by PaoloRotolo** [comment]
Exactly. We're trying to make an IRC client and it's impossible to chat if you don't see the text you're typing. With default theme I've the same behaviour of Hangout or WhatsApp. It just doesn't work with your custom theme.

Thanks again for the help,
Paolo

**Comment by PaoloRotolo** [comment]
Update: it happens both in landscape and portrait mode.

**Comment by neokree** [comment]
Well, sincerily I don't know how "adjustResize" works, I will investigate on that

**Comment by PaoloRotolo** [comment]
UPDATE: It works well with adjustPan (scrolls up ALL the view, even the ActionBar):

Keyboard closed:
![screenshot_2015-03-20-18-19-25](https://cloud.githubusercontent.com/assets/5623301/6757097/b593f3a2-cf2e-11e4-9f41-02c890160057.png)

adjustPan on:
![screenshot_2015-03-20-18-25-38](https://cloud.githubusercontent.com/assets/5623301/6757095/b58f7fde-cf2e-11e4-9863-251a4a35865d.png)

adjustResize on:
![screenshot_2015-03-20-18-19-28](https://cloud.githubusercontent.com/assets/5623301/6757096/b593f33e-cf2e-11e4-937e-17e852c3a190.png)

Actually I need Resize, because users should be able to see all messages and ActionBar.

**Comment by PaoloRotolo** [comment]
I think it's an Android bug: https://code.google.com/p/android/issues/detail?id=5497&q=fullscreen&colspec=ID%20Type%20Status%20Owner%20Summary%20Stars

AdjustResize doesn't work when activity is full screen. Is MaterialNavigationDrawer using Full Screen activities?

**Comment by neokree** [comment]
no, materialnavigationdrawer use normal actionbar activity without action bar

**Comment by josefigueredo** [comment]
Same problem here. Did you find a work arround PaoloRotolo?

**Comment by josefigueredo** [comment]
I found a solution: https://stackoverflow.com/questions/21092888/windowsoftinputmode-adjustresize-not-working-with-translucent-action-navbar/22266717#22266717

**Comment by mikepenz** [comment]
@neokree i know this library is similar to my library. But i think it is always good to help each other. The issue you have here is because as soon as you have the FullScreen flag (which is required to get the Drawer below the StatusBar) the adjustResize feature won't work anymore. (Starting with API Level 19)

I have created a small util to get it working in my MaterialDrawer library. You can find an answer about this here: http://stackoverflow.com/a/30019136/325479

**Comment by PaoloRotolo** [comment]
Great, I knew it was something related to Fullscreen activities. :)

**Comment by mindrunner** [comment]
Same problem here. What exactly solves it? I have a LinearLayout inside of a Scrollview. 
Also I set `android:windowSoftInputMode="adjustPan"` in Manifest. Still, the Keyboard overlays parts of my view.

**Comment by mikepenz** [comment]
@mindrunner do you have the `KeyboardUtil` enabled?

**Comment by mindrunner** [comment]
@mikepenz  Don't really know. Must have a look at the code first. I am not actively maintaining it at the moment. Can you quickly point me to KeyboartUtil? How to activate it?

**Comment by mikepenz** [comment]
@mindrunner oops sorry ignore my comment. I was notified and thought it was an issue on my drawer lib. sorry
