### ISSUE TITLE
Set custom font in Toolbar

### ISSUE THREAD

**Issue by aimanbaharum** [neokree/MaterialNavigationDrawer#228]
Is there a way I can override setTypeface during init() and change the Toolbar's font whenever a section (fragment) is clicked? I want to do this globally. I believe the toolbar is inherited by the extended ActionBarActivity, so there must be a way to set this from init().

**Comment by neokree** [comment]
check the [FAQ](https://github.com/neokree/MaterialNavigationDrawer/wiki/FAQ#how-can-i-get-my-action-bar--toolbar)
