### ISSUE TITLE
Make my NavigationDrawer class MainActivity

### ISSUE THREAD

**Issue by pearlismylove** [neokree/MaterialNavigationDrawer#229]
Hi.

First of all, thank you very much for the library. :)

And I'm not sure if this question has been asked..

but could you please let me know how to make my own NavigationDrawer class extending MaterialNavigationDrawer as MainActivity?

Right now, I call my NavigationDrawer class by using Intent when MainActivity called.

But in this way, when I click the back button, I see the screen of MainActivity

How can I avoid that?

**Comment by aimanbaharum** [comment]
Declare it in your manifest to be the main activity

**Comment by neokree** [comment]
@pearlismylove 
in your AndroidManifest.xml
```xml
<activity
    android:name=".MainActivity"
    android:label="@string/app_name" >
    <intent-filter>
        <action android:name="android.intent.action.MAIN" />

        <category android:name="android.intent.category.LAUNCHER" />
    </intent-filter>

</activity>
```
Where the MainActivity is your activity. 

However, this is not related to the library, so please don't open issue there, check on stackoverflow or other similar sites. Thank you
