### ISSUE TITLE
ActionBar/Toolbar menu items not displayed with Multipane support

### ISSUE THREAD

**Issue by filipebezerra** [neokree/MaterialNavigationDrawer#230]
Hi folks, I have trying to use this awesome library but I've been found some issues, in this particularly issue I'm using the functionalities Multipane with theme MaterialNavigationDrawerTheme.Light.DarkActionBar.TranslucentKitKatStatusBar, actually my theme is:

```xml
<style name="Theme.App" parent="MaterialNavigationDrawerTheme.Light.DarkActionBar.TranslucentKitKatStatusBar">
        <item name="colorPrimary">@color/theme_color_primary</item>
        <item name="colorPrimaryDark">@color/theme_color_primary_dark</item>
        <item name="colorAccent">@color/theme_color_accent</item>
        <item name="drawerType">@integer/DRAWERTYPE_IMAGE</item>
        <item name="rippleBackport">true</item>
        <item name="multipaneSupport">true</item>
        <item name="sectionStyle">@style/ThemeSection</item>
</style>
```

But when launching the app in a large screen devices such as tablets the ActionBar menu items is not being displayed. So how I can fix this?

**Comment by neokree** [comment]
It is actually a bug, I already fixed that in 1.3.3 alpha build 4 avariable on github
