### ISSUE TITLE
Remove toolbar from Activity

### ISSUE THREAD

**Issue by kushalsharma** [neokree/MaterialNavigationDrawer#232]
I want to remove the toolbar from the activity as fragments attached to activity have there own toolbars. Is it possible? if yes how? Could not find any sample about it! Thank you neokree for this lib, its great ! ^.^

**Comment by neokree** [comment]
Actually there isn't a way to remove toolbar from the activity, and sincerily, It doesn't make sense. 
Why do you want a navigation drawer without a toolbar? How an insesperienced user can open the drawer if they don't know the swipe gesture?

**Comment by kushalsharma** [comment]
agree, but i need to have custom toolbar for each fragment(like with movoing images and spinners on one fragment but another one is simple etc). If you can suggest me a way out? 
for now i am hiding the toolbar by marking its visibilty to "gone" and pushing the framelayout with layout_below="statusBar"
Now with my toolbar in fragment is there a way to callback open navigation drawer by clicking a button(say drawer icon on toobar that is inside my fragment)?  So that an insesperienced user can open the drawer from inside the fragment and not the activity.
![device-2015-03-13-143645](https://cloud.githubusercontent.com/assets/6106389/6635685/a2ea256e-c98e-11e4-9e61-6e30e610a8a3.png)

**Comment by mrcasals** [comment]
Put those fragments in other activities and link to those new activities from the Drawer instead of linking to the Fragments. This way you can customize the toolbar without having to hide the Drawer one. Do not make those new activities inherit from `MaterialNavigationDrawer`.

**Comment by kushalsharma** [comment]
@mrcasals thanks man ! I was not aware that i can pass an activity insted of fragment to selector! I will try that out today, and close this issue when its done. Great work guys with the lib again! i am new to android and i so much wish to contribute to community like you guys do. I will also make a lib soon :D thanks for the inspiration as well @neokree

**Comment by kushalsharma** [comment]
@mrcasals i did as you suggested, it seems to be a good workaround. But i think more appropriate solution will be to have a callback from fragment to open drawr (as i lose navigation i.e the drawer if i start new activity the way you suggested and i want to keep the navigation at all times)
