### ISSUE TITLE
Closing drawer in tablets when multipaneSupport is true

### ISSUE THREAD

**Issue by filipebezerra** [neokree/MaterialNavigationDrawer#233]
Library version: 1.3.3 alpha build 4
Devices:
* Google Nexus 9 - Lollipop
* Google Nexus 10 - Lollipop
* Sony Xperia Tablet Z - 4.2.2

When I tap once in a section and after selected I tap twice the same section then drawer closes.

I check in the code and I think is here the bug

    public void onClick(MaterialSection section) {
        switch (section.getTarget()) {
            case MaterialSection.TARGET_FRAGMENT:
                // se l'utente clicca sulla stessa schermata in cui si trova si chiude il drawer e basta
                if(section == currentSection) {
                    layout.closeDrawer(drawer);
                    return;
                }
                ...
    }

Lack the validation: `if (!deviceSupportMultiPane())`

**Comment by neokree** [comment]
Thank you for your bug fix

**Comment by filipebezerra** [comment]
You're welcome friend, nice it' s a pleasure to contribute.

**Comment by josefigueredo** [comment]
I did implement your fix and it works great. However when I test it in a tablet that returns true for deviceSupportMultiPane in landscape but false in portrait, the portrait version become unpractical. So I wrote a custom onConfigurationChanged() based on the onCreate() code to change between layouts.

By the way excelent library neokree !!
