### ISSUE TITLE
TextColor has already been defined ERROR

### ISSUE THREAD

**Issue by Sorush-moradisani** [neokree/MaterialNavigationDrawer#234]
I'm using it.neokree:MaterialTabs:0.11 and it.neokree:MaterialNavigationDrawer:1.3.2 in my app but when I start syncing gradle it gives me a strange error! 

    Error:Attribute "textColor" has already been defined
    Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
	F:\Digital Science\Android\Developer Softwares\Android Studio\SDK\build-tools\21.1.2\aapt.exe package -f --no-crunch -I F:\Digital Science\Android\Developer Softwares\Android Studio\SDK\platforms\android-21\android.jar -M F:\Digital Science\Android\Unfinished Projects\Android Studio Projects\Workplace\FarhangiGolestan\app\build\intermediates\manifests\full\debug\AndroidManifest.xml -S F:\Digital Science\Android\Unfinished Projects\Android Studio Projects\Workplace\FarhangiGolestan\app\build\intermediates\res\debug -A F:\Digital Science\Android\Unfinished Projects\Android Studio Projects\Workplace\FarhangiGolestan\app\build\intermediates\assets\debug -m -J F:\Digital Science\Android\Unfinished Projects\Android Studio Projects\Workplace\FarhangiGolestan\app\build\generated\source\r\debug -F F:\Digital Science\Android\Unfinished Projects\Android Studio Projects\Workplace\FarhangiGolestan\app\build\intermediates\res\resources-debug.ap_ --debug-mode --custom-package com.example.sorush.farhangigolestan -0 apk --output-text-symbols F:\Digital Science\Android\Unfinished Projects\Android Studio Projects\Workplace\FarhangiGolestan\app\build\intermediates\symbols\debug
Error Code:
	1
Output:
	F:\Digital Science\Android\Unfinished Projects\Android Studio Projects\Workplace\FarhangiGolestan\app\build\intermediates\res\debug\values\values.xml:127: error: Attribute "textColor" has already been defined
![pro](https://cloud.githubusercontent.com/assets/9649165/6618386/b870da52-c8d7-11e4-8eef-04536b0233c3.PNG)

and it opens an xml file from library

**Comment by neokree** [comment]
You are using another library that have textColor attribute

**Comment by Sorush-moradisani** [comment]
So is there any solutions?

**Comment by neokree** [comment]
You should check what library have the same attribute and you must choose what library use. You cannot have two attribute in different package on the same project due to android limitation.
