### ISSUE TITLE
where is the Layout of class which extends from MaterialNavigationDrawer

### ISSUE THREAD

**Issue by nguyentando** [neokree/MaterialNavigationDrawer#235]
Hi, I'm a newbie in Android.
I have a little question. 
I created a class which extends from MaterialNavigationDrawer to use like a base Activity in my entire application. Any subclass of this Base Activity will have a Navigation Drawer automatically.

Where is the layout of class MaterialNavigationDrawer, or Base Activity?

**Comment by neokree** [comment]
This library implements the base layout for the navigation drawer activity.
