### ISSUE TITLE
Navigation Icon on the Toolbar!

### ISSUE THREAD

**Issue by nguyentando** [neokree/MaterialNavigationDrawer#236]
How can I change the navigation icon (the icon on which we touch to open the Navigation Drawer) on the Toolbar?

**Comment by neokree** [comment]
Why you want to change it?

**Comment by romanzes** [comment]
@neokree because the default icon may be barely visible on certain ActionBar color, because the designer or client may ask the developer to change it. There could be many reasons. That option definitely should exist.

**Comment by nguyentando** [comment]
Right! Finally, I can change the color of this now :)

**Comment by romanzes** [comment]
@nguyentando Tell us please, how to do it

**Comment by romanzes** [comment]
Okay, if someone else need it, this works:
```
@Override
protected void onPostCreate(Bundle savedInstanceState) {
    super.onPostCreate(savedInstanceState);
    getToolbar().setNavigationIcon(R.drawable.ic_drawer);
}
```
