### ISSUE TITLE
ActionBar doesn't have any shadows

### ISSUE THREAD

**Issue by dotWee** [neokree/MaterialNavigationDrawer#237]
Especially with viewPagers and tabStrips.
Native:

![Native](https://dl.pushbulletusercontent.com/eXXvLu7SIRFB28RKgaTs7h3eT8KND1To/Screenshot_2015-03-15-19-25-30~01.png)

With MaterialNavigationDrawer:

![MaterialNavigationDrawer](https://dl.pushbulletusercontent.com/ls0FZkMEllDo5ogr12ezUZTGyOnPca5q/Screenshot_2015-03-15-19-25-22~01.png)

**Comment by greenog** [comment]
I'm using it with apis <21 and can't add a shadow to the toolbar... :(

**Comment by neokree** [comment]
I will add this feature in next releases

**Comment by romanzes** [comment]
I found a temporarily fix for it: you can add this line to activity theme:
<item name="android:windowContentOverlay">@drawable/actionbar_shadow</item>
I've attached an image which should be placed in drawable folder. But this has the side effect: you'll get the same horizontal shadow on top of your ActionBar, not only below it (with Lollipop this shadow will be on top of status bar). I'll try to make a pull request later to fix it in a more proper way.
![actionbar_shadow 9](https://cloud.githubusercontent.com/assets/5735967/6781184/c6a6b760-d17c-11e4-8e93-75cb33145b90.png)

**Comment by neokree** [comment]
check the [wiki](https://github.com/neokree/MaterialNavigationDrawer/wiki/Functionalities#enable-action-bar-shadow--toolbar-elevation) please.

**Comment by luxsypher** [comment]
Tried both : 
 ```<item name="toolbarElevation">true</item> ```

and 
 ```enableToolbarElevation(); ```

none of them are working 
![screenshot](http://img11.hostingpics.net/pics/513241unnamed.png)

**Comment by nhojyer07** [comment]
The shadow should be below the tabs, not between them so the 2nd image is better.

**Comment by PaoloRotolo** [comment]
Doesn't work for me too...
