### ISSUE TITLE
Collapse searchview on back pressed

### ISSUE THREAD

**Issue by Bernix01** [neokree/MaterialNavigationDrawer#238]
Great job with this library! Very useful!
Is there a way to do this without any mess?

**Comment by neokree** [comment]
I sincerily don't know how it works, could you tell me something about that? 

I think that you should use a custom back pattern and close the searchview if it is open.

**Comment by Bernix01** [comment]
It's like when you are in the google play store and you open the seachview and then you press the back button and the searchview get closed.
I was thinking about that cause it's the general solution, but it says "you must not override onBackPressed method, because the library implement it on its own".

**Comment by neokree** [comment]
yes, Library use onBackPressed for imlement the back pattern.
Check the [wiki](https://github.com/neokree/MaterialNavigationDrawer/wiki/Functionalities#back-pattern)

**Comment by Bernix01** [comment]
got it! Feel free to close this issue

**Comment by Bernix01** [comment]
Plus, can you add some feature to add the scrimm to the drawer header background?

**Comment by neokree** [comment]
sorry, could you explain the word 'scrimm' ?

**Comment by Bernix01** [comment]
my fault, scrim*

**Comment by neokree** [comment]
Well, I think that is better to keep the scrim external to this activity. You can apply it using another library or make your own scrimmer.
