### ISSUE TITLE
Set a custom background color for statusbar

### ISSUE THREAD

**Issue by mrcasals** [neokree/MaterialNavigationDrawer#242]
Hi!

The specs say the statusbar can be dark, translucent or a darker tone than the toolbar:

http://www.google.com/design/spec/layout/structure.html#structure-system-bars (under "System bars -> Color variants" section)

How can I change the statusbar color for my `MaterialNavigationDrawer` activity to a specific color?

I tried this snippet of code in my `onCreate` method:

```java
@Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Fabric.with(this, new Crashlytics());

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP){
            Window window = getWindow();
            window.addFlags(WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS);
            window.setStatusBarColor(Color.parseColor("#FFA000"));
        }
    }
```

But it's not working, the statusbar keeps being translucent. Any idea?

Thanks!

**Comment by mrcasals** [comment]
Oh, and my style is this one:

```xml
    <style name="MyTheme" parent="MaterialNavigationDrawerTheme.Light">
        <item name="colorPrimary">#ffc107</item>
        <item name="colorPrimaryDark">#ffa000</item>
        <item name="colorAccent">#009688</item>
        <item name="drawerType">@integer/DRAWERTYPE_IMAGE</item>
    </style>
```

**Comment by neokree** [comment]
use the `changeToolbarColor(colorToolbar,colorStatusbar)` method if you want to do programmatically.
Note that you can set the section color to a section instead of checking programmatically every time you change to a specific section. <br>
example: <br>
```java
section = newSection( ... );
// first color for toolbar, second for status bar. 
// if second is not setted, dark color is calculated.
section.setSectionColor(Color.parseColor("#9c27b0"), Color.parseColor("#9c27b0"));
```

**Comment by mrcasals** [comment]
Awesome, thanks!
