### ISSUE TITLE
Title Color

### ISSUE THREAD

**Issue by Morosko** [neokree/MaterialNavigationDrawer#243]
Hey 
I want to change the color of the title in my action, but I don't know how to do this..

**Comment by neokree** [comment]
check the [FAQ](https://github.com/neokree/MaterialNavigationDrawer/wiki/FAQ#how-can-i-get-my-action-bar--toolbar) before posting issue please

**Comment by Morosko** [comment]
I did! But there's only how to change background color but not *title* color..

**Comment by neokree** [comment]
The first FAQ tells you how to get the action bar and the toolbar. From toolbar you can set programmatically its title color.
