### ISSUE TITLE
How can I customize the toolbar XML?

### ISSUE THREAD

**Issue by yhack** [neokree/MaterialNavigationDrawer#249]
One of the great things about the Android toolbar is that it is more customizable than the ActionBar. I haven't found a direct way to change the XML with this library. For example, I want to [add a spinner dropdown](http://stackoverflow.com/a/26511653/3211023) to the toolbar and change the hamburger icon to an up arrow for some fragments.

The best solution I've come up with is to set the toolbar's visibility to GONE and make my own. I'm not sure if this will cause other integration problems.

What's the best way to customize the toolbar XML?

p.s. Thanks for the great library :)

**Comment by antde** [comment]
i'm also curious of the best practice recommended for this

**Comment by Kinnonii** [comment]
I'm interested on this, too. Same case, I want to add a Spinner that mimics material specs.

**Comment by Kinnonii** [comment]
Done it, but I need to do some other tricks to fix colors. Added the spinner following (this post)[https://blog.danielbetts.net/2015/01/02/material-design-spinner-toolbar-style-fix/]
Just note that on the "Adding spinner to your toolbar" you should use getToolbar() in place of 'toolbar' or ((MaterialNavigationDrawer) getActivity()).getToolbar() if you're inside a fragment.

**Comment by Kinnonii** [comment]
Fixed. It was almost illegible text on dark background, just added android:background="#FFFFFF" and changed android:textColor to #87000000 on the TextView inside toolbar_text_spinner_dropdown.xml
