### ISSUE TITLE
1.3.3 No Accounts text is too high

### ISSUE THREAD

**Issue by HigHendHd** [neokree/MaterialNavigationDrawer#252]
Hi,

If you choose to not use an account section in 1.3.3, the first section is too high (it leaks into the statusbar). 1.3.2 didn't have this issue.

**Comment by neokree** [comment]
android version tested?

**Comment by HigHendHd** [comment]
Ah sorry, forgot to write it. Tested on Android 5.0 on Nexus 4 and Genymotion Nexus 6 AVD.

It looks like this in 1.3.3:

![device-2015-03-27-094557](https://cloud.githubusercontent.com/assets/10761037/6864804/86a2fd3a-d466-11e4-9f33-5f4af67267df.png)

But in 1.3.2 it worked like it was supposed to:

![device-2015-03-27-094755](https://cloud.githubusercontent.com/assets/10761037/6864827/c3aca294-d466-11e4-8fb9-75c46b01d42c.png)
