### ISSUE TITLE
ActionBar/Toolbar menu items displaying twice

### ISSUE THREAD

**Issue by filipebezerra** [neokree/MaterialNavigationDrawer#254]
* Library version: 1.3.3
* Devices tested:
  * Google Galaxy Nexus | Android 4.3 | Genymotion Emulator
  * Google Nexus 4 | Android 5.0.0 | Genymotion Emulator
  * Google Nexus 5 | Android 5.0.0 | Genymotion Emulator
  * Google Nexus 5 | Android 4.4.4 | Genymotion Emulator
  * Google Nexus 7 | Android 5,0,0 | Genymotion Emulator
  * Google Nexus 7 | Android 4.3 | Genymotion Emulator
  * LG Optimus L3 II | Android 4.1.1 | Genymotion Emulator
  * Motorola Moto X | Android 4.4.4 | Genymotion Emulator
  * Samsung Galaxy S3 Slim | Android 4.2.2 | Real device
  * Samsung Galaxy S5 | Android 4.4,4 | Genymotion Emulator
  * Sony Xperia Tablet Z | Android 4.2.2 | Genymotion Emulator
* Related APIs:
  * com.android.support:appcompat-v7:22.0.0
  * com.google.android.gms:play-services-location:7.0.0
  * com.nispok:snackbar:2.10.6
  * com.jakewharton.timber:timber:2.7.1
  * com.android.support:recyclerview-v7:22.0.0
  * com.jakewharton:butterknife:6.1.0
* When testing with the devices below, this issue don't occurs.
  * Google Nexus 9 | Android 5.0.0 | Genymotion Emulator
  * Google Nexus 10 | Android 4.4.4 | Genymotion Emulator
  * Google Nexus 6 | Preview Android 5.1.0 | Genymotion Emulator

This is the menu.xml file:
```
<menu xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:support="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    tools:context=".DrawerMainActivity"
    >
    <item
        android:id="@+id/action_search"
        android:title="@string/action_search"
        android:icon="@mipmap/ic_search"
        android:orderInCategory="1"
        support:showAsAction="collapseActionView|always"
        support:actionViewClass="android.support.v7.widget.SearchView"
        />

    <item
        android:id="@+id/action_my_location"
        android:title="@string/action_my_location"
        android:icon="@mipmap/ic_my_location"
        android:orderInCategory="2"
        support:showAsAction="ifRoom"
        />
</menu>
```

When the menu softkey is pressed, the action items inflated into ActionBar are displayed as popup menu as shown in the image below.

* Samsung Galaxy S3 Slim
![device-2015-03-28-140500](https://cloud.githubusercontent.com/assets/1006095/6882084/91e896ee-d558-11e4-9ce9-802281bb34cc.png)
* Sony Xperia Tablet Z
![sony xperia tablet z](https://cloud.githubusercontent.com/assets/1006095/6882235/b4035ce2-d55c-11e4-9fc3-0b26318e5710.png)

__In almost devices tested after open the drawer few times this behavior don't occurs, except:__
  * Samsung Galaxy S3 Slim | Android 4.2.2 | Real device
  * Sony Xperia Tablet Z | Android 4.2.2 | Genymotion Emulator

**Comment by bmsgarces** [comment]
This is also happening to me. How can I solve it?

**Comment by mikepenz** [comment]
@filipebezerra @bmsgarces what are you doing to get this issue? i never had this one or i never saw this one?

I assume it could be related to the android appcompat library. I do not do anything with the menu. so i'm sure this is not related to the MaterialDrawer
