### ISSUE TITLE
open navigation drawer page from another page.

### ISSUE THREAD

**Issue by renjithkrish89** [neokree/MaterialNavigationDrawer#257]
I have 4 sessions in navigation drawer in my app. In first fragment i hav a button. When I clicked on this button I want to load the last page of the navigation drawer. How can i do that

**Comment by niketkadde** [comment]
I am also searching for this solution

**Comment by niketkadde** [comment]
@renjithkrish89  I got the solution.
we can use MaterialNavigationDrawer's setSection(.) method for this

**Comment by renjithkrish89** [comment]
@niketkadde it only set the selection in navigation drawer not loading the fragment of corresponding
