### ISSUE TITLE
Set the text size of sections in slide menu

### ISSUE THREAD

**Issue by icsd** [neokree/MaterialNavigationDrawer#258]
Hi,
how can i set the text size of the sections of the slide menu?

Thank you in advance!

**Comment by icsd** [comment]
I changed the textSize attribute of the TextView with id: "section_text", which is in the layout_material_section.xml , but in this way, only the first Section changes textSize. The below sections' textSize is not changed. How can i apply this change to all sections?

**Comment by Sharj** [comment]
@+id/section_text has font size 14sp defined in layout file. It would be nice to change it using style like changing text color right now.
