### ISSUE TITLE
Multiple Sections selected with 1.3.3

### ISSUE THREAD

**Issue by rubengees** [neokree/MaterialNavigationDrawer#259]
![unbenannt](https://cloud.githubusercontent.com/assets/8021265/6944833/36ed7c1e-d896-11e4-9354-1b785999424d.png)
This happens with the new version 1.3.3 only. 
"Statistics" is a normal section and "Settings" is a bottom section.
Device: API 22 emulator

**Comment by jmvines** [comment]
+1

**Comment by tonilopezmr** [comment]
+1

**Comment by RubyDerBoss** [comment]
Great, thank you! I hope this is accepted soon. I want to publish and I was waiting just for a this bugfix.

**Comment by Sharj** [comment]
There's another bug which I guess is related to this. When try to change section by calling setSection(someSection); It just Multiple selects Sections and doesn't load changed section.

**Comment by tonilopezmr** [comment]
setSection() not found in 1.3.3
