### ISSUE TITLE
BackButton troubles

### ISSUE THREAD

**Issue by Sinokos** [neokree/MaterialNavigationDrawer#260]
When i press btn Back and Drawer is open, i throws to previos activity instead of just close Drawer.

It's happend jsut when i use ListFragment or Fragment with layout, if i used just empty Fragment it's work correctly.

Can help me someone>?

**Comment by filipebezerra** [comment]
Override the ```backToSection()``` method:
```
@Override
protected MaterialSection backToSection(final MaterialSection currentSection) {
...
Your implementation goes here
...
}
```
