### ISSUE TITLE
Android Lint throws "Unchecked Call"

### ISSUE THREAD

**Issue by rubengees** [neokree/MaterialNavigationDrawer#261]
When I analyze my code with the Android Lint tools I get the following issues: "Unchecked call to 'newSection(String, int, Fragment)' as a member of raw type 'it.neokree.materialnavigationdrawer.MaterialNavigationDrawer' "

I'm sorry if this is basic java knowledge, but I don't know how to fix it and would be grateful if you could help me.

This is how I declare a new section:
```java
MaterialSection settings = newSection(getString(R.string.section_title_settings), R.drawable.ic_settings, new SettingsFragment()).setSectionColor(color, colorDark);
```

**Comment by filipebezerra** [comment]
You can just ignore that in lint.xml

**Comment by RubyDerBoss** [comment]
Yes of course, but it's not the best practice I suppose.

**Comment by filipebezerra** [comment]
There's no other way, because as you can see, ```MaterialSection``` must receive a ```Fragment``` as a Type parameter, and in this helper methods instantiates a raw type.
