### ISSUE TITLE
Please fix opening or closing Drawer in onClick(), openDrawer() and closeDrawer()

### ISSUE THREAD

**Issue by filipebezerra** [neokree/MaterialNavigationDrawer#263]
* LIbrary version: 1.3.3
* Related APIs:
  * com.android.support:appcompat-v7:22.0.0
  * com.google.android.gms:play-services-location:7.0.0
  * com.nispok:snackbar:2.10.6
  * com.jakewharton.timber:timber:2.7.1
  * com.android.support:recyclerview-v7:22.0.0
  * com.jakewharton:butterknife:6.1.0
* Devices tested: Anyone

I already figure out this bug in early version and it's not fixed. In the callback ```onClick()``` when clicking twice in the same section, on multi-pane devices the Drawer closes.

Another public feature that it's supposed to do correctly, is the methods ```openDrawer()``` and ```closeDrawer()``` which don't checks ```deviceSupportMultiPane()```.

**Comment by artemkutukov** [comment]
Im have this bugs from tabls too. Please fix that.
