### ISSUE TITLE
is there any on navigation drawer section click listener ?

### ISSUE THREAD

**Issue by arafeh94** [neokree/MaterialNavigationDrawer#267]
addSection(newSection("Home",R.drawable.home,new Home()));

when this section click i want to make something more than open the fragment how to it 
thanks in advance.

**Comment by RubyDerBoss** [comment]
I know this is not exactly what you want, but you could do what you want in the onCreate method of your fragment Home. If you want to do something in your Activity, you could do that with something like
```java
((YourActivity)this.getActivity()).doSomething();
```

**Comment by yolapop** [comment]
Read on [Section](https://github.com/neokree/MaterialNavigationDrawer/wiki/Sections). You can set your own listener.
