### ISSUE TITLE
Is there any way to get control of the backstack?

### ISSUE THREAD

**Issue by yolapop** [neokree/MaterialNavigationDrawer#268]
Imagine that I have these fragments.

    Section -> Child fragment 1 -> Child fragment 2 -> Child fragment 3

Now, using your library, I can only get back in the reverse order `Child fragment 3 -> Child fragment 2` ... and so on.
How can I go back from `Child fragment 3` to `Section` and destroy `Child fragment 2` and `Child fragment 1`?

**Comment by filipebezerra** [comment]
You can write your custom backpattern with ```setBackPattern(MaterialNavigationDrawer.BACKPATTERN_CUSTOM)```.

So now you can write something like that:
```
@Override
protected MaterialSection backToSection(final MaterialSection currentSection) {
...
Your implementation goes here
...
}
```
