### ISSUE TITLE
Feature: Account background color

### ISSUE THREAD

**Issue by Brian-McBride** [neokree/MaterialNavigationDrawer#273]
I might not always want to use a background image. 

Maybe it already exists, but I'd love to see where you set the background color of the account screen.

**Comment by javmarina** [comment]
What you can do is:
- Use <item name="drawerType">@integer/DRAWERTYPE_IMAGE</item>
- Programatically, create a new ColorDrawable (in your init() method)
ColorDrawable drawable = new ColorDrawable(Color.parseColor("#RRGGBB")); // your color
- Convert that drawable to a bitmap (see http://stackoverflow.com/questions/3035692/how-to-convert-a-drawable-to-a-bitmap)

private Bitmap drawableToBitmap (Drawable drawable) {
    Bitmap bitmap = Bitmap.createBitmap(drawable.getIntrinsicWidth(), drawable.getIntrinsicHeight(), Config.ARGB_8888);
    Canvas canvas = new Canvas(bitmap); 
    drawable.setBounds(0, 0, canvas.getWidth(), canvas.getHeight());
    drawable.draw(canvas);
    return bitmap;
}

- Then use setDrawerHeaderImage(drawabletoBitmap(drawable));

Tell me if it works.

**Comment by Anatidae-Project** [comment]
Ill give that a try. I was thinking.how nice it would be to use font icons for the section icons. This could be one path. Although having the choice just to set a character, and font styling for a section would be lightweight. 

I'm a big fan of font icons over maintaining dozens of images.
