### ISSUE TITLE
Account Photo Size

### ISSUE THREAD

**Issue by MuhammadShaker** [neokree/MaterialNavigationDrawer#276]
I wonder how to change account photo size, it looks small
![screenshot_2015-04-19-20-19-14](https://cloud.githubusercontent.com/assets/10682377/7220494/853e8248-e6d1-11e4-8015-a0c2af42cca1.png)

**Comment by gvsharma** [comment]
Any idea on this....similar position

**Comment by TheIcemanCometh** [comment]
I would also like to be able to change the header dimensions.  Compared to other apps that have Material Design and a nav drawer, this one is quite a bit taller and wider than what seems to be the "standard".
