### ISSUE TITLE
Is this library maintained any longer?

### ISSUE THREAD

**Issue by jmvines** [neokree/MaterialNavigationDrawer#278]
@neokree I would like to know if this library is actively maintained any longer. There are many unanswered issues.

Thanks for your effort.

**Comment by TheIcemanCometh** [comment]
I would like to know this as well.  It seems to be a nice little library, and I have some questions I'd like to ask and feature updates to suggest, but if it's not being maintained, I'll move on to another library.

**Comment by StefanFaulhaber** [comment]
I would like to know this as well. The last commit was pushed nearly 2 months ago.

I would like to have a statement from @neokree because I have to decide if I use this any longer.

**Comment by antde** [comment]
I recommend to you guys to switch to another maintained library as https://github.com/mikepenz/MaterialDrawer

**Comment by StefanFaulhaber** [comment]
Thanks for the hint, looks good!

**Comment by TheIcemanCometh** [comment]
Thanks for the link, @antde.  I've been tinkering with MaterialDrawer for about 30 minutes now and I think I'll be switching over to it.  With something that's as integral to an app as its menu, I need something that does what I need it do, **and** is maintained.

**Comment by pranaysharma** [comment]
Thanks @antde  for the tip. And @TheIcemanCometh : Any opinion on the MaterialDrawer library?
Thanks

**Comment by TheIcemanCometh** [comment]
@pranaysharma So far, MaterialDrawer is doing what I need it to do.  I have a header image in my menu that I need to figure out how to lay text over, but I haven't figured out how to do that yet.  But again, so far so good overall.

**Comment by pranaysharma** [comment]
Thanks for your reply
