### ISSUE TITLE
Selection Alpha

### ISSUE THREAD

**Issue by Brian-McBride** [neokree/MaterialNavigationDrawer#280]
I am noticing that on this 4.4.4 devices I'm testing on the selection alpha values are not changing as expected.

The menu text stays 1f alpha and the icon seems to stay 0.54f.

The bar that rests behind the currently selected item is highlighted however.

**Comment by nhojyer07** [comment]
It's the current behavior of the library when you don't use setSectionColor(). I hope someone makes a pull request for this.
