### ISSUE TITLE
Selected fragment state is lost on rotation in master-child case

### ISSUE THREAD

**Issue by Zhuinden** [neokree/MaterialNavigationDrawer#284]
The displayed fragment remains the correct fragment, but when using BackPattern `BACKPATTERN_BACK_TO_FIRST` (and possibly other back patterns too), if you rotate the device, then the drawer forgets its "backstack" and shows Drawer button instead of Up, and also pressing Back button closes app.

This is in case of MASTER-CHILD example. The Child Fragment Stack is **not preserved upon orientation change**.

**Comment by BackPackerDz** [comment]
Hi, I have the same issue, any solution ?

**Comment by Zhuinden** [comment]
The variables that would need to be preserved in onSaveInstanceState() are private, therefore I did not bother with coming up with a fix myself.

**Comment by Foivos-Stamopoulos** [comment]
@Zhuinden Could you give an example? Do you handle the back stack some way?

**Comment by Zhuinden** [comment]
It's been ages since I tried this, I've just implemented my own stuff since and my own backstack / state persistence lib.
