### ISSUE TITLE
PreferenceFragment appears in front of the last Fragment

### ISSUE THREAD

**Issue by elysrivero99** [neokree/MaterialNavigationDrawer#288]
When a chose the preference fragment the last fragment doesn't disappears:

My PreferenceFragment code:

public class SettingsFragment extends PreferenceFragment {
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
       addPreferencesFromResource(R.xml.pref_general);
        return super.onCreateView(inflater, container, savedInstanceState);
    }
}

![image](https://cloud.githubusercontent.com/assets/3760276/7449739/d47d91ba-f201-11e4-9f4b-45b015032b2c.png)

**Comment by elysrivero99** [comment]
The solution: Don't use android.support.v4.app.Fragment.

**Comment by carterh062** [comment]
+1
