### ISSUE TITLE
Bottom section pinning

### ISSUE THREAD

**Issue by mkosik** [neokree/MaterialNavigationDrawer#29]
According to material design specification:
http://www.google.com/design/spec/patterns/navigation-drawer.html
there is no such thing as a bottom pinned section.

From the spec:
"Settings and support are located at the bottom of the scrolling list, in-line with the rest of the list content."
Inline = following the last items in drawer, not pinned to the bottom - see Google apps.

From the specification - if the list of items in drawer is short:
"If the list doesn’t scroll, the settings and support items will appear at the end of the list and are not pinned."

But it might be OPTIONALY pinned, if a list of items is very long, from the spec:
"If the list of content in the navigation drawer is very long, the two options can be pinned to the bottom of the navigation drawer on a surface with a higher elevation. This surface is present only while at the top of the list; any other scroll position will immediately result in dismissing the surface and placing the options at the end of the list, in-line with the rest of the list content. The navigation drawer retains its scroll position when closed and reopened."

So pinning to bottom is OPTIONAL only in case of so many items that scrolling is enabled (but not even Google apps does that). Moreover, in this very specific OPTIONAL scenario, it should appear pinned only when not scrolled, and dissappear while scrolling.

**Comment by mkosik** [comment]
Hi @neokree. Thx for adding this, but the default behaviour should be no pinning at all - pinning is only OPTIONAL if list is too long & only when not scrolled, as mentioned in specs you provided a link in wiki.
Suggested changes:
- no pinning at all by def
- method to enable pinning with current behaviour
Please, re-open the issue.

**Comment by prashantwosti** [comment]
its actually not working for me like i want. 
Here's my scenario:
I have 13 items in the drawer. Last item is set as "addBottomSection". If I set 1 account with expand collapse enabled, last item only gets pinned after toggling expand/collapse.

and also don't know why there's a line in the end.
