### ISSUE TITLE
gradle error!

### ISSUE THREAD

**Issue by TheLoyalCruel** [neokree/MaterialNavigationDrawer#292]
how to import and use it in android studio?

**Comment by filipedelimabrito** [comment]
Hi @TheLoyalCruel, I had problems to use this lib in Android Studio too (specifically: “Error:Configuration with name 'default' not found.”).
Happily, I could solve this problem in this way:

 1- After cloned the repository, open Android Studio, click in “Import project (Eclipse ADT, Gradle, etc.)” and, in “Select Eclipse or Gladle Project to Import” window, navigate to “name of you project cloned”>MaterialNavigationDrawer, select build.gradle, then click “Ok”.
 
 2- In Android Studio, right click over MaterialNavigationDrawer and click in “Open Module Settings”.

 3- In Project Structure’s window, click in + (plus icon)>Import Existing Project(“Import existing Eclipse ADT or Gradle project as a module”)>Next.
 
 4- In “Source directory”, navigate to “name of you project cloned” and select “MaterialNavigationDrawerModule”, then click Ok. After, click in “Finish.
 
 5- Click Ok in Project Structure’s window and… voila!

I hope this answer helps you!

**Comment by susemi99** [comment]
Thank you @filipedelimabrito

**Comment by filipedelimabrito** [comment]
You're welcome @susemi99 :)

**Comment by luna3504** [comment]
You are a Hero

**Comment by filipedelimabrito** [comment]
Thanks @luna3504 :D

**Comment by luna3504** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

luna3504@naver.com 님께 보내신 메일 <Re: [MaterialNavigationDrawer] gradle error! (#292)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by RiadhRahmi** [comment]
thank you filipedelimabrito

**Comment by filipedelimabrito** [comment]
You're welcome @RiadhRahmi ! :) :)
