### ISSUE TITLE
With v7Lib v22.1.1 app:theme is now deprecated.

### ISSUE THREAD

**Issue by QFNU-JWK** [neokree/MaterialNavigationDrawer#293]
Since upgrade to appcompat-v7:22.1.1 

I/ViewUtils﹕ app:theme is now deprecated. Please move to using android:theme instead.

**Comment by jmvines** [comment]
I fear that this library is abandoned

**Comment by koesie10** [comment]
Where did you find app:theme? I can't find any reference to it in the source code.

**Comment by QFNU-JWK** [comment]
I don't look for the source code. I use maven and when I update the appcompat-v7 Lib to v22.1.1 ,the logcat show this info when my app is init......

**Comment by Anatidae-Project** [comment]
I had to bail on this and moved to:
https://github.com/mikepenz/MaterialDrawer

It's more work, but Mike is prolific about keeping the lib updated.

**Comment by CedricVandelaer** [comment]
This is a major issue, would be great if there was some workaround...
