### ISSUE TITLE
not find BackPatternCustom.class

### ISSUE THREAD

**Issue by hzy87email** [neokree/MaterialNavigationDrawer#295]
I not find BackPatternCustom.class, the MainActivity is not find intent = new Intent(this, BackPatternCustom.class) in 149 lines

**Comment by souwa** [comment]
me too.
how do you solve it?
"Error:(13, 38) error: cannot find symbol class BackPatternCustom"

**Comment by hzy87email** [comment]
@souwa  I removed this line of code.
