### ISSUE TITLE
Adding account from Fragment

### ISSUE THREAD

**Issue by phanghos** [neokree/MaterialNavigationDrawer#296]
I'm trying to add an account from a Fragment. What am I doing wrong? Am I missing something? I can do it from the main activity with no problem, but I need to do it from a Fragment. I'm using standard code:

    MaterialAccount account = new MaterialAccount(getResources(), "title", "subtitle", photo, background);
    context.addAccount(account);

This seems to be the Exception it throws, which did not help at all:

    java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable it.neokree.materialnavigationdrawer.elements.MaterialAccount.getCircularPhoto()' on a null object reference

**Comment by mmutuyu** [comment]
Same problem. doesn't have any clue :(
