### ISSUE TITLE
How to change Activity Theme dynamically?

### ISSUE THREAD

**Issue by HanderWei** [neokree/MaterialNavigationDrawer#305]
I can  use `setTheme` in `onCreate` method before `setContentView` to change the Activity theme.

But **MaterialNavigationDrawer**  can not override `onCreate` method.

Any help will be highly appreciated.

**Comment by paulomcnally** [comment]
On your fragment 1:

    MainActivity.setToolbarColors(R.color.color_primary, R.color.color_primary_dark);

On your fragment 2:

    MainActivity.setToolbarColors(R.color.color_primary_2, R.color.color_primary_dark_2);

On youre MainActivity:

    public static void setToolbarColors(int primaryColor, int primaryDarkColor) {
        toolbar.setBackgroundColor(mContext.getResources().getColor(primaryColor));
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            mWindow.addFlags(WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS);
            // set colorPrimaryDark
            mWindow.setStatusBarColor(mContext.getResources().getColor(primaryDarkColor));
        }
    }

**Comment by elratonmaton** [comment]
this doesn't work for me, the color is not changing.

a little more help ?
