### ISSUE TITLE
Project Unmaintained?

### ISSUE THREAD

**Issue by mindrunner** [neokree/MaterialNavigationDrawer#309]
It looks pretty much that this is full of bugs and no longer maintained. Who is actively using this? Who is satisfied? Also there are more than 300 forks of this project? Is there any more active version?

**Comment by Anatidae-Project** [comment]
Yeah. I moved to this:
https://github.com/mikepenz/MaterialDrawer

Mike is prolific about updates. There is a bit more setup and it doesn't quite have the built-ins, however the other side is that it is far more extensible.

**Comment by filipebezerra** [comment]
Why not using Android Design Library ?

http://android-developers.blogspot.com.br/2015/05/android-design-support-library.html

**Comment by Anatidae-Project** [comment]
The design library is great. Hands down. 

Mike's MaterialDrawer library offers a lot more features. I would not be surprised in the least if Mike utilizes the design lib as the base if the future if it makes sense. 

For me, my clients want sticky footers and custom headers that would require me to extend the design lib in such ways that I'd be replicating Mike's work. I love that Google is finally offering some great libs like this to get Material design more wide-spread though.

**Comment by mindrunner** [comment]
@Anatidae-Project Cool, thanks for pointing that out. I was thinking about doing the same. What is your experience of porting an App from MaterialNavigationDrawer to MaterialDrawer? 

@filipebezerra I think, that google just gives us the UI controls, but libs like MaterialNavigationDrawer or MaterialDrawer bring some functionality such as  handling fragments, accounts, etc. They should use the Android Design Library under the hood for sure. (If there are no reasons for not doing it).

I might be wring, but this is how I see the things here
