### ISSUE TITLE
How to make section icons bigger?

### ISSUE THREAD

**Issue by DKMudrechenko** [neokree/MaterialNavigationDrawer#313]
Hello there, I am using this awesome library in one of my apps and I would like to change size of section icons, how can I achieve this? Or could you point me to the list of all styling items that are used in the library?

Thanks

**Comment by merijnbrs** [comment]
I use the "Mikepenz Iconics" library. In this one you can define the size of the icons. So if you set a section you can say: this.addSection(newSection("your text..", new IconicsDrawable(this, FontAwesome.Icon.<an icon>).color(Color.WHITE).sizeDp(<the size you want>), <Your fragment>));
I hope this points you in the right direction!
