### ISSUE TITLE
back button support

### ISSUE THREAD

**Issue by yanivagman** [neokree/MaterialNavigationDrawer#33]
Hi,

First, I want to thank you for doing such a great work. This lib is great and helps a lot.
I encountered few issues when using back button,
Please take a look at the following if possible:
1. If I exit the app with back button, the next time I start the app causes a crash
2. Using back button will exit the app, instead of getting back to the previous screen (in google apps, the behavior is to get back to the main screen, then another "back" press leads to app exit)
3. Opening a new fragment from the drawer (like settings fragment), then hitting back, will cause us to get back to the previous screen as it should, however, the selected list item will still be settings, instead of the previous item selected.

One more small issue here, not related to back button, is RTL support. It will be nice to have this feature (explained at http://android-developers.blogspot.co.il/2013/03/native-rtl-support-in-android-42.html). Essentialy, there are two steps involved:
adding android:supportsRtl="true" to the <application> element in manifest file
and changing (or adding if min sdk is lower than 17) "start" instead of "left" and "end" instead of right.

Thanks again,
Yaniv

**Comment by neokree** [comment]
can I close the issue?

**Comment by yanivagman** [comment]
Sorry, but I won't be able to test the new version soon. Seems you did great work here though... Thanks!

**Comment by mkosik** [comment]
@neokree I'll try to test it this weekend, it seems like a suitable solution.

**Comment by vedhavyas** [comment]
i have tried the above mentioned code with BACK_TO_FIRST option
when i press back button, the first fragment is being loaded.
But there are two issues here:
1. First section is not highlighted and 
2. When i try and click any other section the click is not working. I have to close the drawer, tap somewhere and reopen the drawer to move to other section.

With CUSTOM_PATTERN, I was able to highlight the section by calling section.select() and return the section but the second issue still exist.

**Comment by neokree** [comment]
I have committed the 1.3 alpha version to github, that resolve the first problem, the second problem is related to another issue, that is in working progress there: #59

**Comment by vedhavyas** [comment]
Okay cool
Thanks bro

**Comment by sohayb** [comment]
Hello,
How can I force moveTaskToBackground(true) in backPressed rather than calling super.onBackPressed which kills the activity?
