### ISSUE TITLE
using KitKat translucent modes

### ISSUE THREAD

**Issue by captain-miao** [neokree/MaterialNavigationDrawer#330]
when using KitKat translucent modes，Use android:fitsSystemWindows="true"

but MaterialNavigationDrawer setting：android:fitsSystemWindows="false"

what can I do?

**Comment by martipello** [comment]
I was also looking to make the notification bar translucent for KitKat I think the best way is to add 24dp padding in dimen-v19

**Comment by captain-miao** [comment]
@martipello it works. Great.
