### ISSUE TITLE
Retrive parent fragments 

### ISSUE THREAD

**Issue by fadaeian** [neokree/MaterialNavigationDrawer#333]
hello
there is bug when i am in child fragment then press my phone home button, my app go to on pause after while os kill parent activity ,on restore just child fragment retrive and parent fragments gone??!
how can i fix it ?

**Comment by neokree** [comment]
Hello, 
The current last version of this libray is not supported anymore. 
I'm working on a new major release starting from scratch. 
I suggest you to download and import the module from this repository and then debug the code.
