### ISSUE TITLE
Learning pattern

### ISSUE THREAD

**Issue by mkosik** [neokree/MaterialNavigationDrawer#36]
There is a learning pattern associated with the nav drawer nature, as it is something people don't see (and some don't know it's there) until it's open. Basically what Google recommends is to open the nav drawer when starting your app everytime until user himself / herself firstly tap / swipe to open the drawer = they finally got it how it works and that it's there. It seems like pretty obvious to us, but there are some users that must be taught to do that (unfortunatelly).

If you generate a new project in Android Studio with a drawer pattern, it is already implemented there, so check it out - just one SharedPref variable, that's it ;)

**Comment by neokree** [comment]
ok so I will check what code are used with sample project.

**Comment by neokree** [comment]
In the sample code the drawer will open when the instance state is null and the user has not learned the drawer
```java

        // If the user hasn't 'learned' about the drawer, open it to introduce them to the drawer,
        // per the navigation drawer design guidelines.
        if (!mUserLearnedDrawer && !mFromSavedInstanceState) {
            mDrawerLayout.openDrawer(mFragmentContainerView);
        }

```
So my code is an exactly reproduction, but I use a static variable instead passing it through a bundle.
