### ISSUE TITLE
Hiding OptionsMenu (icons) when the drawer is opened

### ISSUE THREAD

**Issue by mkosik** [neokree/MaterialNavigationDrawer#37]
OptionsMenu should be hidden (gone) when the drawer is opened (so toolbar icons will disappear) and recovered when closed (see GMail app for example).

More complicated cases are when a toolbar is changed e.g. multiselect is triggered or search in toolbar is present. In this case, original toolbar without menu icons should appear back when the drawer is opened and specialized multiselect / search / however previously changed toolbar should re-appear when closed back. Try to multiselect some items in GMail app, open/close the drawer & you will see it in action ;)

UPDATE: from GMail app
![toolbar-menu](https://cloud.githubusercontent.com/assets/2512454/5565341/4f79b80a-8ef5-11e4-893c-1d2869a98e5b.png)

**Comment by mkosik** [comment]
What about this @neokree ?

**Comment by neokree** [comment]
I just added this code:
```xml
if(layout.isDrawerOpen(drawer)) {
            menu.clear();
        }

```

But I don't know if this works, because I need to create some example. 
However, I commited now the new dev project, so can you test the new code? 
Thanks

**Comment by Balgam** [comment]
It seems like it's the default behavior now that the toolbar icons are hidden when the drawer is open.  But is there a possibility to change that behavior?

**Comment by neokree** [comment]
Sorry @Balgam why you want to see toolbar icons when the drawer is open?

**Comment by Balgam** [comment]
@neokree 
I've checked a couple of Google Apps. Sometimes they hide the icons and sometimes not. It seems like there is no rule for that. For me, it feels a little bit unsettled,  but if Google has no guidelines for that I think it's ok, thank you for your work 😊
