### ISSUE TITLE
Drawer items coloring

### ISSUE THREAD

**Issue by mkosik** [neokree/MaterialNavigationDrawer#38]
As per Material Design guidelines (and also in Google apps like GMail for a reference)
http://www.google.com/design/spec/patterns/navigation-drawer.html
ordinary drawer item icons (and "notifications") should be of one specific color in non selected state and that is 54% #000000, not black, nor custom colored. However text in some apps appears to be black, as per spec (guidelines) it should be 87% #000000.

When selected, icon and text in such ordinary item should become 100% black or of a custom color for a better contrast (SectionColor now in your case) and item should have a gray BG, as it already has.
See selection state in specs:
http://www.google.com/design/spec/patterns/navigation-drawer.html
How "notifications" should be colored in selected state isn't specified, but judging from GMail app, they still stay gray (no matter section has a custom color or not).

In some rare cases, coloring an icon has it's meaning (check GMail labels), but this icons shouldn't be the ones for a primary navigation purposes. BUT, text & notification colors should remain not changed in this case.

I advice to set & kinda enforce this default colors, make section color -> section icon color and add section selected color as a highlight color, if user would like to override default (and of course handle open/close re-coloring cases).

Lastly, custom coloring of section items in selected state (usually the same custom color for all items) doesn't have to affect fragment's toolbar color (by default it doesn't). It's nice feature, but should be optional for a better flexibility.

PS: drawer items (sections in this lib case) default background color shouln't be white, but #fafafa.

**Comment by neokree** [comment]
well, I will add a theme option in the next release for remove the toolbar color changing when a section that has a color is selected. 
could you suggest a name for the attribute? 
I thinked about toolbarColorChanging -> true / false or something like that.

**Comment by mkosik** [comment]
That method / approach might be usefull too, but I would do that other way around - create a method that will allow setting a default section selected color (like primary or accent color) for all sections, because that was my point / use-case I've mentioned.

**Comment by neokree** [comment]
using the Theme item "uniqueToolbarColor" when a section that has a color is clicked the toolbar color not change.
