### ISSUE TITLE
No account drawer

### ISSUE THREAD

**Issue by mkosik** [neokree/MaterialNavigationDrawer#40]
There are apps that don't need a user to be logged in. In such case, in "account area" there is just a text of a size "abc_text_size_headline_material" - usually by def white, with some background, usually only a color (accent in some apps). Nothing else, pretty simple.

**Comment by randombyte-developer** [comment]
@neokree There should be the possibility to hide the accounts section completly. So the only thing to do is to remove the views like in replaceDrawerHeader() and additionally remove the ImageView 'usercover'. Call the method something like 'noAccounts()' and you have done it. :smiley:

**Comment by neokree** [comment]
ehm, yes but no. @randombyte-developer  you forgot the status bar on lollipop devices, the drawer is between the status bar and the status bar background, so when you remove all user section it should be a little space for status bar, but I actually don't know if I have to color it with the background status bar or simple add some padding from the top

**Comment by randombyte-developer** [comment]
Sorry, I didn't get your point. 
Do you mean, that you don't know, what is right in material design? Personally, I think you should just add padding. 
Or do you mean that the color is different? Maybe a screenshot?

**Comment by neokree** [comment]
I have uploaded three new screenshot on the EXAMPLE.md file. Please see if is a possible solution.

**Comment by randombyte-developer** [comment]
On my Nexus 6, the example app and my app behave wrong. When I select no header the drawer is so tiny.

![screenshot_2015-01-05-20-36-03 1](https://cloud.githubusercontent.com/assets/10366256/5618579/9bba6d1a-951a-11e4-98f6-dcc6b754ff04.png)

Because I have to release my app soon, I set the custom header to 

    <LinearLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        android:layout_height="match_parent"
        android:layout_width="240dp">
    
        <View
            android:layout_width="240dp"
            android:layout_height="wrap_content" />
    
        </LinearLayout>

That works not perfectly but is acceptable.

**Comment by neokree** [comment]
Actually it is an issue only on nexus 6, I suppose for the hight resolution of the screen. 
In the example app the others navigation drawers worked or they still have this issue?

**Comment by mkosik** [comment]
If there is no account section at all, sections should not go behind status bar, because it will look wrong.
So padding or something should be in order.

For apps that use no status bar coloring / behind the status bar theme on KitKat, there should be no padding and items should start from the top (as the Toolbar starts as well).

**Comment by neokree** [comment]
For the nexus 6 and hight resolutions devices problem, I found a solution. 
Now I'm working for remove the drawer between the status bar when you select the NO_HEADER option.

**Comment by mkosik** [comment]
wooohooo, we've got an official statement to this @neokree, check this:
https://plus.google.com/u/0/+MiroslavKo%C5%A1%C3%ADk/posts/jeQGkAXUtvA

**Comment by drinfernoo** [comment]
Any news on this? Another thing I'm seeing on my N6 is this: http://imgur.com/zHOuFz8, when setting the images as Bitmaps. It basically looks like the width just isn't being calculated right. Could we maybe get a way to manually set the width?

**Comment by neokree** [comment]
@drinfernoo what version are you using? Because in 1.2.9 there was a problem for hight resolution and small screen devices, but in 1.3 alpha version there is fixed.

**Comment by randombyte-developer** [comment]
Bug on Nexus 6 fixed! Drawer expands normally.
