### ISSUE TITLE
Roboto font in the drawer (and toolbar)

### ISSUE THREAD

**Issue by mkosik** [neokree/MaterialNavigationDrawer#42]
Well, as per spec Roboto font should be used everywhere in the drawer (by def). However, setting font's isn't esiest in Android  - usually done thru extending original Views classes, creating (libs with) custom ones. Everybody does it differently, some use libraries, some handle it in their app alone...

Thus, it would be gr8 to let implementation use the most commond Roboto libs like:
https://github.com/johnkil/Android-RobotoTextView
https://github.com/eeVoskos/RobotoViews
 or use developer provided font resource internally in lib, avoiding unnecessary, possibly duplicate assets (if utilizing own font as asset in lib). If lib / font asset would not be provided (developer doesn't care), default font might be used as now.

**Comment by muriloandrade** [comment]
Hi guys. I'm trying to use ```<TextView android:textStyle="bold" />``` on a fragment layout but it's not working. 
I'm not sure if I'm able to use Calligraphy as a transitive dependency, but I also tried to save the Roboto-Bold.ttf into my assets/fonts folder and then using the Calligraphy this way with no success:
    ```<TextView 
    xmlns:tools="http://schemas.android.com/tools"
    tools:ignore="MissingPrefix"
    fontPath="fonts/Roboto-Bold.ttf />```

Another trial was to create a CustomTextView and setTypeFace. Doesn't work either.

Any help? please.
