### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by yanivagman** [neokree/MaterialNavigationDrawer#43]
It will be nice to have RTL support so the lib can be more generic (as explained at http://android-developers.blogspot.co.il/2013/03/native-rtl-support-in-android-42.html). 
Essentialy, there are two steps involved:
adding android:supportsRtl="true" to the element in manifest file
and changing (or adding if min sdk is lower than 17) "start" instead of "left" and "end" instead of right.

**Comment by neokree** [comment]
Sorry for the delay, but now the rtl support is added and it will be avariable from the next release

**Comment by neokree** [comment]
please check if the rtl now work and this issue can be closed. Thanks

**Comment by navidei** [comment]
Could you please explain how can I use this feature? I want to force the navigation drawer and toolbar to be right to left.
