### ISSUE TITLE
Section previously selected remains highlighted 

### ISSUE THREAD

**Issue by h0aX14** [neokree/MaterialNavigationDrawer#52]
I've created a app using your library, but when I select new section, the previously selected section remains highlighted in the drawer. I've tested on 5.x

Screenshot :: [Imgur](http://i.imgur.com/7hQFWwB.png)

**Comment by h0aX14** [comment]
@neokree, Resolved

**Comment by filipebezerra** [comment]
Hey, I got this issue using the section selection programatically using the method select(). The previous selected section remains selected after calling select() with another section. 

The piece of code that can simulate this:

    getSectionByTitle(getString(R.string.my_section_title)).select();

Please refer this issue here #220.
