### ISSUE TITLE
colorAccent not working for v1.2.8 for lollipop devices

### ISSUE THREAD

**Issue by h0aX14** [neokree/MaterialNavigationDrawer#56]
Here is my style.xml

     <style name="MyTheme"   parent="MaterialNavigationDrawerTheme.Light.DarkActionBar.TranslucentKitKatStatusBar">
     
        <item name="colorPrimary">@color/colorPrimaryIndigo</item>

        <item name="colorPrimaryDark">@color/colorDarkPrimaryIndigo</item>
        <item name="colorAccent">@color/colorPinkAccent</item>
    </style>

colors.xml

     <color name="colorDarkPrimaryIndigo">#303F9F</color>
    <color name="colorPrimaryIndigo">#3F51B5</color>
    <color name="colorPinkAccent">#FF4081</color>

In my manifest file, i have set application level theme as MyTheme

![screenshot_2014-12-28-15-05-51](https://cloud.githubusercontent.com/assets/10323829/5563540/5c777616-8ea3-11e4-8943-8296bf7527e3.png)

**Comment by neokree** [comment]
maybe I found something.
see [there](https://github.com/neokree/MaterialNavigationDrawer/blob/master/MaterialNavigationDrawerModule/src/main/res/values/styles.xml) I setted the popupTheme with the V21 Appcompat theme for popup as a user suggest me. Maybe It is the cause for your problem.

**Comment by h0aX14** [comment]
app:popupTheme referes to toolbar and not dialog box mate!

**Comment by mkosik** [comment]
No additional styles should be needed for real Android L dialogs - they should use the accentColor by default. Is it an issue also in other cases, where the accentColor should be use by def by the system?

What AppCompat version do you use in your app @h0aX14? Does this issue remain in an empty app with & without AppCompat on Android L?

**Comment by h0aX14** [comment]
@mkosik , I'm using AppCompat v7:21.0.+ .I've not tried without AppCompat. But on pre-lollipop devices it's working flawlessly. The issue is only with dialog boxes.
