### ISSUE TITLE
RTL support is a bit buggy

### ISSUE THREAD

**Issue by javmarina** [neokree/MaterialNavigationDrawer#57]
The drawer view supports  RTL direction, but the items inside it don't. See attached screenshot.
![screenshot_2014-12-27-22-14-38](https://cloud.githubusercontent.com/assets/2737599/5563968/b6a9e28e-8ea0-11e4-9e92-5057969837f1.png)

**Comment by EMIN3M1986** [comment]
First of all I thank you for this very nice module.
Is it possible to say when your next version release ?
