### ISSUE TITLE
Last clicked section remains highlighted even when the target is an activity

### ISSUE THREAD

**Issue by javmarina** [neokree/MaterialNavigationDrawer#58]
In the example apk, when you click a section, the drawer is closed. If you reopen it, the section is highlighted. That's the correct behavior when the target is a fragment. However, if you open the Settings activity, close it and open the drawer, you'll see that the section is highlighted.
![screenshot_2014-12-28-14-55-02](https://cloud.githubusercontent.com/assets/2737599/5563984/8b160804-8ea1-11e4-9429-d146e143271b.png)

**Comment by javmarina** [comment]
I think it's solved (at least in the example.apk)

**Comment by mkosik** [comment]
@neokree actually it should NOT select the section in first place (no unselect needed) for activity section (because it's a default behaviour) & for custom action sections that should be optional.
