### ISSUE TITLE
You can click multiple sections before the drawer closes

### ISSUE THREAD

**Issue by javmarina** [neokree/MaterialNavigationDrawer#59]
In most google apps, when you click a section, the drawer is automatically disabled, avoiding new clicks. Nevertheless, you can click a few sections at once in the example app. That leads to force close (3 sections for me), probably because of an out of memory error.

**Comment by javmarina** [comment]
No

**Comment by javmarina** [comment]
What I propose is that when a section is clicked, the first thing done is totally disabling the drawer. When it's closed, the drawer gets enabled again. Right now you can click multiple sections at the same time.

**Comment by neokree** [comment]
yes I know.
I have tried now and you have reason, it isn't disabled. 
I done my question because I have implemented a disabling method into the drawer, but seems to have a bug, maybe with the devicemultipaneSupport check.

**Comment by javmarina** [comment]
I haven't seen your code. For example, your drawer view is mDrawer. I think you have to call mDrawer.setClickable(false); when a section is clicked and when the drawer is closed call mDrawer.setClickable(true); again

**Comment by neokree** [comment]
no, I disabled all listener using a simple if with boolean parameter. Because I have try but setClickable not work with custom listener on child view. I think the bug persists because this is a time problem. I block all section listeners too late

**Comment by egor-n** [comment]
Google's DrawerLayout cancels children view touches by itself when it is not in the `STATE_IDLE`. Their approach doesn't work here, because of the `MaterialSection`'s touch behavior. It waits for the ripple effect to finish before doing actual `onClick`. I've made a separate issue about it - #128.

**Comment by mrcasals** [comment]
I'm having the same second problem vedhavyas is facing in #33. Any update on this? 

Thanks!

**Comment by neokree** [comment]
I'm working to move the ripple effect to another lib, because this bug is related to some others.
please check this issue #128
