### ISSUE TITLE
Action bar not expanding on Landscape mode

### ISSUE THREAD

**Issue by CoericK** [neokree/MaterialNavigationDrawer#61]
These are images from the sample than im testing:
When the app is in portrait mode works fine but when changes to landscape the menu is shown but when it hides the fragment within don't resize.

https://www.dropbox.com/sh/x4jg0cdp27o67q2/AACUXEUyOpqWU3X_onoizkuPa?dl=0

**Comment by CoericK** [comment]
Oh ok i see @ht1990, thanks for your help. But seems like i will have to wait for @neokree to fix this and add it for the new release. I hope it will be soon.

**Comment by neokree** [comment]
Well, the main problem is preserve the options to add or remove the multi pane support.
For example, @ht1990 your fix is very useful, but It cannot disable the multi pane support.
