### ISSUE TITLE
cannot touch in content in DrawerLayout.LOCK_MODE_LOCKED_OPEN

### ISSUE THREAD

**Issue by ht1990** [neokree/MaterialNavigationDrawer#62]
in tablet 7-inch landscape or larger device, you setDrawerLockMode, so you can't touch in content.
I think this is solution:
http://derekrwoods.com/2013/09/creating-a-static-navigation-drawer-in-android/
I tried and it work for me.

**Comment by neokree** [comment]
mmm ok, but with this method I adds multipane support on every project. 
The problem is that It should be the developer choice, I can try to add a new attribute to the MaterialNavigationDrawerTheme and delete the actual method addMultipaneSupport(); for support both.

**Comment by rburgst** [comment]
I fixed the issue in the following manner 

1. I subclassed DrawerLayout to stop intercepting touch events


        package com.burgstaller.android.focusgtd.ui.widgets;

        import android.content.Context;
        import android.support.v4.widget.DrawerLayout;
        import android.util.AttributeSet;
        import android.view.MotionEvent;

        /**
         * An improved version of DrawerLayout that will ensure that a locked open DrawerLayout can be used without capturing all touches into the client
         * area.
         * <p>
         *     To activate, call {@link #requestDisallowInterceptTouchEvent(boolean)} on the layout. Note that this should only ever be done in case when
         *     the drawer is to be locked open.
         * </p>
         * @author Rainer Burgstaller
         */
        public class BetterDrawerLayout extends DrawerLayout {
            private boolean m_disallowIntercept;

            public BetterDrawerLayout(final Context context) {
                super(context);
            }

            public BetterDrawerLayout(final Context context, final AttributeSet attrs) {
                super(context, attrs);
            }

            public BetterDrawerLayout(final Context context, final AttributeSet attrs, final int defStyle) {
                super(context, attrs, defStyle);
            }

            @Override
            public boolean onInterceptTouchEvent(final MotionEvent ev) {
                if (m_disallowIntercept) {
                    return false;
                }
                return super.onInterceptTouchEvent(ev);
            }

            @Override
            public void requestDisallowInterceptTouchEvent(final boolean disallowIntercept) {
                super.requestDisallowInterceptTouchEvent(disallowIntercept);

                m_disallowIntercept = disallowIntercept;
            }
        }

2. then you only need to replace the drawer layout in `activity_material_navigation_drawer.xml`

        <com.burgstaller.android.focusgtd.ui.widgets.BetterDrawerLayout
            xmlns:android="http://schemas.android.com/apk/res/android"
            android:id="@+id/drawer_layout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:fitsSystemWindows="false" >

            
            <RelativeLayout
                android:id="@+id/content"
       ...

        </com.burgstaller.android.focusgtd.ui.widgets.BetterDrawerLayout>

3. finally you need to call `layout.requestDisallowInterceptTouchEvent(true)` in `MaterialNavigationDrawer#onCreate`


        if(deviceSupportMultiPane()) {
            // se il multipane e' attivo, si e' in landscape e si e' un tablet allora si passa in multipane mode
            layout.setDrawerLockMode(DrawerLayout.LOCK_MODE_LOCKED_OPEN,drawer);
            DrawerLayout.LayoutParams params = new DrawerLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT);
            params.setMargins((int) (320 * density),0,0,0);
            content.setLayoutParams(params);
            layout.setScrimColor(Color.TRANSPARENT);
            layout.openDrawer(drawer);
            layout.requestDisallowInterceptTouchEvent(true);
        }


If you don't want to change the original source code you can grab a reference to the DrawerLayout in your Activity.init() method and call `layout.requestDisallowInterceptTouchEvent(true)` there.

**Comment by neokree** [comment]
Thanks @rburgst for your custom DrawerLayout. It works perfectly! 
It will be active from the next release

**Comment by CoericK** [comment]
Awesome thanks @rburgst, so @neokree after u check if the problem is resolved, when are you going to release it? Any ETA?

**Comment by neokree** [comment]
I have released it few minutes ago, in about two hours it will be online

**Comment by rburgst** [comment]
@neokree I have a better solution (actually the current one does not seem to work on a fullHD phone, where the drawer won't close on 5.0 and higher)

in `BetterDrawerLayout.java`
        @Override
    public void setDrawerLockMode(final int lockMode, final int edgeGravity) {
        super.setDrawerLockMode(lockMode, edgeGravity);
        m_disallowIntercept = (lockMode == LOCK_MODE_LOCKED_OPEN);
    }
