### ISSUE TITLE
Cannot add an account outside the init method

### ISSUE THREAD

**Issue by qgadrian** [neokree/MaterialNavigationDrawer#63]
Hi,

I'm trying to use the account section to implement a sing in, but when I get the result code from the login activity, I'm not able to add an account to the navigation drawer. I can do it if a manually insert an account in the init method.

This is what I'm doing right now:

```java
    @Override
    public void onAccountOpening(MaterialAccount materialAccount) {
        if (materialAccount == null) {
            Intent intentLogin = new Intent(getApplicationContext(), LoginActivity.class);
            startActivityForResult(intentLogin, RESULT_LOGIN_SUCCESS);
        }
        else {
            Toast.makeText(getApplicationContext(), "Current account is " + materialAccount.getTitle(), Toast.LENGTH_SHORT).show();
        }
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        if (resultCode == RESULT_LOGIN_SUCCESS) {
            MaterialAccount materialAccount = new MaterialAccount("Elovendo","account@elovendo.com",this.getResources().getDrawable(R.drawable.home),this.getResources().getDrawable(R.drawable.nav_drawer_background));
            this.addAccount(materialAccount);
        } else {
            Toast.makeText(getApplicationContext(), "Not signed in", Toast.LENGTH_SHORT).show();
        }
    }
```

Don't know if I'm missing something or this is not currently supported yet.

Thank you for your fantastic work ;)

**Comment by neokree** [comment]
@qgadrian  please try to add the <code>notifyAccountDataChanged();</code> after this.addAccount()

**Comment by qgadrian** [comment]
Hi @neokree  still not working, fails at `notifyAccountDataChanged()`. Here is the full stacktrace:

java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=1, data=null} to activity {com.elovendo/com.elovendo.ElovendoMain}: java.lang.NullPointerException
            at android.app.ActivityThread.deliverResults(ActivityThread.java:3365)
            at android.app.ActivityThread.handleSendResult(ActivityThread.java:3408)
            at android.app.ActivityThread.access$1300(ActivityThread.java:135)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1244)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5017)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
            at it.neokree.materialnavigationdrawer.MaterialNavigationDrawer.notifyAccountDataChanged(MaterialNavigationDrawer.java:1005)
            at com.elovendo.ElovendoMain.onActivityResult(ElovendoMain.java:336)
            at android.app.Activity.dispatchActivityResult(Activity.java:5423)
            at android.app.ActivityThread.deliverResults(ActivityThread.java:3361)
            at android.app.ActivityThread.handleSendResult(ActivityThread.java:3408)
            at android.app.ActivityThread.access$1300(ActivityThread.java:135)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1244)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5017)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
            at dalvik.system.NativeStart.main(Native Method)

I noticed a few problems. Now there is no click event on the drawer header (`onAccountOpening(MaterialAccount materialAccount)` ). Also, it's not clear that which type of drawerType is needed for an image and account, I guess should be `<item name="drawerType">@integer/DRAWERTYPE_ACCOUNTS</item>` but in the wiki it's not reference to this.

**Comment by neokree** [comment]
sorry but I don't catch how your activity is still visible if you add the account into the 
<code>onActivityResult()</code>. That should be used when the activity is gone, and it returns back his work. So adding the account when the activity will be destroyed is useless. 

The accounts drawer type is the default, so you don't have to declare anything to your theme.

**Comment by qgadrian** [comment]
This was just an example. ``intentLogin`` sends back the user information, but I was only catching the result code and testing how should be adding an account, just for testing.

Anyway, I changed it for using with a fragment, but still throws the same error. I tried to create the MaterialAccount in fragment, and set it to the drawer thru ``onChangeAccount(MaterialAccount materialAccount)``, but still same result...

**Comment by neokree** [comment]
Well, Basicly in a real situation an account will be setted asyncronously, when the user send back the informations you need to add the account information. 
For emulate it, I used an asynctask that will add an account after 5 seconds and then update his content.

```java
public class NavigationDrawerTest extends MaterialNavigationDrawer implements MaterialAccountListener, MaterialSectionListener {

    MaterialAccount account;
    MaterialSection section1, section2, section3, section4, section5, section6, recorder, night, last, settingsSection;

    @Override
    public void init(Bundle savedInstanceState) {


        this.allowArrowAnimation();
        // add first account

        account = new MaterialAccount(this.getResources(),"Hello " + getUsername(), "", null, R.drawable.mat2);
        this.addAccount(account);

        // set listener
        this.setAccountListener(this);

        // create sections
        section1 = this.newSection("String1", new FragmentIndex());
        section2 = this.newSection("String2", new FragmentIndex());
        section3 = this.newSection("Help", new FragmentIndex());
        section4 = this.newSection("Send Feedback", new FragmentIndex());
        section5 = this.newSection("Rate our app", new FragmentIndex());
        section6 = this.newSection("About", new FragmentIndex());

        Intent i = null;
        settingsSection = this.newSection("Settings", this.getResources().getDrawable(R.drawable.ic_settings_black_24dp), i);

        // add your sections to the drawer
        this.addSubheader("Header1");
        this.addSection(section1);
        this.addSection(section2);

        this.addSubheader("General");
        this.addSection(section3);
        this.addSection(section4);
        this.addSection(section5);
        this.addSection(section6);

        this.addBottomSection(settingsSection);

        this.addMultiPaneSupport();

        t.start();
    }

    private String getUsername() {
        return "Username";
    }

    @Override
    public void onAccountOpening(MaterialAccount account) {

    }

    @Override
    public void onChangeAccount(MaterialAccount newAccount) {

    }

    // after 5 second (async task loading photo from website) change user photo
    Thread t = new Thread(new Runnable() {
        @Override
        public void run() {
            try {
                Thread.sleep(5000);

                runOnUiThread(new Runnable() {
                    @Override
                    public void run() {
                        MaterialAccount account = new MaterialAccount(getResources(),"Hello " + getUsername(), "", R.drawable.photo2, R.drawable.mat2);
                        addAccount(account);
                        notifyAccountDataChanged();
                        Toast.makeText(getApplicationContext(), "Added 'from web' account", Toast.LENGTH_SHORT).show();
                    }
                });


            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
    });
}
```
NOTE: this code use the dev version of this library, that you could find into gihub.

**Comment by qgadrian** [comment]
But in a real situation, you also need to get user input for login/password. That's my point, you need a ``Fragment`` to get that user input, and you need to pass it to the drawer in order to add the a new account with the user info.

A workaround is create an "empty" account on ``init()``, and "update" it when a successful login.

**Comment by neokree** [comment]
Or you can set a base account with sample images like youtube app, then when the user is logged in you need only to change the informations. 
However, if the user is obligatory for your app I suggest you to move your sign in/sign up form outside the navigation drawer, like the email app.

**Comment by neokree** [comment]
check the new library version, 1.3.2
