### ISSUE TITLE
Create method on MaterialSection.java to pass String as parameter

### ISSUE THREAD

**Issue by alessandrosilva** [neokree/MaterialNavigationDrawer#66]
I suggest adding the following code in MaterialSection.java class:

public MaterialSection setNotificationsText(String text) {
this.notifications.setText(text);
return this;
}

With that you can pass String as parameter and put values such as "$ 200.00" in the notification

**Comment by neokree** [comment]
I have relased the new version with this method added. 
Please check if it work and close this issue
