### ISSUE TITLE
Please help me fixed this, i've trying to resolve it but no solution!

### ISSUE THREAD

**Issue by samsoft00** [neokree/MaterialNavigationDrawer#68]
public void init(Bundle savedInstanceState) {

        navMenuTitles = getResources().getStringArray(R.array.navDrawerItems);
        navMenuIcons = getResources().obtainTypedArray(R.array.navDrawerIcons);

        MaterialAccount account = new MaterialAccount("NeoKree", "neokree@gmail.com",this.getResources().getDrawable(R.drawable.bg_unlike_button),this.getResources().getDrawable(R.drawable.bamboo));
        this.addAccount(account);

        // set listener
        this.setAccountListener(this);

        // add your sections
        this.addSection(this.newSection(navMenuTitles[0], this.getResources().getDrawable(navMenuIcons.getResourceId(0, -1)),
                new HomeFragment()));

        this.addSection(this.newSection(navMenuTitles[1], this.getResources().getDrawable(navMenuIcons.getResourceId(1, -1)),
                new FollowingFragment()));

        this.addSection(this.newSection(navMenuTitles[2], this.getResources().getDrawable(navMenuIcons.getResourceId(2, -1)),
                new FavoritesFragment()));

        this.addDivisor();

        Intent i = new Intent(this, SettingsActivity.class);
        this.addSection(this.newSection(navMenuTitles[4],this.getResources().getDrawable(navMenuIcons.getResourceId(4, -1)),i));

        navMenuIcons.recycle();
    }

ERROR
01-01 10:55:15.854    7918-7918/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.atouchsimo.fullsocialnetwork/com.atouchsimo.fullsocialnetwork.MainActivity}: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2180)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
            at android.app.ActivityThread.access$600(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5041)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
            at android.support.v7.app.ActionBarActivityDelegateBase.setSupportActionBar(ActionBarActivityDelegateBase.java:165)
            at android.support.v7.app.ActionBarActivity.setSupportActionBar(ActionBarActivity.java:92)
            at it.neokree.materialnavigationdrawer.MaterialNavigationDrawer.onCreate(MaterialNavigationDrawer.java:234)
            at android.app.Activity.performCreate(Activity.java:5104)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
            at android.app.ActivityThread.access$600(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5041)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by h0aX14** [comment]
Can you post your style.xml ?

**Comment by samsoft00** [comment]
Thanks @h0aX14  here is the style.xml   
<resources xmlns:android="http://schemas.android.com/apk/res/android">

    
    <style name="AppBaseTheme" parent="android:Theme.Light">
        
    </style>

    
    <style name="AppTheme" parent="AppBaseTheme">
        <item name="android:actionBarStyle">@style/MyActionBar</item>
    </style>
    
    <style name="MyActionBar" parent="@style/Theme.AppCompat.Light.DarkActionBar">
        <item name="android:background">@color/actionBar</item>
        <item name="android:titleTextStyle">@style/MyActionBarTitleText</item>
    </style>

    <style name="MyActionBarTitleText">
        <item name="android:textColor">@android:color/white</item>
    </style>

    <style name="postOwnerName">
        <item name="android:textColor">@color/postOwner</item>
        <item name="android:textSize">16sp</item>
    </style>

    <style name="postPublishDate">
        <item name="android:textColor">@color/postPublishDate</item>
        <item name="android:textSize">14sp</item>
    </style>

    <style name="postStatus">
        <item name="android:textColor">@color/postStatus</item>
        <item name="android:padding">16dp</item>
        <item name="android:textSize">14sp</item>
    </style>

    <style name="viewsCount">
        <item name="android:textColor">@color/footerText</item>
        <item name="android:textSize">14sp</item>
    </style>

    <style name="useCount">
        <item name="android:textColor">@color/footerText</item>
        <item name="android:textSize">14sp</item>
    </style>

    <style name="actionAreaBtns">
        <item name="android:layout_margin">5dp</item>
    </style>

    <style name="buttons">
        <item name="android:textColor">@android:color/white</item>
        <item name="android:textSize">14sp</item>
        <item name="android:layout_margin">5dp</item>
        <item name="android:paddingRight">5dp</item>
        <item name="android:paddingLeft">5dp</item>
    </style>

    <style name="profileName">
        <item name="android:textColor">@color/profileName</item>
        <item name="android:textSize">16sp</item>
    </style>

    <style name="profileJob">
        <item name="android:textColor">@color/profileJob</item>
        <item name="android:textSize">14sp</item>
    </style>

    <style name="profileAdress">
        <item name="android:textColor">@color/profileAdress</item>
        <item name="android:textSize">12sp</item>
    </style>

    <style name="featuredPhotos">
        <item name="android:textColor">@color/featuredPhotos</item>
        <item name="android:textSize">14sp</item>
        <item name="android:layout_marginTop">10dp</item>
        <item name="android:layout_marginBottom">10dp</item>
    </style>

    <style name="statusEditText">
        <item name="android:background">@drawable/bg_status_editetxt</item>
        <item name="android:textColorHint">@color/statusEditTextBorder</item>
        <item name="android:textColor">@color/actionBar</item>
    </style>

    <style name="newStatusHeader">
        <item name="android:background">@drawable/bg_newstatus_header</item>
    </style>

    <style name="newStatusFooter">
        <item name="android:background">@drawable/bg_newstatus_header</item>
    </style>

    <style name="newStatusBody">
        <item name="android:background">@drawable/bg_newstatus_header</item>
    </style>
	<style name="drawerListItem">
	    <item name="android:textAppearance">?android:attr/textAppearanceMedium</item>
	    <item name="android:textColor">@color/postPublishDate</item>
	    <item name="android:layout_marginTop">10dp</item>
	    <item name="android:layout_marginBottom">10dp</item>
	</style>
	<style name="drawerListItemIcon">
	    <item name="android:layout_marginLeft">12dp</item>
	    <item name="android:layout_marginRight">12dp</item>
	    <item name="android:layout_width">25dp</item>
	</style>
	<style name="editText">
	    <item name="android:background">@drawable/bg_edittext</item>
	    <item name="android:textColorHint">#B7B7B7</item>
	    <item name="android:textColor">@color/actionBar</item>
	    <item name="android:padding">8dp</item>
	    <item  
	      name="android:textSize">16sp</item>
	</style>
	<style name="loginLayout">
	    <item name="android:layout_margin">20dp</item>
	</style>
	<style name="logintBtn">
	    <item name="android:textColor">@color/white</item>
	    <item name="android:textSize">14sp</item>
	</style>
	<style name="commentOwnerName">
        <item name="android:textColor">#000000</item>
        <item name="android:textSize">14sp</item>
    </style>
    <style name="commentText">
        <item name="android:textColor">@color/postPublishDate</item>
        <item name="android:textSize">12sp</item>
    </style>
    <style name="commentDate">
        <item name="android:textColor">@color/postPublishDate</item>
        <item name="android:textSize">10sp</item>
    </style>
</resources>

**Comment by h0aX14** [comment]
And what is your application level theme ? is it AppTheme ?
if yes, problem lies there!
Refer this sample example's style.xml
https://github.com/neokree/MaterialNavigationDrawer/blob/master/MaterialNavigationDrawer/app/src/main/res/values/styles.xml

You can use any of them found here ::
https://github.com/neokree/MaterialNavigationDrawer/blob/master/MaterialNavigationDrawerModule/src/main/res/values/styles.xml

**Comment by neokree** [comment]
@samsoft00 if you have resolved your problem, please close this issue

**Comment by am9072** [comment]
There are **two simple and quick solutions**

go to res-->values-->styles
watch the simple video for the answer
[https://youtu.be/YJR8njVHRA4](url)

You can  remove your window action bar by setting NoActionBar 
`<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">`
or by adding  <item name="windowActionBar">false</item>
    <item name="windowNoTitle">true</item>
