### ISSUE TITLE
BottomSection should stick to bottom

### ISSUE THREAD

**Issue by hisham2007** [neokree/MaterialNavigationDrawer#69]
As in Inbox app, settings should stick to bottom but I found here that it scrolls like normal sections

**Comment by h0aX14** [comment]
Actually it should stick down!

**Comment by neokree** [comment]
See issue #29 for a complete explanation. 
Please before open a new issue, checks if there are other issues closed that are compatible with yours

**Comment by mkosik** [comment]
Default behaviour is not sticking it to the bottom at all. It is optional, however only when not scrolled - as defined in Material Design specs. Inbox doesn't implement it right (yet) - however most of the latest updates of Google apps do it correctly (no sticking at all, the default option).

Please, close this issue & if you have anything to add, re-open #29.

**Comment by hisham2007** [comment]
Thanks for replies. I will close it .
