### ISSUE TITLE
Support Multiple Profiles

### ISSUE THREAD

**Issue by Speenah** [neokree/MaterialNavigationDrawer#7]
I think it would be a great addition to this library to support multiple profiles and switching profiles like in the Gmail app.
![image](https://cloud.githubusercontent.com/assets/3674506/5328464/7d3b4d44-7d4d-11e4-9d10-b0d90b01a31d.png)

**Comment by neokree** [comment]
I have committed the 1.3 alpha to github. 
This commit finally remove the max account size. 
There are a new sectionlist that shows the accounts like in the Gmail app and there are also a new sectionList above the account list for insert section like "add a new account" or other things like this.
You can add sections to this list using: <code>addAccountSection()</code> method.

I have also make public these methods:
```java
public void setUserEmail(String email)
public void setUsername(String username)
public void setFirstAccountPhoto(Drawable photo)
public void setSecondAccountPhoto(Drawable photo)
public void setThirdAccountPhoto(Drawable photo)
public void setDrawerHeaderBackground(Drawable background)
```

So if you want a mockup account now you can have it.
