### ISSUE TITLE
real status bar color is not changed

### ISSUE THREAD

**Issue by hisham2007** [neokree/MaterialNavigationDrawer#70]
when action bar color changes, fake status bar get darker color while status bar here should be the system status bar

**Comment by neokree** [comment]
Yes, I used this little trick for implements a support for every devices. 
I tried some solutions and this is the more faster and easier. 
You have some problem with it?

**Comment by hisham2007** [comment]
Yes. when a section has another color. action bar color changes while system status bar on Lollipop still unchanged while it should change to the darker color of the toolbar. This can be achieved on Android 5 and you can use fallback code on previous Android releases. It is  enhancement. not really an issue.

**Comment by neokree** [comment]
Well, in this case I can add the system call for changing status bar color with 5.0 devices
