### ISSUE TITLE
Add DrawerLayout.DrawerListener callbacks

### ISSUE THREAD

**Issue by randombyte-developer** [neokree/MaterialNavigationDrawer#71]
Hello! I am new here on GitHub.

First, your library is awesome!

But I have one suggestion: How about offering us the callbacks of the DrawerLayout? I have to close the keyboard in my app, when the NavigationDrawer is expanded. But I have not found 'setDrawerListener(...)' or anything like that.
So, please add a method like that which simply only calls setDrawerListener(listenerFromArgument) on your DrawerLayout.

Thank you!

**Comment by randombyte-developer** [comment]
Thanks!  
As you know, I am new here. Do I have to close this issue now or after the next release (which will hopefully come soon 😃)?

**Comment by neokree** [comment]
well, please wait up to the next release, and if your problem is solved (and you don't find any bug) then you can close the issue :)

**Comment by randombyte-developer** [comment]
Commit is six hours ago. When does it push to Maven Central?

**Comment by neokree** [comment]
I forgot to release on maven central the new version, sorry... 
I have released it now, please wait about two hours and it will be online

**Comment by randombyte-developer** [comment]
Works perfectly! Thanks.
