### ISSUE TITLE
Navigation Item click ripple affect

### ISSUE THREAD

**Issue by joseedwin84** [neokree/MaterialNavigationDrawer#73]
This is by far the best Material design navigation drawer example i could find but i found one issue, the ripple animations seems to be a bit slow and this may be a bit annoying to the user. :smiley:

**Comment by marcusforsberg** [comment]
This was discussed in #47. :)

**Comment by neokree** [comment]
@joseedwin84 a bit slow so I have to speed it up?

**Comment by joseedwin84** [comment]
@neokree Yeh i think you need to make it more faster because its slower than the ripple animation in the normal elements in Lollipop and this may be a little annyoing to the user :+1:

**Comment by neokree** [comment]
ok, in the next release I will set to 300 ms,anyone that knows exactly the duration of the ripple effect?

**Comment by mkosik** [comment]
well what we call "duration" is more complicated - here from AOSP:
https://github.com/android/platform_frameworks_base/blob/master/graphics/java/android/graphics/drawable/Ripple.java

**Comment by neokree** [comment]
With the last version (1.3.2) I have used the new material-ripple library, that is very similar at the official lollipop ripple effect.

**Comment by kartiraman** [comment]
@neokree Is it posible to remove ripple effect? am using it.neokree:MaterialTabs:0.11. Thanks
