### ISSUE TITLE
SaveInstanceState

### ISSUE THREAD

**Issue by FHellmann** [neokree/MaterialNavigationDrawer#75]
When a device is rotated, the first Section will be selected. Is there any solution so far? Or is it a bug due to the fact that the Instance State is not saved?

**Comment by neokree** [comment]
Actually it is a bug, I will work for a fix

**Comment by neokree** [comment]
Please check if the bug is solved with <code>1.2.9</code> version.
Thanks

**Comment by philbring** [comment]
Bug seemed not to be fixed with 1.2.9

**Comment by FHellmann** [comment]
It looks like it is working! :+1:  
Thank you!
