### ISSUE TITLE
Drawer in Dark Theme

### ISSUE THREAD

**Issue by aritraroy** [neokree/MaterialNavigationDrawer#76]
Hello,

You have done a nice work with this lib. In my app, I am using a Dark Theme, but this Navigation Drawer is all white.

Is there a way to use Dark Theme on the Navigation Drawer?

**Comment by neokree** [comment]
actually no, I haven't thinked about it, but it is a valid request. 
I add it to my todo-list for the next release

**Comment by mkosik** [comment]
Well even without an example I think this is a valid request due to specific app customization / branding, that might occur in some cases ;)

**Comment by neokree** [comment]
With the 1.3 alpha version I have added the Dark Theme, you can set it using the <code>MaterialNavigationDrawerTheme</code>. Please check it out and tell me if it could be a solution or if you find some bug.

**Comment by aritraroy** [comment]
I will surely test it out. Actually, I needed a more flexible Navigation Drawer for my project so I needed to scratch code one.

But I will surely test it out and let you know for improvements and bugs.

**Comment by neokree** [comment]
Thank for your help and your time @aritraroy
