### ISSUE TITLE
Sandwich icon is blurred

### ISSUE THREAD

**Issue by alextel69** [neokree/MaterialNavigationDrawer#80]
Device: Samsung Galaxy S2
Android: CyanogenMod 4.4.4
AppCompat: com.android.support:appcompat-v7:21.0.3

I downloaded an example APK from README. All throughout the example app sandwich icon is blurred. However, Gmail app on this very device has got clear sandwich.

TAKE A LOOK AT TOP LEFT CORNER IN 2 SCREENSHOTS BELOW (Sandwich icon)

Clear sandwich

![screenshot_2015-01-05-12-13-08](https://cloud.githubusercontent.com/assets/3159171/5611965/5c47e930-94d6-11e4-8f81-95b09a20dd81.png)

Blurred sandwich
![screenshot_2015-01-05-12-11-12](https://cloud.githubusercontent.com/assets/3159171/5611974/8a2711aa-94d6-11e4-88f3-5f84176846e2.png)

**Comment by neokree** [comment]
I am using the default sandwich icon from ActionbarDrawerToggle v7, but I will investigate on this problem.

**Comment by mkosik** [comment]
Here's screen from an experiment with an older version of the lib (1.1.3) using 'com.android.support:appcompat-v7:21.0.3' I found in my phone. It doesn't seem blurred. What AppCompat version are you guys using?

![screenshot_2015-01-05-23-52-42](https://cloud.githubusercontent.com/assets/2512454/5621503/7fd68662-9536-11e4-8357-cbd8680484f9.png)

**Comment by alextel69** [comment]
@mkosik I am also using 21.0.3 version. Sandwich icon is clear on my Samsung tablet, but blurred on my Samsung S2. 
What device did you use to make the screenshot?

**Comment by mkosik** [comment]
@alextel69 hmmm, interesting. I used my OnePlus One with FULLHD res.

**Comment by neokree** [comment]
it seems this problem is only applicable with low resolution devices

**Comment by alextel69** [comment]
@neokree if so, why Gmail app has got ok sandwich?

**Comment by neokree** [comment]
@alextel69 I sincerely don't know.

**Comment by mkosik** [comment]
@alextel69 Have you tried any other open-source app / lib example with material design drawer on that same resolution that doesn't have this issue? If yes, tell us which for an inspiration.
Here's for e.g. Google's I/O 2014 app (by Roman Nurik, Google designer) which is essentially a "cookbook" how Android apps should look & work:
https://github.com/romannurik/iosched
Or another Material Design app by Google designer:
Philm by Chris Banes:
https://github.com/chrisbanes/philm

Also I suggest you to ask in "Android App Design" group on G+, managed by Roman Nurik:
https://plus.google.com/u/0/communities/116667001535376136065
or / and on stackoverflow and come back here if you will find some answer / clue ;)

**Comment by mohfaz** [comment]
how to change sandwich icon color?

**Comment by neokree** [comment]
@mohfaz please check [this](http://stackoverflow.com/a/27251004/3600120)
