### ISSUE TITLE
No view found for id 0x7f09005a (com.my.app:id/frame_container) 

### ISSUE THREAD

**Issue by younes0** [neokree/MaterialNavigationDrawer#81]
This is more a support question, would be very please to have this fixed:
I get the following error:
> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.younes0.bnm/com.my.app.activities.MainActivity}: java.lang.IllegalArgumentException: No view found for id 0x7f09005a (com.my.app:id/frame_container) for fragment SwipeFragment{5282cc60 #0 id=0x7f09005a}

I'm not sure to have setup the lib correctly, there my classes:
- AbstractBaseActivity 
```java
public abstract class AbstractBaseActivity extends MaterialNavigationDrawer  {

    private ObjectGraph activityGraph; // dagger
    private MaterialSection section1;

    protected abstract List<Object> getModules();

	@Override protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		activityGraph = ((App) getApplication()).createScopedGraph(getModules().toArray());
		activityGraph.inject(this);
	}

	@Override public void init(Bundle savedInstanceState) {
		section1 = this.newSection("Section 1", new SwipeFragment());
		this.addSection(section1);
    }
}
```
- MainActivity:
```java
public class MainActivity extends AbstractBaseActivity {

    private Toolbar toolbar ;

    // dagger
    @Inject ConnectionSource connectionSource;
    @Inject Application app;

    protected List<Object> getModules() {
        return Arrays.<Object>asList(new DbModule());
    }

    @Override protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        ButterKnife.inject(this);
    }
}
```
- activity_main.xml
```xml
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              xmlns:app="http://schemas.android.com/apk/res-auto"
              android:orientation="vertical"
              android:layout_width="match_parent"
              android:layout_height="match_parent">

 </LinearLayout>
```
- And finally, a Fragment:
```java
public class SwipeFragment extends Fragment {

    @InjectView(R.id.frame) SwipeFlingAdapterView flingContainer;

    @Override public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {

    View myFragmentView = inflater.inflate(R.layout.fragment_swipe, container, false);
        ButterKnife.inject(this, myFragmentView);
        /* ... */
        return myFragmentView;
    }
}

**Comment by neokree** [comment]
as written on EXAMPLE.md file, please not override onCreate method, use init() method instead, so please try to move all code in <code>AbstractBaseActivity</code> onCreate method into init(), then in your MainActivity replace the override to onCreate to init() method. 
Tell us if your problem is solved, thanks

**Comment by younes0** [comment]
Thanks nokree, I didn't understand two things:
- `activity.onCreate()` must be removed since it's called by `init()` by the library (I guess).
- this error is caused by `setContentView(R.layout.activity_main);`: I guess that the lib sets the activity view itself, so you need to move the `R.layout.activity_main` view setup into the Fragment

Based on this, I could make suggestions to the documentation

**Comment by neokree** [comment]
exactly @younes0 , you are right. 
If you would make suggestions for the documentation please tell me, every help is appreciated :smiley:

**Comment by younes0** [comment]
great :), will do :)
