### ISSUE TITLE
Themes vs Styles

### ISSUE THREAD

**Issue by mkosik** [neokree/MaterialNavigationDrawer#83]
I think themes should belog to themes.xml file, see:
http://android-developers.blogspot.sk/2014/10/appcompat-v21-material-design-for-pre.html

or see here a clarification of topic "Theme vs Style" - what belongs where (if done properly, as per guidelines):
https://chris.banes.me/2014/11/12/theme-vs-style/
http://developer.android.com/guide/topics/ui/themes.html

**Comment by neokree** [comment]
mmm yes, I have renamed my styles.xml files to themes.xml files

**Comment by mkosik** [comment]
hmm, does everything you style belong to themes.xml? but... probably yes ;)
I'll close it as soon as available in the next release. thx
