### ISSUE TITLE
Add/Remove sections outside init() method

### ISSUE THREAD

**Issue by sckoh** [neokree/MaterialNavigationDrawer#84]
For example, 
When user logout, drawer will not show logged in feature and account.
When user login, the drawer will show all the logged in feature and account.

How can I reinit the drawer?

**Comment by neokree** [comment]
you can call the <code>notifyAccountDataChanged()</code> for update the accounts

**Comment by sckoh** [comment]
How about other sections?

**Comment by neokree** [comment]
Actually you cannot insert or remove other sections asynchronously or when the account is changed, It will be a feature soon

**Comment by aalc** [comment]
you can hide sections instead.
Section section1 = this.newSection(...);
section1.getView().setVisibility(View.GONE);
