### ISSUE TITLE
Drawer doesn't react when you scrolled in ListView

### ISSUE THREAD

**Issue by randombyte-developer** [neokree/MaterialNavigationDrawer#85]
Layout: I have a RecyclerView in a Fragment. This Fragment is bound to the first section of the drawer. In the RecyclerView are 50000 entries.

Problem: I can not open the drawer with the left to right swipe when I touched the RecyclerView to scroll. Since I scrolled, I have to touch the hamburger menu to open the drawer.
And when it is open(and I scrolled before) I can only close it when I touch on the back button or I select a section. No swipe or no tap on the empty space on the right of the drawer.

When I opened the drawer(and I scrolled before) you can scroll the RecyclerView when you touch the space to the right of the drawer. That is the space, where you can see the RecyclerView. You can see that in the video at the end of this post. The scrollbar in the top right shows, that the RecyclerView scrolls.

To fix that problem, you have to restart the app. But with the next touch on the RecyclerView to scroll, it is broken.

I can reproduce this issue. You only have to

-create new project
-implement the drawer
-create a Fragment with ReycyclerView
-create an adapter and a ViewHolder for the RecyclerView
-in code, create a new instance of your adapter with min 100 items(so you can scroll)

Edit: The problem is the ListView. So, it doesn't react whith ListView and RecyclerView(extends from ListView).

Tested on Nexus 6, Nexus 6 emulator and Note 2. Demo on Note 2: https://www.youtube.com/watch?v=qSNQ5B5HT60

**Comment by silverkid** [comment]
I also have this issue, I have a ListFragment instead of a Fragment with a ListView but it's basically the same thing.

**Comment by randombyte-developer** [comment]
@silverkid Any ideas how the bug is produced? Any approach? If had a basic idea why the drawer is not moveable I would search through the code. But I have no idea where to start...

**Comment by choiruru** [comment]
@randombyte-developer , @silverkid 
i fix it with import module manually

just find MaterialDrawerLayout class in library
and change "multipaneSupport = false;" in requestDisallowInterceptTouchEvent method

its work for me

**Comment by randombyte-developer** [comment]
@choiruru ok, I'll test it later. Thank you! 
The question is, what calls requestDisallow...(false)?! Or maybe it's a bug, that multipane is bound to this intercept thing...

**Comment by choiruru** [comment]
I think we can't call requestDisallow..(false). its because MaterialDrawerLayout class is set as private variable in MaterialNavigationDrawer class. I think its a bug and I don't know why scroll detected as multipane.

**Comment by randombyte-developer** [comment]
@neokree Any comments? I think it is easy to fix.

**Comment by pawelantczak** [comment]
same here: fragment with listview.

**Comment by neokree** [comment]
Sorry guys, I had some problems in these days. 
I will fix with bug, thanks for your help.

**Comment by clh161** [comment]
The other problem is that the soft keyboard will overlap the EditText when you tap on it.

**Comment by randombyte-developer** [comment]
@clh161 I think your problem isn't related to the drawer. Or I didn't get your point. Which EditText do you mean?

**Comment by mseroczynski** [comment]
So how is fixing going? I'll have to ship my app soon, and it's still causing trouble all the time.

**Comment by randombyte-developer** [comment]
@mseroczynski I had to set marginLeft or Start to something bigger but then the layout is weird. Also it "solves" only the open problem. The close problem still exists.
I don't like to live with workarounds. Especially in this case because this is easy to fix.
Apart from that: @neokree I see, you have a lot of work. You can't fix all issues at once. But how about a 1.2.9.000000001 fix for us? Thanks! :smiley:

**Comment by torgash-ivanblch** [comment]
Really, setting "multipaneSupport = false;" in requestDisallowInterceptTouchEvent method, as choiruru stated, solves the problem, especially in my case where I have a MaterialDrawer and ViewPager with PagerSlidingTabStrip placed in together in one Activity. 
Author, what is the original form of that method for?

**Comment by neokree** [comment]
Ok, sorry for the late response, but I have a lot of work to do in these days. 
Simple change to false the multiPaneSupport boolean in MaterialDrawerLayout solve this problem when you don't want to create tablet layouts. Because I overrided the DrawerLayout class only for getting tablet content always clickable (the drawer still remain open for multipanesupport). 
So I checked if the device is a tablet, and only for tablets the multiPaneSupport variable can change. 

```java
        if(Utils.isTablet(this.getResources())) {
            // custom implementation only for tablets
            multipaneSupport = disallowIntercept;
        }
```

**Comment by neokree** [comment]
I have tested and the fix works!

**Comment by choiruru** [comment]
Thanks @neokree

**Comment by Mrjerruss** [comment]
@neokree, and when to wait for the result?

**Comment by neokree** [comment]
The fix is already online on github. For the 1.3 release on maven, you should be patient because I'm writing the library documentation.

**Comment by randombyte-developer** [comment]
Fixed! Thank you.
