### ISSUE TITLE
Extended Statusbar since 1.2.7

### ISSUE THREAD

**Issue by DavidMaza** [neokree/MaterialNavigationDrawer#87]
Hello,

I'm trying to update the version of Material Navigation Drawer I'm using from v1.2.6 to 1.2.9 to try and fix an OutOfMemory exception.

However, starting from 1.2.7, the status bar appears to extend itself on Lollipop devices. I've attached two screenshots below to illustrate the problem along with a screenshot from Android Device Monitor.

**1.2.6**
![1 2 6](https://cloud.githubusercontent.com/assets/2233700/5627784/6ef10410-95d8-11e4-824b-00651d3bac3d.png)

**1.2.9**
![1 2 9](https://cloud.githubusercontent.com/assets/2233700/5627785/71da20bc-95d8-11e4-84a6-50c4a216b3b0.png)

**Android Device Monitor 1.2.9**
![statusbar](https://cloud.githubusercontent.com/assets/2233700/5627768/12e1158e-95d8-11e4-825f-85dcfbdccb20.png)

**Comment by neokree** [comment]
maybe you would say extended Toolbar, not status bar. 
The status bar is positioned over the toolbar.

**Comment by DavidMaza** [comment]
A little hack to fix this is to add the following line of code to the init method:

    findViewById(R.id.statusBar).setVisibility(View.GONE);

**Comment by neokree** [comment]
@DavidMaza, on my example app should not do this "extension", or I am wrong? 
I have tested on virtual Nexus 6 running Lollipop 64 bit

**Comment by neokree** [comment]
@DavidMaza please check if you have setted 
```xml
<item name="android:windowTranslucentStatus">false</item>
```
into your theme. That could cause some problems with older android version.

**Comment by neokree** [comment]
if you solve your problem, please close this issue.

**Comment by DavidMaza** [comment]
Resolved some time after 1.2.9.

Thank you! :)
