### ISSUE TITLE
ActionBar hide/show when scrolling ScrollView

### ISSUE THREAD

**Issue by Hondrus** [neokree/MaterialNavigationDrawer#88]
How I can hide/show Actionbar like in Google Play app?
![screenshot_2015-01-07-03-51-26 2 1](https://cloud.githubusercontent.com/assets/3332036/5636942/084277fa-9621-11e4-9811-5e3488e3feef.jpg)
![screenshot_2015-01-07-03-51-31 2 1](https://cloud.githubusercontent.com/assets/3332036/5636945/0c7b2df8-9621-11e4-83fa-26d38517447b.jpg)

**Comment by mkosik** [comment]
Well, this is kinda app dependant. You have to observe scroll change of your scrollable view (listview, gridview, scrollview, ...) and based on observed change, you will animate showing/hiding of your AppBar (the old fashioned ActionBar). You have an access to AppBar, so you can handle it on your own, so I don't know if it belongs to Nav Drwaer lib.
http://stackoverflow.com/questions/26616427/material-design-checklist-hiding-app-bar-on-scroll

However if you are going to add it @neokree, passing a scroll event (from any scrollable view) to a lib should be solution that is general enough ;)

**Comment by phillwiggins** [comment]
Found this - it's pretty helpful :-)

https://mdxdave.de/android/android-fading-actionbar

**Comment by gamedirty** [comment]
cool~
