### ISSUE TITLE
1440 x 2560 screen issue

### ISSUE THREAD

**Issue by AngelBob** [neokree/MaterialNavigationDrawer#90]
When running in Portrait on an LG G3 the menu expands to around 150% of the screen width when DRAWERTYPE_IMAGE is set and only about 3% when no image is set.
It works without issue in Landscape.
![screenshot_2015-01-07-00-24-00](https://cloud.githubusercontent.com/assets/5631440/5638754/b4ae4582-9603-11e4-8c28-aa485add545c.png)

**Comment by neokree** [comment]
It is a currently bug with xxxhdpi devices. 
It will be fixed with the next release

**Comment by neokree** [comment]
With the last commit the fix is setted, please into the dev project.
