### ISSUE TITLE
Calligraphy conflict

### ISSUE THREAD

**Issue by grojasv** [neokree/MaterialNavigationDrawer#93]
Greetings,

If I use Calligraphy 2.0.0 in my own project I have some conflicts with MaterialNavigationDrawer Calligraphy 1.2.0 dependency.

Thanks

**Comment by muriloandrade** [comment]
Hi guys. I'm trying to use <TextView android:textStyle="bold" /> on a fragment layout but it's not working.
I'm not sure if I'm able to use Calligraphy as a transitive dependency, but I also tried to save the Roboto-Bold.ttf into my assets/fonts folder and then using the Calligraphy this way with no success:
<TextView xmlns:tools="http://schemas.android.com/tools" tools:ignore="MissingPrefix" fontPath="fonts/Roboto-Bold.ttf" />

Another trial was to create a CustomTextView and setTypeFace on constructor. Doesn't work either.

Any help? please.

Obs: I moved this comment from #42

**Comment by neokree** [comment]
@grojasv I will update the library to 2.0.0 version in the next release, so It will not be other conflicts.

**Comment by grojasv** [comment]
Thanks @neokree Calligraphy 2.0.0 has some slightly code changes, on initialization and whenever you have to wrap the Activity Context.

**Comment by neokree** [comment]
That is not a problem, the big problem is how to add to the project. Because actually the 2.0.0 version seems not online on maven, but only with a snapshot. What code are you using for add the dependency @grojasv ?

**Comment by grojasv** [comment]
Sorry about that, I was indeed using calligraphy:2.0.0-SNAPSHOT. I thought they were going to release as it was in the readme file. Maybe it's better to wait for a stable release.

Have you considered not using calligraphy to manage fonts? 

Link added:
https://github.com/chrisbanes/philm/blob/master/app/src/main/java/app/philm/in/util/TypefaceManager.java

**Comment by guilhermearaujo** [comment]
There's another bug that I think that is due Calligrafy: I have a few [me.grantland.widget.AutofitTextView]( `me.grantland.widget.AutofitTextView`) labels that should be bold, but after including `MaterialNavigationDrawer` they are no longer bolded. Also, their fonts were changed.

**Comment by neokree** [comment]
from the next release the font was not included with Calligraphy, so the problem will not exist anymore.

**Comment by guilhermearaujo** [comment]
Great news! Any ETA for the next release?

**Comment by neokree** [comment]
Actually I have released the 1.3 alpha module, clonable by github. I have added so many functionalities and before I will release on maven something official I need to test all functionalities. 
Now I'm working for creating all examples.
