### ISSUE TITLE
 Option to disable status bar gradient (KitKat)

### ISSUE THREAD

**Issue by javmarina** [neokree/MaterialNavigationDrawer#94]
Doing so, the status bar will look the same in KitKat and Lollipop. Currently, a gradient is used in KitKat, which some people think it's ugly. See http://stackoverflow.com/questions/2931953/getting-rid-of-the-gradient-at-the-top-of-an-activity-android

**Comment by neokree** [comment]
Well, I did not knew the gradient could be removed from kitkat status bar, so thank you for the information!

**Comment by mkosik** [comment]
already mentioned in #31, I tought it's resolved.

**Comment by javmarina** [comment]
"work in progress" but closed?

**Comment by neokree** [comment]
I forgot to remove the label, sorry
