### ISSUE TITLE
Wiki out-of-date.. MaterialAccount arguements

### ISSUE THREAD

**Issue by wrik** [neokree/MaterialNavigationDrawer#96]
Great library! However I just updated my local copy and now have errors regarding MaterialAccount.

A new argument (Resources res) has been added the constructor, what should be specified here?

```
    public MaterialAccount(Resources res,String title, String subTitle, Drawable photo,Bitmap background) {
        this.photo = photo;
        this.title = title;
        this.subTitle = subTitle;
        this.background = new BitmapDrawable(res,background);
        resources = res;
    }
```

**Comment by wrik** [comment]
Turns out it was an obvious solution.. You need to use getResources().

Example:
```
account = new MaterialAccount(getResources(),"NeoKree","neokree@gmail.com",getResources().getDrawable(R.drawable.photo),this.getResources().getDrawable(R.drawable.bamboo));
        this.addAccount(account);
```

**Comment by neokree** [comment]
Wiki is created for releases, into github I commited the dev version of this project, used for testing purpouse.
